/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   F:\nim\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IF:\nim\lib -o O:\nim\wnim\release\examples\nimcache\kiwi_symbolics.o O:\nim\wnim\release\examples\nimcache\kiwi_symbolics.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w;
typedef struct tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A;
typedef struct tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w {
tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable;
NF coefficient;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A {
tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* terms;
NF constant;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw {
  Exception Sup;
};
typedef NU8 tyEnum_RelationalOperator_5xNVQtJfV72RJXri8FYKwA;
struct tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw {
NimStringDesc* mName;
NF value;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow {
tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression;
NF strength;
tyEnum_RelationalOperator_5xNVQtJfV72RJXri8FYKwA op;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag {
  TGenericSeq Sup;
  tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, star__zIR3EpwtfOUvF29cWiqm7jA)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w term, NF coefficient, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(void, newTerm_CUiom7cTGYrQxNjFn2uBcwterm)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable, NF coefficient, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, star__nWGOkcgLsnRWYZmF6pMXAQ)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression, NF coefficient);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, nimNewSeqOfCap)(TNimType* typ, NI cap);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, newExpression_3HX7z0VHsgMwKC3PTO0Tcg)(tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* terms, NF constant);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, star__AOSYyJjB1bC8dut68M7CMQ)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression1, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isConstant_1B82q6bfOLoar0meYZt9c8A)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* e);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_lPdoI1hMHEVrHyZsEjWWow)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, slash__AOSYyJjB1bC8dut68M7CMQ_2)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression1, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression2);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, star__siEfhbOf2Itaci4l9avPcsA)(NF lhs, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* rhs);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, plus__poxgDPTsfr1bjlus2T0Htg)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* first, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* second);
N_LIB_PRIVATE N_NIMCALL(tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*, amp__zaoTRruwhf7z3APlnn1Hvw)(tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* x, tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* y);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, plus__elEsbhllctBHEX3ECKvMGA)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* first, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w second);
N_LIB_PRIVATE N_NIMCALL(tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*, amp__lkFfXYnh2I1DfdO255mi9aw)(tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* x, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w y);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, plus__DRcIfOit5C7faZQM4ojQrw)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression, NF constant);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, plus__KC0ghqkgQ9bzElOZgIykwqQ)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w first, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w second);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, eqeq__Lzl0sQQvbdORfkwA8Hp7qw)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable, NF constant);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, newConstraint_sjE7tUsttsqqo9cO7CVcZ4Q)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* e, tyEnum_RelationalOperator_5xNVQtJfV72RJXri8FYKwA op);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, newExpression_P51h2FGLoXA9cabbJCgPhOA)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w term, NF constant);
N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, newExpression_vLi84tTLBROaCEHi1yfzoQ)(NF constant);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, gteq__Lzl0sQQvbdORfkwA8Hp7qw_2)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable, NF constant);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, lteq__lHC20lfC3W7aLZ9berEUahA)(NF constant, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, lteq__HIjLefyH8tPd0BW8oogf5Q)(NF constant, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w term);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, lteq__lIcYAXSu7c217yjpWY0KGw)(NF constant, tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, gteq__HIjLefyH8tPd0BW8oogf5Q_2)(NF constant, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w term);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, gteq__lIcYAXSu7c217yjpWY0KGw_2)(NF constant, tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, modifyStrength_9bloI1Yj2TZAxIaRSekwqxQ)(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* constraint, NF strength);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, newConstraint_HrRPy1MzWvAkSqHD4F9bHRQ)(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* other, NF strength);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, modifyStrength_FIoB9boZJoq1bZO8Zy6H5xw)(NF strength, tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* constraint);
extern TNimType NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_Yy1a0hyEjWJ9a1RdS8eLO9ag_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_9b5pqO6tHbmc0Hs7TazVOJw_;
TNimType NTI_lPdoI1hMHEVrHyZsEjWWow_;
STRING_LITERAL(TM_1ue2SXnEsRG00OFlzdVGtw_3, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_1ue2SXnEsRG00OFlzdVGtw_4, "", 0);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, newTerm_CUiom7cTGYrQxNjFn2uBcwterm)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable, NF coefficient, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w* Result) {
	nimfr_("newTerm", "term.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_));
	nimln_(8, "term.nim");
	unsureAsgnRef((void**) (&(*Result).variable), variable);
	nimln_(9, "term.nim");
	(*Result).coefficient = coefficient;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, star__zIR3EpwtfOUvF29cWiqm7jA)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w term, NF coefficient, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w* Result) {
	tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w T1_;
	nimfr_("*", "symbolics.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_));
	nimln_(9, "symbolics.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	newTerm_CUiom7cTGYrQxNjFn2uBcwterm(term.variable, ((NF)(term.coefficient) * (NF)(coefficient)), (&T1_));
	unsureAsgnRef((void**) (&(*Result).variable), T1_.variable);
	(*Result).coefficient = T1_.coefficient;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, star__nWGOkcgLsnRWYZmF6pMXAQ)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression, NF coefficient) {
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* result;
	tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* terms;
	NI T1_;
	nimfr_("*", "symbolics.nim");
	result = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	nimln_(15, "symbolics.nim");
	T1_ = ((*expression).terms ? (*expression).terms->Sup.len : 0);
	terms = (tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*)nimNewSeqOfCap((&NTI_Yy1a0hyEjWJ9a1RdS8eLO9ag_), ((NI)chckRange(T1_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w term;
		tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* colontmp_;
		NI i;
		NI L;
		NI T3_;
		memset((void*)(&term), 0, sizeof(term));
		colontmp_ = (tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*)0;
		nimln_(16, "symbolics.nim");
		colontmp_ = (*expression).terms;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T3_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T3_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w T6_;
				NI T7_;
				NI TM_1ue2SXnEsRG00OFlzdVGtw_2;
				if (!(i < L)) goto LA5;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				term.variable = colontmp_->data[i].variable;
				term.coefficient = colontmp_->data[i].coefficient;
				nimln_(17, "symbolics.nim");
				memset((void*)(&T6_), 0, sizeof(T6_));
				star__zIR3EpwtfOUvF29cWiqm7jA(term, coefficient, (&T6_));
				terms = (tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*) incrSeqV2(&(terms)->Sup, sizeof(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w));
				T7_ = terms->Sup.len++;
				asgnRefNoCycle((void**) (&terms->data[T7_].variable), T6_.variable);
				terms->data[T7_].coefficient = T6_.coefficient;
				nimln_(3809, "system.nim");
				TM_1ue2SXnEsRG00OFlzdVGtw_2 = addInt(i, ((NI) 1));
				i = (NI)(TM_1ue2SXnEsRG00OFlzdVGtw_2);
				nimln_(3810, "system.nim");
				{
					NI T10_;
					T10_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T10_ == L))) goto LA11_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_1ue2SXnEsRG00OFlzdVGtw_3));
				}
				LA11_: ;
			} LA5: ;
		}
	}
	nimln_(20, "symbolics.nim");
	result = newExpression_3HX7z0VHsgMwKC3PTO0Tcg(terms, ((NF)((*expression).constant) * (NF)(coefficient)));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_lPdoI1hMHEVrHyZsEjWWow)(void* p, NI op) {
	tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw* a;
	a = (tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, star__AOSYyJjB1bC8dut68M7CMQ)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression1, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression2) {
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* result;
	nimfr_("*", "symbolics.nim");
{	result = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	nimln_(25, "symbolics.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isConstant_1B82q6bfOLoar0meYZt9c8A(expression1);
		if (!T3_) goto LA4_;
		nimln_(26, "symbolics.nim");
		result = star__nWGOkcgLsnRWYZmF6pMXAQ(expression2, (*expression1).constant);
		goto BeforeRet_;
	}
	goto LA1_;
	LA4_: ;
	{
		NIM_BOOL T7_;
		nimln_(27, "symbolics.nim");
		T7_ = (NIM_BOOL)0;
		T7_ = isConstant_1B82q6bfOLoar0meYZt9c8A(expression2);
		if (!T7_) goto LA8_;
		nimln_(28, "symbolics.nim");
		result = star__nWGOkcgLsnRWYZmF6pMXAQ(expression1, (*expression2).constant);
		goto BeforeRet_;
	}
	goto LA1_;
	LA8_: ;
	{
		tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw* e;
		NimStringDesc* T11_;
		e = (tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw*) newObj((&NTI_lPdoI1hMHEVrHyZsEjWWow_), sizeof(tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw));
		(*e).Sup.Sup.m_type = (&NTI_9b5pqO6tHbmc0Hs7TazVOJw_);
		nimln_(30, "symbolics.nim");
		T11_ = (NimStringDesc*)0;
		T11_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_1ue2SXnEsRG00OFlzdVGtw_4));
		if (T11_) nimGCunrefNoCycle(T11_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(30, "symbolics.nim");
		raiseException((Exception*)e, "NonlinearExpressionException");
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, slash__AOSYyJjB1bC8dut68M7CMQ_2)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression1, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression2) {
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* result;
	nimfr_("/", "symbolics.nim");
{	result = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	nimln_(35, "symbolics.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isConstant_1B82q6bfOLoar0meYZt9c8A(expression2);
		if (!T3_) goto LA4_;
		nimln_(36, "symbolics.nim");
		nimln_(32, "symbolics.nim");
		result = star__nWGOkcgLsnRWYZmF6pMXAQ(expression1, ((NF)(1.0000000000000000e+000) / (NF)((*expression2).constant)));
		goto BeforeRet_;
	}
	goto LA1_;
	LA4_: ;
	{
		tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw* e;
		NimStringDesc* T7_;
		e = (tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw*) newObj((&NTI_lPdoI1hMHEVrHyZsEjWWow_), sizeof(tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw));
		(*e).Sup.Sup.m_type = (&NTI_9b5pqO6tHbmc0Hs7TazVOJw_);
		nimln_(38, "symbolics.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_1ue2SXnEsRG00OFlzdVGtw_4));
		if (T7_) nimGCunrefNoCycle(T7_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(38, "symbolics.nim");
		raiseException((Exception*)e, "NonlinearExpressionException");
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, star__siEfhbOf2Itaci4l9avPcsA)(NF lhs, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* rhs) {
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* result;
	nimfr_("*", "symbolics.nim");
	result = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	nimln_(43, "symbolics.nim");
	result = star__nWGOkcgLsnRWYZmF6pMXAQ(rhs, lhs);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, plus__poxgDPTsfr1bjlus2T0Htg)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* first, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* second) {
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* result;
	tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* T1_;
	nimfr_("+", "symbolics.nim");
	result = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	nimln_(49, "symbolics.nim");
	T1_ = (tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*)0;
	T1_ = amp__zaoTRruwhf7z3APlnn1Hvw((*first).terms, (*second).terms);
	result = newExpression_3HX7z0VHsgMwKC3PTO0Tcg(T1_, ((NF)((*first).constant) + (NF)((*second).constant)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, plus__elEsbhllctBHEX3ECKvMGA)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* first, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w second) {
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* result;
	tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* T1_;
	nimfr_("+", "symbolics.nim");
	result = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	nimln_(53, "symbolics.nim");
	T1_ = (tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*)0;
	T1_ = amp__lkFfXYnh2I1DfdO255mi9aw((*first).terms, second);
	result = newExpression_3HX7z0VHsgMwKC3PTO0Tcg(T1_, (*first).constant);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, plus__DRcIfOit5C7faZQM4ojQrw)(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression, NF constant) {
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* result;
	nimfr_("+", "symbolics.nim");
	result = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	nimln_(58, "symbolics.nim");
	result = newExpression_3HX7z0VHsgMwKC3PTO0Tcg((*expression).terms, ((NF)((*expression).constant) + (NF)(constant)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*, plus__KC0ghqkgQ9bzElOZgIykwqQ)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w first, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w second) {
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* result;
	tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag* T1_;
	nimfr_("+", "symbolics.nim");
	result = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	nimln_(65, "symbolics.nim");
	T1_ = (tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*)0;
	T1_ = (tySequence_Yy1a0hyEjWJ9a1RdS8eLO9ag*) newSeq((&NTI_Yy1a0hyEjWJ9a1RdS8eLO9ag_), 2);
	asgnRefNoCycle((void**) (&T1_->data[0].variable), first.variable);
	T1_->data[0].coefficient = first.coefficient;
	asgnRefNoCycle((void**) (&T1_->data[1].variable), second.variable);
	T1_->data[1].coefficient = second.coefficient;
	result = newExpression_3HX7z0VHsgMwKC3PTO0Tcg(T1_, 0.0);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, eqeq__Lzl0sQQvbdORfkwA8Hp7qw)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable, NF constant) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w T1_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T2_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T3_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T4_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T5_;
	nimfr_("==", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(87, "symbolics.nim");
	nimln_(104, "symbolics.nim");
	nimln_(113, "symbolics.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	newTerm_CUiom7cTGYrQxNjFn2uBcwterm(variable, 1.0000000000000000e+000, (&T1_));
	T2_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T2_ = newExpression_P51h2FGLoXA9cabbJCgPhOA(T1_, 0.0);
	nimln_(90, "symbolics.nim");
	nimln_(113, "symbolics.nim");
	T3_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T3_ = newExpression_vLi84tTLBROaCEHi1yfzoQ(constant);
	T4_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T4_ = star__nWGOkcgLsnRWYZmF6pMXAQ(T3_, -1.0000000000000000e+000);
	T5_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T5_ = plus__poxgDPTsfr1bjlus2T0Htg(T2_, T4_);
	result = newConstraint_sjE7tUsttsqqo9cO7CVcZ4Q(T5_, ((tyEnum_RelationalOperator_5xNVQtJfV72RJXri8FYKwA) 2));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, gteq__Lzl0sQQvbdORfkwA8Hp7qw_2)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable, NF constant) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w T1_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T2_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T3_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T4_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T5_;
	nimfr_(">=", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(97, "symbolics.nim");
	nimln_(107, "symbolics.nim");
	nimln_(120, "symbolics.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	newTerm_CUiom7cTGYrQxNjFn2uBcwterm(variable, 1.0000000000000000e+000, (&T1_));
	T2_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T2_ = newExpression_P51h2FGLoXA9cabbJCgPhOA(T1_, 0.0);
	nimln_(100, "symbolics.nim");
	nimln_(120, "symbolics.nim");
	T3_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T3_ = newExpression_vLi84tTLBROaCEHi1yfzoQ(constant);
	T4_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T4_ = star__nWGOkcgLsnRWYZmF6pMXAQ(T3_, -1.0000000000000000e+000);
	T5_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T5_ = plus__poxgDPTsfr1bjlus2T0Htg(T2_, T4_);
	result = newConstraint_sjE7tUsttsqqo9cO7CVcZ4Q(T5_, ((tyEnum_RelationalOperator_5xNVQtJfV72RJXri8FYKwA) 1));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, lteq__lHC20lfC3W7aLZ9berEUahA)(NF constant, tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* expression) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T1_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T2_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T3_;
	nimfr_("<=", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(92, "symbolics.nim");
	nimln_(125, "symbolics.nim");
	T1_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T1_ = newExpression_vLi84tTLBROaCEHi1yfzoQ(constant);
	T2_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T2_ = star__nWGOkcgLsnRWYZmF6pMXAQ(expression, -1.0000000000000000e+000);
	T3_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T3_ = plus__poxgDPTsfr1bjlus2T0Htg(T1_, T2_);
	result = newConstraint_sjE7tUsttsqqo9cO7CVcZ4Q(T3_, ((tyEnum_RelationalOperator_5xNVQtJfV72RJXri8FYKwA) 0));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, lteq__HIjLefyH8tPd0BW8oogf5Q)(NF constant, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w term) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T1_;
	nimfr_("<=", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(126, "symbolics.nim");
	T1_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T1_ = newExpression_P51h2FGLoXA9cabbJCgPhOA(term, 0.0);
	result = lteq__lHC20lfC3W7aLZ9berEUahA(constant, T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, lteq__lIcYAXSu7c217yjpWY0KGw)(NF constant, tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w T1_;
	nimfr_("<=", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(127, "symbolics.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	newTerm_CUiom7cTGYrQxNjFn2uBcwterm(variable, 1.0000000000000000e+000, (&T1_));
	result = lteq__HIjLefyH8tPd0BW8oogf5Q(constant, T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, gteq__HIjLefyH8tPd0BW8oogf5Q_2)(NF constant, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w term) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T1_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T2_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T3_;
	tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A* T4_;
	nimfr_(">=", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(97, "symbolics.nim");
	nimln_(129, "symbolics.nim");
	T1_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T1_ = newExpression_vLi84tTLBROaCEHi1yfzoQ(constant);
	nimln_(98, "symbolics.nim");
	nimln_(129, "symbolics.nim");
	T2_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T2_ = newExpression_P51h2FGLoXA9cabbJCgPhOA(term, 0.0);
	T3_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T3_ = star__nWGOkcgLsnRWYZmF6pMXAQ(T2_, -1.0000000000000000e+000);
	T4_ = (tyObject_ExpressioncolonObjectType__A9c9axh2HstEPzMZE5RSWy4A*)0;
	T4_ = plus__poxgDPTsfr1bjlus2T0Htg(T1_, T3_);
	result = newConstraint_sjE7tUsttsqqo9cO7CVcZ4Q(T4_, ((tyEnum_RelationalOperator_5xNVQtJfV72RJXri8FYKwA) 1));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, gteq__lIcYAXSu7c217yjpWY0KGw_2)(NF constant, tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w T1_;
	nimfr_(">=", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(130, "symbolics.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	newTerm_CUiom7cTGYrQxNjFn2uBcwterm(variable, 1.0000000000000000e+000, (&T1_));
	result = gteq__HIjLefyH8tPd0BW8oogf5Q_2(constant, T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, modifyStrength_9bloI1Yj2TZAxIaRSekwqxQ)(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* constraint, NF strength) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	nimfr_("modifyStrength", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(134, "symbolics.nim");
	result = newConstraint_HrRPy1MzWvAkSqHD4F9bHRQ(constraint, strength);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*, modifyStrength_FIoB9boZJoq1bZO8Zy6H5xw)(NF strength, tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* constraint) {
	tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow* result;
	nimfr_("modifyStrength", "symbolics.nim");
	result = (tyObject_ConstraintcolonObjectType__l7RCco3bFvyRGF9ajbLjoow*)0;
	nimln_(137, "symbolics.nim");
	result = modifyStrength_FIoB9boZJoq1bZO8Zy6H5xw(strength, constraint);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, kiwi_symbolicsInit000)(void) {
	nimfr_("symbolics", "symbolics.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, kiwi_symbolicsDatInit000)(void) {
static TNimNode TM_1ue2SXnEsRG00OFlzdVGtw_0[1];
NTI_9b5pqO6tHbmc0Hs7TazVOJw_.size = sizeof(tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw);
NTI_9b5pqO6tHbmc0Hs7TazVOJw_.kind = 17;
NTI_9b5pqO6tHbmc0Hs7TazVOJw_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_1ue2SXnEsRG00OFlzdVGtw_0[0].len = 0; TM_1ue2SXnEsRG00OFlzdVGtw_0[0].kind = 2;
NTI_9b5pqO6tHbmc0Hs7TazVOJw_.node = &TM_1ue2SXnEsRG00OFlzdVGtw_0[0];
NTI_lPdoI1hMHEVrHyZsEjWWow_.size = sizeof(tyObject_NonlinearExpressionException_9b5pqO6tHbmc0Hs7TazVOJw*);
NTI_lPdoI1hMHEVrHyZsEjWWow_.kind = 22;
NTI_lPdoI1hMHEVrHyZsEjWWow_.base = (&NTI_9b5pqO6tHbmc0Hs7TazVOJw_);
NTI_lPdoI1hMHEVrHyZsEjWWow_.marker = Marker_tyRef_lPdoI1hMHEVrHyZsEjWWow;
}

