/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   F:\nim\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IF:\nim\lib -o O:\nim\wnim\release\examples\nimcache\kiwi_term.o O:\nim\wnim\release\examples\nimcache\kiwi_term.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw;
typedef struct tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w {
tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable;
NF coefficient;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw {
NimStringDesc* mName;
NF value;
};
static N_INLINE(void, newTerm_CUiom7cTGYrQxNjFn2uBcwterm)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable, NF coefficient, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, value_mDzmCKZWvYjcBJAjOR4nTwterm)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__OLEOmoksvjZmzXglLPjLkg)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w t);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__LluWHqnqFFLfe55A9aNwtbA_2)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* v);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
TNimType NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_;
extern TNimType NTI_BvrmYJmXOiwxlfPTQ4GBwA_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_9cyJIhgSXuxs45dMk82f6nA_3, "variable: (", 11);
STRING_LITERAL(TM_9cyJIhgSXuxs45dMk82f6nA_4, ") coefficient: ", 15);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, newTerm_CUiom7cTGYrQxNjFn2uBcwterm)(tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* variable, NF coefficient, tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w* Result) {
	nimfr_("newTerm", "term.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_));
	nimln_(8, "term.nim");
	unsureAsgnRef((void**) (&(*Result).variable), variable);
	nimln_(9, "term.nim");
	(*Result).coefficient = coefficient;
	popFrame();
}

static N_INLINE(NF, value_mDzmCKZWvYjcBJAjOR4nTwterm)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w t) {
	NF result;
	nimfr_("value", "term.nim");
	result = (NF)0;
	nimln_(12, "term.nim");
	result = ((NF)(t.coefficient) * (NF)((*t.variable).value));
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__OLEOmoksvjZmzXglLPjLkg)(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	nimfr_("$", "term.nim");
	result = (NimStringDesc*)0;
	nimln_(15, "term.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__LluWHqnqFFLfe55A9aNwtbA_2(t.variable);
	T3_ = (NimStringDesc*)0;
	T3_ = nimFloatToStr(t.coefficient);
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + 26);
appendString(T1_, ((NimStringDesc*) &TM_9cyJIhgSXuxs45dMk82f6nA_3));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_9cyJIhgSXuxs45dMk82f6nA_4));
appendString(T1_, T3_);
	result = T1_;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, kiwi_termInit000)(void) {
	nimfr_("term", "term.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, kiwi_termDatInit000)(void) {
static TNimNode* TM_9cyJIhgSXuxs45dMk82f6nA_2[2];
static TNimNode TM_9cyJIhgSXuxs45dMk82f6nA_0[3];
NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_.size = sizeof(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w);
NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_.kind = 18;
NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_.base = 0;
NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_.flags = 2;
TM_9cyJIhgSXuxs45dMk82f6nA_2[0] = &TM_9cyJIhgSXuxs45dMk82f6nA_0[1];
TM_9cyJIhgSXuxs45dMk82f6nA_0[1].kind = 1;
TM_9cyJIhgSXuxs45dMk82f6nA_0[1].offset = offsetof(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w, variable);
TM_9cyJIhgSXuxs45dMk82f6nA_0[1].typ = (&NTI_BvrmYJmXOiwxlfPTQ4GBwA_);
TM_9cyJIhgSXuxs45dMk82f6nA_0[1].name = "variable";
TM_9cyJIhgSXuxs45dMk82f6nA_2[1] = &TM_9cyJIhgSXuxs45dMk82f6nA_0[2];
TM_9cyJIhgSXuxs45dMk82f6nA_0[2].kind = 1;
TM_9cyJIhgSXuxs45dMk82f6nA_0[2].offset = offsetof(tyObject_Term_qLxQ9bKfr9aMzqZ9aEXgWgn4w, coefficient);
TM_9cyJIhgSXuxs45dMk82f6nA_0[2].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_9cyJIhgSXuxs45dMk82f6nA_0[2].name = "coefficient";
TM_9cyJIhgSXuxs45dMk82f6nA_0[0].len = 2; TM_9cyJIhgSXuxs45dMk82f6nA_0[0].kind = 2; TM_9cyJIhgSXuxs45dMk82f6nA_0[0].sons = &TM_9cyJIhgSXuxs45dMk82f6nA_2[0];
NTI_qLxQ9bKfr9aMzqZ9aEXgWgn4w_.node = &TM_9cyJIhgSXuxs45dMk82f6nA_0[0];
}

