/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   F:\nim\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IF:\nim\lib -o O:\nim\wnim\release\examples\nimcache\kiwi_strength.o O:\nim\wnim\release\examples\nimcache\kiwi_strength.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(NF, createStrength_b9ae4zNeDsbu8alYzuWW0IA)(NF a, NF b, NF c, NF w);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, clipStrength_fgLWfxVl7n1qcZLAgaLJTwstrength)(NF value);
N_LIB_PRIVATE N_NIMCALL(NF, clamp_BGhQiHv5LFkg9aDgeidEq0g)(NF x, NF a, NF b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3700, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NF, createStrength_b9ae4zNeDsbu8alYzuWW0IA)(NF a, NF b, NF c, NF w) {
	NF result;
	nimfr_("createStrength", "strength.nim");
	result = (NF)0;
	nimln_(2, "strength.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&result), ((NF)(((0.0 >= ((1.0000000000000000e+003 <= ((NF)(a) * (NF)(w))) ? 1.0000000000000000e+003 : ((NF)(a) * (NF)(w)))) ? 0.0 : ((1.0000000000000000e+003 <= ((NF)(a) * (NF)(w))) ? 1.0000000000000000e+003 : ((NF)(a) * (NF)(w))))) * (NF)(1.0000000000000000e+006)));
	nimln_(3, "strength.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&result), ((NF)(((0.0 >= ((1.0000000000000000e+003 <= ((NF)(b) * (NF)(w))) ? 1.0000000000000000e+003 : ((NF)(b) * (NF)(w)))) ? 0.0 : ((1.0000000000000000e+003 <= ((NF)(b) * (NF)(w))) ? 1.0000000000000000e+003 : ((NF)(b) * (NF)(w))))) * (NF)(1.0000000000000000e+003)));
	nimln_(4, "strength.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&result), ((0.0 >= ((1.0000000000000000e+003 <= ((NF)(c) * (NF)(w))) ? 1.0000000000000000e+003 : ((NF)(c) * (NF)(w)))) ? 0.0 : ((1.0000000000000000e+003 <= ((NF)(c) * (NF)(w))) ? 1.0000000000000000e+003 : ((NF)(c) * (NF)(w)))));
	popFrame();
	return result;
}

static N_INLINE(NF, clipStrength_fgLWfxVl7n1qcZLAgaLJTwstrength)(NF value) {
	NF result;
	nimfr_("clipStrength", "strength.nim");
	result = (NF)0;
	nimln_(11, "strength.nim");
	result = clamp_BGhQiHv5LFkg9aDgeidEq0g(value, 0.0, 1.0010010000000000e+009);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, kiwi_strengthInit000)(void) {
	nimfr_("strength", "strength.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, kiwi_strengthDatInit000)(void) {
}

