/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   F:\nim\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IF:\nim\lib -o O:\nim\wnim\release\examples\nimcache\stdlib_sets.o O:\nim\wnim\release\examples\nimcache\stdlib_sets.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA;
typedef struct tySequence_U5QYqmtUND3fb25zvpemlg tySequence_U5QYqmtUND3fb25zvpemlg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_Ll5iolPASSzOEheeSNjmiw tyTuple_Ll5iolPASSzOEheeSNjmiw;
typedef struct tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q;
typedef struct tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA;
typedef struct tySequence_q1CYcV9cohVCitBx05qim8w tySequence_q1CYcV9cohVCitBx05qim8w;
typedef struct tyTuple_pNXh8jOAX7m9ahUugForVlw tyTuple_pNXh8jOAX7m9ahUugForVlw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA;
typedef struct tySequence_h26ZlPH9aOPYIh58Am8MiyA tySequence_h26ZlPH9aOPYIh58Am8MiyA;
typedef struct tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg;
typedef struct tyTuple_eXmvJ9a9c9biYHSPeysfLxHig tyTuple_eXmvJ9a9c9biYHSPeysfLxHig;
typedef struct RootObj RootObj;
typedef struct tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w;
typedef struct tySequence_ycFDskWNp4jtk39aIuuDoHA tySequence_ycFDskWNp4jtk39aIuuDoHA;
typedef struct tyTuple_FtZxsWeKlOo83uVL9c4OOmg tyTuple_FtZxsWeKlOo83uVL9c4OOmg;
typedef struct tyObject_wStatusBarcolonObjectType__vo8kVIAtbX1itw5NocPmLg tyObject_wStatusBarcolonObjectType__vo8kVIAtbX1itw5NocPmLg;
typedef struct tyObject_wToolBarcolonObjectType__2sEaVgZyXWY9cWOfPC9cBlSQ tyObject_wToolBarcolonObjectType__2sEaVgZyXWY9cWOfPC9cBlSQ;
typedef struct tyObject_wFontcolonObjectType__X29b7QPs6exs9afv638QYRrQ tyObject_wFontcolonObjectType__X29b7QPs6exs9afv638QYRrQ;
typedef struct tyObject_wBrushcolonObjectType__wtTQ9a2eLTnt89be63Xu9cFtw tyObject_wBrushcolonObjectType__wtTQ9a2eLTnt89be63Xu9cFtw;
typedef struct tyObject_wCursorcolonObjectType__L42FjqGXK6RB9a40yintB9aw tyObject_wCursorcolonObjectType__L42FjqGXK6RB9a40yintB9aw;
typedef struct tyObject_Table_Nzd0y9bF9cqcqPaWbUEDIDXQ tyObject_Table_Nzd0y9bF9cqcqPaWbUEDIDXQ;
typedef struct tySequence_9cOTMEBwo55wzlZjPFOYQHg tySequence_9cOTMEBwo55wzlZjPFOYQHg;
typedef struct tyObject_wAcceleratorTablecolonObjectType__Jf9cEoqNXWroaftMQTNNUDg tyObject_wAcceleratorTablecolonObjectType__Jf9cEoqNXWroaftMQTNNUDg;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_wSizingInfocolonObjectType__Aa2dIYi6KZnI9ckxCpb5Xww tyObject_wSizingInfocolonObjectType__Aa2dIYi6KZnI9ckxCpb5Xww;
typedef struct tyObject_wDraggableInfocolonObjectType__2BZLwTupJRTWgL4PaL9cWZw tyObject_wDraggableInfocolonObjectType__2BZLwTupJRTWgL4PaL9cWZw;
typedef struct tyObject_wMenuBarcolonObjectType__iFHpBcYgEPIJPGBuoJdTMw tyObject_wMenuBarcolonObjectType__iFHpBcYgEPIJPGBuoJdTMw;
typedef struct tyObject_wIconcolonObjectType__6fF55dXerC0LG5WDiY2Tbw tyObject_wIconcolonObjectType__6fF55dXerC0LG5WDiY2Tbw;
typedef struct tyTuple_Q9cGQekOok3ahAXVy9axgf9aA tyTuple_Q9cGQekOok3ahAXVy9axgf9aA;
typedef struct tyObject_wEventcolonObjectType__uUaAHKFmAV5MWgXoDq0lQQ tyObject_wEventcolonObjectType__uUaAHKFmAV5MWgXoDq0lQQ;
typedef struct tyObject_wControlcolonObjectType__yeTY9aITRoONBr9bxxLt04SA tyObject_wControlcolonObjectType__yeTY9aITRoONBr9bxxLt04SA;
typedef struct tySequence_T0z34G8Ya9cBkfJWxv7RbzA tySequence_T0z34G8Ya9cBkfJWxv7RbzA;
typedef struct tyObject_wGdiObjectcolonObjectType__8tqtxPp3JdHT18Fg357l6Q tyObject_wGdiObjectcolonObjectType__8tqtxPp3JdHT18Fg357l6Q;
typedef struct tyTuple_5FmmQw5czEqyIS6OX5ADRQ tyTuple_5FmmQw5czEqyIS6OX5ADRQ;
typedef struct tyObject_DoublyLinkedList_lS8cbiVegM6G2dXDZSjosA tyObject_DoublyLinkedList_lS8cbiVegM6G2dXDZSjosA;
typedef struct tyObject_DoublyLinkedNodeObj_1vaaI59c77NJCwY6W4au9c8w tyObject_DoublyLinkedNodeObj_1vaaI59c77NJCwY6W4au9c8w;
typedef struct tySequence_0YDEcvfYupp19cAmp9bz9c5EA tySequence_0YDEcvfYupp19cAmp9bz9c5EA;
typedef struct tyTuple_KNeKpKPHFicng4e3OvpAWQ tyTuple_KNeKpKPHFicng4e3OvpAWQ;
typedef struct tyTuple_aAVnisOFnmoSd9cfJ9aQgJNw tyTuple_aAVnisOFnmoSd9cfJ9aQgJNw;
typedef struct tyObject_wMenuBasecolonObjectType__sJxVdMGMr78Iy2Qznhvbjg tyObject_wMenuBasecolonObjectType__sJxVdMGMr78Iy2Qznhvbjg;
typedef struct tySequence_F7BzjrS6ruvt9cV9ccSEA50A tySequence_F7BzjrS6ruvt9cV9ccSEA50A;
typedef struct tyObject_wToolBarToolcolonObjectType__Mevf0bX1yAVjI8KJD0HIqw tyObject_wToolBarToolcolonObjectType__Mevf0bX1yAVjI8KJD0HIqw;
typedef struct tyObject_ACCEL_IwPxdEWRYYSQ39bY1mW9aFeQ tyObject_ACCEL_IwPxdEWRYYSQ39bY1mW9aFeQ;
typedef struct tyObject_wMenucolonObjectType__fCPsDvxqCFVsAnPEAAb0Jw tyObject_wMenucolonObjectType__fCPsDvxqCFVsAnPEAAb0Jw;
typedef struct tyObject_wBitmapcolonObjectType__iQ6sGy0YDhzCvfKqbg9anUw tyObject_wBitmapcolonObjectType__iQ6sGy0YDhzCvfKqbg9anUw;
typedef struct tySequence_GEQhRx9bHjh7gn2K1qTnG8A tySequence_GEQhRx9bHjh7gn2K1qTnG8A;
typedef struct tyObject_CountTable_9cp9cpkNj9aQOr76ZTLeDIRUA tyObject_CountTable_9cp9cpkNj9aQOr76ZTLeDIRUA;
typedef struct tySequence_ZQphAAUq7LCG9brR1SFDrPg tySequence_ZQphAAUq7LCG9brR1SFDrPg;
typedef struct tyObject_wMenuItemcolonObjectType__Fz7rKvpEKh9aDf9chc3kE2qw tyObject_wMenuItemcolonObjectType__Fz7rKvpEKh9aDf9chc3kE2qw;
typedef struct tyTuple_yh69bd2OuOhYRzIjAmTKbdA tyTuple_yh69bd2OuOhYRzIjAmTKbdA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA {
tySequence_U5QYqmtUND3fb25zvpemlg* data;
NI counter;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyTuple_Ll5iolPASSzOEheeSNjmiw {
NI Field0;
NI32 Field1;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q {
tySequence_q1CYcV9cohVCitBx05qim8w* data;
NI counter;
};
struct tyTuple_pNXh8jOAX7m9ahUugForVlw {
NI Field0;
tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* Field1;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA {
tySequence_h26ZlPH9aOPYIh58Am8MiyA* data;
NI counter;
};
struct tyTuple_eXmvJ9a9c9biYHSPeysfLxHig {
NI Field0;
tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* Field1;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA {
  RootObj Sup;
tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* mLeft;
tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* mRight;
tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* mTop;
tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw* mBottom;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_FtZxsWeKlOo83uVL9c4OOmg {
NI Field0;
NI Field1;
NI Field2;
NI Field3;
};
struct tyObject_Table_Nzd0y9bF9cqcqPaWbUEDIDXQ {
tySequence_9cOTMEBwo55wzlZjPFOYQHg* data;
NI counter;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w {
  tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA Sup;
NI mHwnd;
tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w* mParent;
tySequence_ycFDskWNp4jtk39aIuuDoHA* mChildren;
tyTuple_FtZxsWeKlOo83uVL9c4OOmg mMargin;
tyObject_wStatusBarcolonObjectType__vo8kVIAtbX1itw5NocPmLg* mStatusBar;
tyObject_wToolBarcolonObjectType__2sEaVgZyXWY9cWOfPC9cBlSQ* mToolBar;
tyObject_wFontcolonObjectType__X29b7QPs6exs9afv638QYRrQ* mFont;
NI32 mBackgroundColor;
NI32 mForegroundColor;
tyObject_wBrushcolonObjectType__wtTQ9a2eLTnt89be63Xu9cFtw* mBackgroundBrush;
tyObject_wCursorcolonObjectType__L42FjqGXK6RB9a40yintB9aw* mCursor;
tyObject_wCursorcolonObjectType__L42FjqGXK6RB9a40yintB9aw* mOverrideCursor;
tyObject_Table_Nzd0y9bF9cqcqPaWbUEDIDXQ mSystemConnectionTable;
tyObject_Table_Nzd0y9bF9cqcqPaWbUEDIDXQ mConnectionTable;
tyObject_wAcceleratorTablecolonObjectType__Jf9cEoqNXWroaftMQTNNUDg* mAcceleratorTable;
tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w* mSaveFocus;
NIM_BOOL mFocusable;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ mMaxSize;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ mMinSize;
NI mDummyParent;
NIM_BOOL mMouseInWindow;
tyObject_wSizingInfocolonObjectType__Aa2dIYi6KZnI9ckxCpb5Xww* mSizingInfo;
tyObject_wDraggableInfocolonObjectType__2BZLwTupJRTWgL4PaL9cWZw* mDraggableInfo;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_wEventcolonObjectType__uUaAHKFmAV5MWgXoDq0lQQ* event, void* ClE_0);
void* ClE_0;
} tyProc_YYUaYYVWar3sptHT4LdXug;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tyTuple_Q9cGQekOok3ahAXVy9axgf9aA {
NI32 Field0;
NI Field1;
tyProc_YYUaYYVWar3sptHT4LdXug Field2;
tyProc_IIomJ6ptE6vfJ5zRbATgkQ Field3;
NI Field4;
NIM_BOOL Field5;
};
struct tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg {
  tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w Sup;
tyObject_wMenuBarcolonObjectType__iFHpBcYgEPIJPGBuoJdTMw* mMenuBar;
tyObject_wIconcolonObjectType__6fF55dXerC0LG5WDiY2Tbw* mIcon;
tySequence_ycFDskWNp4jtk39aIuuDoHA* mDisableList;
tyObject_wIconcolonObjectType__6fF55dXerC0LG5WDiY2Tbw* mTrayIcon;
NimStringDesc* mTrayToolTip;
NIM_BOOL mTrayIconAdded;
tyTuple_Q9cGQekOok3ahAXVy9axgf9aA mTrayConn;
tyTuple_Q9cGQekOok3ahAXVy9axgf9aA mCreateConn;
};
struct tyObject_VariablecolonObjectType__lxa06ORp9bdmcVMa6w4sGbw {
NimStringDesc* mName;
NF value;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_wControlcolonObjectType__yeTY9aITRoONBr9bxxLt04SA {
  tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w Sup;
};
typedef NI32 tyArray_5SV2SHwn9afaDnWBL2ydsJw[256];
struct tyObject_wStatusBarcolonObjectType__vo8kVIAtbX1itw5NocPmLg {
  tyObject_wControlcolonObjectType__yeTY9aITRoONBr9bxxLt04SA Sup;
NI mFiledNumbers;
tyArray_5SV2SHwn9afaDnWBL2ydsJw mWidths;
};
struct tyObject_wToolBarcolonObjectType__2sEaVgZyXWY9cWOfPC9cBlSQ {
  tyObject_wControlcolonObjectType__yeTY9aITRoONBr9bxxLt04SA Sup;
tySequence_T0z34G8Ya9cBkfJWxv7RbzA* mTools;
};
struct tyObject_wGdiObjectcolonObjectType__8tqtxPp3JdHT18Fg357l6Q {
  RootObj Sup;
NI mHandle;
};
struct tyObject_wFontcolonObjectType__X29b7QPs6exs9afv638QYRrQ {
  tyObject_wGdiObjectcolonObjectType__8tqtxPp3JdHT18Fg357l6Q Sup;
NF mPointSize;
NI mFamily;
NI mWeight;
NIM_BOOL mItalic;
NIM_BOOL mUnderline;
NimStringDesc* mFaceName;
NI mEncoding;
};
struct tyObject_wBrushcolonObjectType__wtTQ9a2eLTnt89be63Xu9cFtw {
  tyObject_wGdiObjectcolonObjectType__8tqtxPp3JdHT18Fg357l6Q Sup;
NI32 mColor;
NI32 mStyle;
};
struct tyObject_wCursorcolonObjectType__L42FjqGXK6RB9a40yintB9aw {
  tyObject_wGdiObjectcolonObjectType__8tqtxPp3JdHT18Fg357l6Q Sup;
NIM_BOOL mDeletable;
NIM_BOOL mIconResource;
};
struct tyObject_DoublyLinkedList_lS8cbiVegM6G2dXDZSjosA {
tyObject_DoublyLinkedNodeObj_1vaaI59c77NJCwY6W4au9c8w* head;
tyObject_DoublyLinkedNodeObj_1vaaI59c77NJCwY6W4au9c8w* tail;
};
struct tyTuple_5FmmQw5czEqyIS6OX5ADRQ {
NI Field0;
NI32 Field1;
tyObject_DoublyLinkedList_lS8cbiVegM6G2dXDZSjosA Field2;
};
struct tyObject_wAcceleratorTablecolonObjectType__Jf9cEoqNXWroaftMQTNNUDg {
  RootObj Sup;
NI mHandle;
tySequence_0YDEcvfYupp19cAmp9bz9c5EA* mAccels;
NIM_BOOL mModified;
};
struct tyTuple_KNeKpKPHFicng4e3OvpAWQ {
NIM_BOOL Field0;
NIM_BOOL Field1;
NIM_BOOL Field2;
NIM_BOOL Field3;
};
struct tyTuple_aAVnisOFnmoSd9cfJ9aQgJNw {
tyTuple_Q9cGQekOok3ahAXVy9axgf9aA Field0;
tyTuple_Q9cGQekOok3ahAXVy9axgf9aA Field1;
tyTuple_Q9cGQekOok3ahAXVy9axgf9aA Field2;
};
struct tyObject_wSizingInfocolonObjectType__Aa2dIYi6KZnI9ckxCpb5Xww {
tyTuple_FtZxsWeKlOo83uVL9c4OOmg border;
NIM_BOOL dragging;
tyTuple_KNeKpKPHFicng4e3OvpAWQ ready;
tyTuple_FtZxsWeKlOo83uVL9c4OOmg offset;
tyTuple_aAVnisOFnmoSd9cfJ9aQgJNw connection;
};
struct tyObject_wDraggableInfocolonObjectType__2BZLwTupJRTWgL4PaL9cWZw {
NIM_BOOL enable;
NIM_BOOL inClient;
NIM_BOOL dragging;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ startMousePos;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ startPos;
tyTuple_aAVnisOFnmoSd9cfJ9aQgJNw connection;
};
struct tyObject_wMenuBasecolonObjectType__sJxVdMGMr78Iy2Qznhvbjg {
  RootObj Sup;
NI mHmenu;
};
struct tyObject_wMenuBarcolonObjectType__iFHpBcYgEPIJPGBuoJdTMw {
  tyObject_wMenuBasecolonObjectType__sJxVdMGMr78Iy2Qznhvbjg Sup;
tySequence_F7BzjrS6ruvt9cV9ccSEA50A* mMenuList;
tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA mParentFrameSet;
};
struct tyObject_wIconcolonObjectType__6fF55dXerC0LG5WDiY2Tbw {
  tyObject_wGdiObjectcolonObjectType__8tqtxPp3JdHT18Fg357l6Q Sup;
NI mWidth;
NI mHeight;
};
typedef NI8 tyArray_EUdzkGykm9crxB9b8gAu6G8g[256];
struct tyObject_wEventcolonObjectType__uUaAHKFmAV5MWgXoDq0lQQ {
  RootObj Sup;
tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w* mWindow;
NI mOrigin;
NI32 mMsg;
NI mId;
NU64 mWparam;
NI64 mLparam;
NI mUserData;
NIM_BOOL mSkip;
NI mPropagationLevel;
NI64 mResult;
tyArray_EUdzkGykm9crxB9b8gAu6G8g mKeyStatus;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ mMousePos;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ mClientPos;
};
struct tyObject_DoublyLinkedNodeObj_1vaaI59c77NJCwY6W4au9c8w {
tyObject_DoublyLinkedNodeObj_1vaaI59c77NJCwY6W4au9c8w* next;
tyObject_DoublyLinkedNodeObj_1vaaI59c77NJCwY6W4au9c8w* prev;
tyTuple_Q9cGQekOok3ahAXVy9axgf9aA value;
};
struct tyObject_ACCEL_IwPxdEWRYYSQ39bY1mW9aFeQ {
NU8 fVirt;
NU16 key;
NU16 cmd;
};
struct tyObject_wToolBarToolcolonObjectType__Mevf0bX1yAVjI8KJD0HIqw {
  RootObj Sup;
tyObject_wBitmapcolonObjectType__iQ6sGy0YDhzCvfKqbg9anUw* mBitmap;
NimStringDesc* mShortHelp;
NimStringDesc* mLongHelp;
tyObject_wMenucolonObjectType__fCPsDvxqCFVsAnPEAAb0Jw* mMenu;
};
struct tyObject_CountTable_9cp9cpkNj9aQOr76ZTLeDIRUA {
tySequence_ZQphAAUq7LCG9brR1SFDrPg* data;
NI counter;
};
struct tyObject_wMenucolonObjectType__fCPsDvxqCFVsAnPEAAb0Jw {
  tyObject_wMenuBasecolonObjectType__sJxVdMGMr78Iy2Qznhvbjg Sup;
tyObject_wBitmapcolonObjectType__iQ6sGy0YDhzCvfKqbg9anUw* mBitmap;
tySequence_GEQhRx9bHjh7gn2K1qTnG8A* mItemList;
tyObject_CountTable_9cp9cpkNj9aQOr76ZTLeDIRUA mParentMenuCountTable;
};
struct tyObject_wBitmapcolonObjectType__iQ6sGy0YDhzCvfKqbg9anUw {
  tyObject_wGdiObjectcolonObjectType__8tqtxPp3JdHT18Fg357l6Q Sup;
NI mWidth;
NI mHeight;
NI mDepth;
};
struct tyTuple_yh69bd2OuOhYRzIjAmTKbdA {
tyObject_wMenuBasecolonObjectType__sJxVdMGMr78Iy2Qznhvbjg* Field0;
NI Field1;
};
typedef NU8 tyEnum_wMenuItemKind_xoUEUOF1NJDD46SUwt05kQ;
struct tyObject_wMenuItemcolonObjectType__Fz7rKvpEKh9aDf9chc3kE2qw {
  RootObj Sup;
NI mId;
tyEnum_wMenuItemKind_xoUEUOF1NJDD46SUwt05kQ mKind;
NimStringDesc* mText;
NimStringDesc* mHelp;
tyObject_wBitmapcolonObjectType__iQ6sGy0YDhzCvfKqbg9anUw* mBitmap;
tyObject_wMenucolonObjectType__fCPsDvxqCFVsAnPEAAb0Jw* mSubmenu;
tyObject_wMenucolonObjectType__fCPsDvxqCFVsAnPEAAb0Jw* mParentMenu;
};
struct tySequence_U5QYqmtUND3fb25zvpemlg {
  TGenericSeq Sup;
  tyTuple_Ll5iolPASSzOEheeSNjmiw data[SEQ_DECL_SIZE];
};
struct tySequence_q1CYcV9cohVCitBx05qim8w {
  TGenericSeq Sup;
  tyTuple_pNXh8jOAX7m9ahUugForVlw data[SEQ_DECL_SIZE];
};
struct tySequence_h26ZlPH9aOPYIh58Am8MiyA {
  TGenericSeq Sup;
  tyTuple_eXmvJ9a9c9biYHSPeysfLxHig data[SEQ_DECL_SIZE];
};
struct tySequence_ycFDskWNp4jtk39aIuuDoHA {
  TGenericSeq Sup;
  tyObject_wWindowcolonObjectType__JkYbaVH1UCpF9cuhB5gH9c4w* data[SEQ_DECL_SIZE];
};
struct tySequence_9cOTMEBwo55wzlZjPFOYQHg {
  TGenericSeq Sup;
  tyTuple_5FmmQw5czEqyIS6OX5ADRQ data[SEQ_DECL_SIZE];
};
struct tySequence_T0z34G8Ya9cBkfJWxv7RbzA {
  TGenericSeq Sup;
  tyObject_wToolBarToolcolonObjectType__Mevf0bX1yAVjI8KJD0HIqw* data[SEQ_DECL_SIZE];
};
struct tySequence_0YDEcvfYupp19cAmp9bz9c5EA {
  TGenericSeq Sup;
  tyObject_ACCEL_IwPxdEWRYYSQ39bY1mW9aFeQ data[SEQ_DECL_SIZE];
};
struct tySequence_F7BzjrS6ruvt9cV9ccSEA50A {
  TGenericSeq Sup;
  tyObject_wMenucolonObjectType__fCPsDvxqCFVsAnPEAAb0Jw* data[SEQ_DECL_SIZE];
};
struct tySequence_GEQhRx9bHjh7gn2K1qTnG8A {
  TGenericSeq Sup;
  tyObject_wMenuItemcolonObjectType__Fz7rKvpEKh9aDf9chc3kE2qw* data[SEQ_DECL_SIZE];
};
struct tySequence_ZQphAAUq7LCG9brR1SFDrPg {
  TGenericSeq Sup;
  tyTuple_yh69bd2OuOhYRzIjAmTKbdA data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isEmpty_UshbaKGVTNLaJdFZ6zcwswsets)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets)(NI hcode);
static N_INLINE(NIM_BOOL, mustRehash_flzFqVXoQqeNJHN4qDyOhwsets)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, rightSize_9aQ9aswOyc6W7eMnLOsk3W7Asets)(NI count);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, nextTry_iM1OyigHU0QXXBzsM5QjYAsets)(NI h, NI maxHash);
static N_NIMCALL(void, Marker_tySequence_U5QYqmtUND3fb25zvpemlg)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValid_Cr2i6JuJyL3fC74vZoxgNg)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA s);
static N_INLINE(NI, rawGet_i9cuqXZVrK28o3oFNoUWvOgsets)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA s, NI32 key, NI* hc);
static N_INLINE(NI, hash_a5N2Ic0uYrdiANf4A16L3wtables)(NI32 x);
N_NOINLINE(void, raiseIndexError)(void);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, init_tnXLDnthHCPk9aOqGqGsPcw)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s, NI initialSize);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_mOnmCQUcGXjDELP4riZIpg)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s);
static N_INLINE(NI, rawGetKnownHC_5F3DlfpDlM9cKRsAIGa39bZAsets)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA s, NI32 key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_s259ckzVTX8HW7DzE6y8rOw)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s, tySequence_U5QYqmtUND3fb25zvpemlg** data, NI32 key, NI hc, NI h);
static N_INLINE(NIM_BOOL, exclImpl_gs29aVuzkMeqH9bBcKGBj3tQsets)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s, NI32 key);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValid_HZCTm4DO9aqMj4q6jOwYfxA)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q s);
static N_INLINE(NI, rawGet_4SH8egtmQSwLxrtOXlFagQsets)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q s, tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* key, NI* hc);
static N_INLINE(NI, hash_aWNG17kGOlkdSwuejjVcyQsets)(tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* o);
static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_zQOA2HcogM6mJS9btK9blQ6w)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_q1CYcV9cohVCitBx05qim8w)(void* p, NI op);
static N_INLINE(NI, rawGetKnownHC_uywRz5J9a8U7EdX2uBD1STQsets)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q s, tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_bjchl9a9azjh5QmKmO6rKikQ)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q* s, tySequence_q1CYcV9cohVCitBx05qim8w** data, tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* key, NI hc, NI h);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, init_SqlKePD661SUfX5UlV4sXg)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q* s, NI initialSize);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValid_R64k0VbGpy5rYWPS9bz9aGlA)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA s);
static N_INLINE(NI, rawGet_UmRH9cn2qEuh132VO5uFSSAsets)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key, NI* hc);
static N_INLINE(NI, hash_1xOPFMnr2RA8UYg28Su7rQsets)(tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* o);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_k7eGk0qr8AynxR9cpixtrjQ)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s);
static N_NIMCALL(void, Marker_tySequence_h26ZlPH9aOPYIh58Am8MiyA)(void* p, NI op);
static N_INLINE(NI, rawGetKnownHC_mhuFGqnh4VLGPOpiQfaXzQsets)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_yulUpVn9cD28rypLF9aPaejw)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s, tySequence_h26ZlPH9aOPYIh58Am8MiyA** data, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key, NI hc, NI h);
static N_INLINE(NIM_BOOL, exclImpl_C9bJC0uBcQ69cBLuCK1xBICAsets)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key);
N_LIB_PRIVATE N_NIMCALL(void, init_LBss9bh9b7x9bkrVCgNGHUvJw)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s, NI initialSize);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_Kdjcw8t00DG9cPNKQvs5fnA_;
TNimType NTI_Ll5iolPASSzOEheeSNjmiw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;
TNimType NTI_U5QYqmtUND3fb25zvpemlg_;
TNimType NTI_pNXh8jOAX7m9ahUugForVlw_;
extern TNimType NTI_ThjbtLtYFRDzc9cV2ZB6Npw_;
TNimType NTI_q1CYcV9cohVCitBx05qim8w_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_slAuD5d9bFbK0rXC4DO235Q_;
TNimType NTI_eXmvJ9a9c9biYHSPeysfLxHig_;
TNimType NTI_NHIwwI53SsbxyRoPrbjsfA_;
extern TNimType NTI_ctlP3m52lAF6P9cTNFq9ctAA_;
TNimType NTI_h26ZlPH9aOPYIh58Am8MiyA_;
STRING_LITERAL(TM_0JXiWyhP5OCO8jWMA6sb1w_2, "\012counter < length ", 18);
STRING_LITERAL(TM_0JXiWyhP5OCO8jWMA6sb1w_12, "isValid(s) The set needs to be initialized.", 43);
STRING_LITERAL(TM_0JXiWyhP5OCO8jWMA6sb1w_14, "isPowerOfTwo(initialSize) ", 26);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isEmpty_UshbaKGVTNLaJdFZ6zcwswsets)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isEmpty", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(60, "sets.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(63, "sets.nim");
	nimln_(398, "system.nim");
	nimln_(63, "sets.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustRehash_flzFqVXoQqeNJHN4qDyOhwsets)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T5_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_3;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_4;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_5;
	nimfr_("mustRehash", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(127, "sets.nim");
	{
		if (!!((counter < length))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_2));
	}
	LA3_: ;
	nimln_(128, "sets.nim");
	T5_ = (NIM_BOOL)0;
	TM_0JXiWyhP5OCO8jWMA6sb1w_3 = mulInt(length, ((NI) 2));
	TM_0JXiWyhP5OCO8jWMA6sb1w_4 = mulInt(counter, ((NI) 3));
	T5_ = ((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_3) < (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_4));
	if (T5_) goto LA6_;
	TM_0JXiWyhP5OCO8jWMA6sb1w_5 = subInt(length, counter);
	T5_ = ((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_5) < ((NI) 4));
	LA6_: ;
	result = T5_;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rightSize_9aQ9aswOyc6W7eMnLOsk3W7Asets)(NI count) {
	NI result;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_6;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_7;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_8;
	nimfr_("rightSize", "sets.nim");
	result = (NI)0;
	nimln_(137, "sets.nim");
	TM_0JXiWyhP5OCO8jWMA6sb1w_6 = mulInt(((NI) (count)), ((NI) 3));
	TM_0JXiWyhP5OCO8jWMA6sb1w_7 = divInt((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_6), ((NI) 2));
	TM_0JXiWyhP5OCO8jWMA6sb1w_8 = addInt((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_7), ((NI) 4));
	result = nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_8));
	popFrame();
	return result;
}

static N_INLINE(NI, nextTry_iM1OyigHU0QXXBzsM5QjYAsets)(NI h, NI maxHash) {
	NI result;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_9;
	nimfr_("nextTry", "sets.nim");
	result = (NI)0;
	nimln_(140, "sets.nim");
	TM_0JXiWyhP5OCO8jWMA6sb1w_9 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_9) & maxHash);
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_U5QYqmtUND3fb25zvpemlg)(void* p, NI op) {
	tySequence_U5QYqmtUND3fb25zvpemlg* a;
	NI T1_;
	a = (tySequence_U5QYqmtUND3fb25zvpemlg*)p;
	T1_ = (NI)0;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValid_Cr2i6JuJyL3fC74vZoxgNg)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA s) {
	NIM_BOOL result;
	nimfr_("isValid", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(77, "sets.nim");
	result = !((s.data == 0));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_a5N2Ic0uYrdiANf4A16L3wtables)(NI32 x) {
	NI result;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(129, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_i9cuqXZVrK28o3oFNoUWvOgsets)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA s, NI32 key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_13;
	nimfr_("rawGet", "sets.nim");
{	result = (NI)0;
	nimln_(155, "sets.nim");
	(*hc) = hash_a5N2Ic0uYrdiANf4A16L3wtables(key);
	nimln_(156, "sets.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(157, "sets.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(143, "sets.nim");
	T5_ = (s.data ? (s.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(144, "sets.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(s.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(149, "sets.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T11_ = (s.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T11_ = (s.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(150, "sets.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(151, "sets.nim");
			T15_ = (s.data ? (s.data->Sup.len-1) : -1);
			h = nextTry_iM1OyigHU0QXXBzsM5QjYAsets(h, T15_);
		} LA7: ;
	}
	nimln_(152, "sets.nim");
	TM_0JXiWyhP5OCO8jWMA6sb1w_13 = subInt(((NI) -1), h);
	result = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_13);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_eQU4FROcK3eIBJzGsTOgEA)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA s, NI32 key) {
	NIM_BOOL result;
	NI hc;
	NI index;
	nimfr_("contains", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(204, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValid_Cr2i6JuJyL3fC74vZoxgNg(s);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_12));
	}
	LA4_: ;
	hc = (NI)0;
	nimln_(206, "sets.nim");
	index = rawGet_i9cuqXZVrK28o3oFNoUWvOgsets(s, key, (&hc));
	nimln_(207, "sets.nim");
	result = (((NI) 0) <= index);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, init_tnXLDnthHCPk9aOqGqGsPcw)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s, NI initialSize) {
	nimfr_("init", "sets.nim");
	nimln_(377, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_14));
	}
	LA4_: ;
	nimln_(378, "sets.nim");
	(*s).counter = ((NI) 0);
	nimln_(379, "sets.nim");
	unsureAsgnRef((void**) (&(*s).data), (tySequence_U5QYqmtUND3fb25zvpemlg*) newSeq((&NTI_U5QYqmtUND3fb25zvpemlg_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initSet_Xq0OD4rB318Ssuqh4ZT8Iw)(NI initialSize, tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* Result) {
	nimfr_("initSet", "sets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_Kdjcw8t00DG9cPNKQvs5fnA_));
	nimln_(391, "sets.nim");
	init_tnXLDnthHCPk9aOqGqGsPcw(Result, initialSize);
	popFrame();
}

static N_INLINE(NI, rawGetKnownHC_5F3DlfpDlM9cKRsAIGa39bZAsets)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA s, NI32 key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_16;
	nimfr_("rawGetKnownHC", "sets.nim");
{	result = (NI)0;
	nimln_(143, "sets.nim");
	T1_ = (s.data ? (s.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(144, "sets.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(s.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(149, "sets.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T7_ = (s.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T7_ = (s.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(150, "sets.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(151, "sets.nim");
			T11_ = (s.data ? (s.data->Sup.len-1) : -1);
			h = nextTry_iM1OyigHU0QXXBzsM5QjYAsets(h, T11_);
		} LA3: ;
	}
	nimln_(152, "sets.nim");
	TM_0JXiWyhP5OCO8jWMA6sb1w_16 = subInt(((NI) -1), h);
	result = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_16);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_s259ckzVTX8HW7DzE6y8rOw)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s, tySequence_U5QYqmtUND3fb25zvpemlg** data, NI32 key, NI hc, NI h) {
	nimfr_("rawInsert", "sets.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(161, "sets.nim");
	(*data)->data[h].Field1 = key;
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(162, "sets.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_mOnmCQUcGXjDELP4riZIpg)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s) {
	tySequence_U5QYqmtUND3fb25zvpemlg* n;
	NI T1_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_15;
	tySequence_U5QYqmtUND3fb25zvpemlg* T2_;
	nimfr_("enlarge", "sets.nim");
	n = (tySequence_U5QYqmtUND3fb25zvpemlg*)0;
	nimln_(215, "sets.nim");
	T1_ = ((*s).data ? (*s).data->Sup.len : 0);
	TM_0JXiWyhP5OCO8jWMA6sb1w_15 = mulInt(T1_, ((NI) 2));
	n = (tySequence_U5QYqmtUND3fb25zvpemlg*) newSeq((&NTI_U5QYqmtUND3fb25zvpemlg_), ((NI)chckRange((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_15), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(216, "sets.nim");
	T2_ = (tySequence_U5QYqmtUND3fb25zvpemlg*)0;
	T2_ = (*s).data;
	unsureAsgnRef((void**) (&(*s).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(217, "sets.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI TM_0JXiWyhP5OCO8jWMA6sb1w_18;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(218, "sets.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					NI TM_0JXiWyhP5OCO8jWMA6sb1w_17;
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(n->data[i].Field0);
					if (!T9_) goto LA10_;
					nimln_(219, "sets.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					T12_ = (NI)0;
					T12_ = rawGetKnownHC_5F3DlfpDlM9cKRsAIGa39bZAsets((*s), n->data[i].Field1, n->data[i].Field0);
					TM_0JXiWyhP5OCO8jWMA6sb1w_17 = subInt(((NI) -1), T12_);
					j = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_17);
					nimln_(220, "sets.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_s259ckzVTX8HW7DzE6y8rOw(s, (&(*s).data), n->data[i].Field1, n->data[i].Field0, j);
				}
				LA10_: ;
				nimln_(2035, "system.nim");
				TM_0JXiWyhP5OCO8jWMA6sb1w_18 = addInt(res, ((NI) 1));
				res = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_18);
			} LA6: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, incl_0HUfYVHsUrZTtJpZehnSgw)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s, NI32 key) {
	NI hc;
	NI index;
	nimfr_("incl", "sets.nim");
	nimln_(254, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValid_Cr2i6JuJyL3fC74vZoxgNg((*s));
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_12));
	}
	LA4_: ;
	hc = (NI)0;
	nimln_(224, "sets.nim");
	index = rawGet_i9cuqXZVrK28o3oFNoUWvOgsets((*s), key, (&hc));
	nimln_(255, "sets.nim");
	{
		NI TM_0JXiWyhP5OCO8jWMA6sb1w_19;
		NI TM_0JXiWyhP5OCO8jWMA6sb1w_20;
		nimln_(225, "sets.nim");
		if (!(index < ((NI) 0))) goto LA8_;
		nimln_(226, "sets.nim");
		{
			NI T12_;
			NIM_BOOL T13_;
			T12_ = ((*s).data ? (*s).data->Sup.len : 0);
			T13_ = (NIM_BOOL)0;
			T13_ = mustRehash_flzFqVXoQqeNJHN4qDyOhwsets(T12_, (*s).counter);
			if (!T13_) goto LA14_;
			nimln_(227, "sets.nim");
			enlarge_mOnmCQUcGXjDELP4riZIpg(s);
			nimln_(228, "sets.nim");
			index = rawGetKnownHC_5F3DlfpDlM9cKRsAIGa39bZAsets((*s), key, hc);
		}
		LA14_: ;
		nimln_(229, "sets.nim");
		TM_0JXiWyhP5OCO8jWMA6sb1w_19 = subInt(((NI) -1), index);
		rawInsert_s259ckzVTX8HW7DzE6y8rOw(s, (&(*s).data), key, hc, (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_19));
		nimln_(230, "sets.nim");
		TM_0JXiWyhP5OCO8jWMA6sb1w_20 = addInt((*s).counter, ((NI) 1));
		(*s).counter = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_20);
	}
	LA8_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, exclImpl_gs29aVuzkMeqH9bBcKGBj3tQsets)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s, NI32 key) {
	NIM_BOOL result;
	NI hc;
	NI i;
	NI msk;
	NI T6_;
	nimfr_("exclImpl", "sets.nim");
{	result = (NIM_BOOL)0;
	nimln_(282, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValid_Cr2i6JuJyL3fC74vZoxgNg((*s));
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_12));
	}
	LA4_: ;
	hc = (NI)0;
	nimln_(284, "sets.nim");
	i = rawGet_i9cuqXZVrK28o3oFNoUWvOgsets((*s), key, (&hc));
	nimln_(285, "sets.nim");
	T6_ = ((*s).data ? ((*s).data->Sup.len-1) : -1);
	msk = T6_;
	nimln_(286, "sets.nim");
	result = NIM_TRUE;
	nimln_(288, "sets.nim");
	{
		NI TM_0JXiWyhP5OCO8jWMA6sb1w_21;
		if (!(((NI) 0) <= i)) goto LA9_;
		nimln_(289, "sets.nim");
		result = NIM_FALSE;
		nimln_(290, "sets.nim");
		TM_0JXiWyhP5OCO8jWMA6sb1w_21 = subInt((*s).counter, ((NI) 1));
		(*s).counter = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_21);
		{
			nimln_(291, "sets.nim");
			while (1) {
				NI j;
				NI r;
				NI32 v;
				nimln_(292, "sets.nim");
				j = i;
				nimln_(293, "sets.nim");
				r = j;
				if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
				nimln_(294, "sets.nim");
				(*s).data->data[i].Field0 = ((NI) 0);
				if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
				nimln_(295, "sets.nim");
				v = (NI32)0;
				(*s).data->data[i].Field1 = v;
				{
					nimln_(296, "sets.nim");
					while (1) {
						NI TM_0JXiWyhP5OCO8jWMA6sb1w_22;
						nimln_(297, "sets.nim");
						TM_0JXiWyhP5OCO8jWMA6sb1w_22 = addInt(i, ((NI) 1));
						i = (NI)((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_22) & msk);
						nimln_(298, "sets.nim");
						{
							NIM_BOOL T17_;
							if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
							T17_ = (NIM_BOOL)0;
							T17_ = isEmpty_UshbaKGVTNLaJdFZ6zcwswsets((*s).data->data[i].Field0);
							if (!T17_) goto LA18_;
							nimln_(299, "sets.nim");
							goto BeforeRet_;
						}
						LA18_: ;
						nimln_(300, "sets.nim");
						if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
						r = (NI)((*s).data->data[i].Field0 & msk);
						nimln_(275, "sets.nim");
						{
							NIM_BOOL T22_;
							NIM_BOOL T23_;
							NIM_BOOL T24_;
							NIM_BOOL T27_;
							NIM_BOOL T30_;
							nimln_(296, "sets.nim");
							T22_ = (NIM_BOOL)0;
							T23_ = (NIM_BOOL)0;
							T24_ = (NIM_BOOL)0;
							T24_ = (r <= i);
							if (!(T24_)) goto LA25_;
							T24_ = (j < r);
							LA25_: ;
							T23_ = T24_;
							if (T23_) goto LA26_;
							T27_ = (NIM_BOOL)0;
							T27_ = (j < r);
							if (!(T27_)) goto LA28_;
							T27_ = (i < j);
							LA28_: ;
							T23_ = T27_;
							LA26_: ;
							T22_ = T23_;
							if (T22_) goto LA29_;
							T30_ = (NIM_BOOL)0;
							T30_ = (i < j);
							if (!(T30_)) goto LA31_;
							T30_ = (r <= i);
							LA31_: ;
							T22_ = T30_;
							LA29_: ;
							if (!!(T22_)) goto LA32_;
							nimln_(275, "sets.nim");
							goto LA13;
						}
						LA32_: ;
					}
				} LA13: ;
				if ((NU)(j) >= (NU)((*s).data->Sup.len)) raiseIndexError();
				nimln_(301, "sets.nim");
				if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
				(*s).data->data[j] = (*s).data->data[i];
			}
		}
	}
	LA9_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, excl_0HUfYVHsUrZTtJpZehnSgw_2)(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA* s, NI32 key) {
	NIM_BOOL T1_;
	nimfr_("excl", "sets.nim");
	nimln_(325, "sets.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = exclImpl_gs29aVuzkMeqH9bBcKGBj3tQsets(s, key);
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValid_HZCTm4DO9aqMj4q6jOwYfxA)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q s) {
	NIM_BOOL result;
	nimfr_("isValid", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(77, "sets.nim");
	result = !((s.data == 0));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x) {
	NI result;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(109, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_aWNG17kGOlkdSwuejjVcyQsets)(tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* o) {
	NI result;
	nimfr_("hash", "wTypes.nim");
	result = (NI)0;
	nimln_(505, "wTypes.nim");
	result = hash_M6zZEYz39abIOUmj0QsNREghashes(((NI) (o)));
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_4SH8egtmQSwLxrtOXlFagQsets)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q s, tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_23;
	nimfr_("rawGet", "sets.nim");
{	result = (NI)0;
	nimln_(155, "sets.nim");
	(*hc) = hash_aWNG17kGOlkdSwuejjVcyQsets(key);
	nimln_(156, "sets.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(157, "sets.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(143, "sets.nim");
	T5_ = (s.data ? (s.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(144, "sets.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(s.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(149, "sets.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T11_ = (s.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T11_ = (s.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(150, "sets.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(151, "sets.nim");
			T15_ = (s.data ? (s.data->Sup.len-1) : -1);
			h = nextTry_iM1OyigHU0QXXBzsM5QjYAsets(h, T15_);
		} LA7: ;
	}
	nimln_(152, "sets.nim");
	TM_0JXiWyhP5OCO8jWMA6sb1w_23 = subInt(((NI) -1), h);
	result = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_23);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_q1CYcV9cohVCitBx05qim8w)(void* p, NI op) {
	tySequence_q1CYcV9cohVCitBx05qim8w* a;
	NI T1_;
	a = (tySequence_q1CYcV9cohVCitBx05qim8w*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}

static N_INLINE(NI, rawGetKnownHC_uywRz5J9a8U7EdX2uBD1STQsets)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q s, tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_26;
	nimfr_("rawGetKnownHC", "sets.nim");
{	result = (NI)0;
	nimln_(143, "sets.nim");
	T1_ = (s.data ? (s.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(144, "sets.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(s.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(149, "sets.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T7_ = (s.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T7_ = (s.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(150, "sets.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(151, "sets.nim");
			T11_ = (s.data ? (s.data->Sup.len-1) : -1);
			h = nextTry_iM1OyigHU0QXXBzsM5QjYAsets(h, T11_);
		} LA3: ;
	}
	nimln_(152, "sets.nim");
	TM_0JXiWyhP5OCO8jWMA6sb1w_26 = subInt(((NI) -1), h);
	result = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_26);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_bjchl9a9azjh5QmKmO6rKikQ)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q* s, tySequence_q1CYcV9cohVCitBx05qim8w** data, tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* key, NI hc, NI h) {
	nimfr_("rawInsert", "sets.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(161, "sets.nim");
	asgnRef((void**) (&(*data)->data[h].Field1), key);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(162, "sets.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_zQOA2HcogM6mJS9btK9blQ6w)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q* s) {
	tySequence_q1CYcV9cohVCitBx05qim8w* n;
	NI T1_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_24;
	tySequence_q1CYcV9cohVCitBx05qim8w* T2_;
	nimfr_("enlarge", "sets.nim");
	n = (tySequence_q1CYcV9cohVCitBx05qim8w*)0;
	nimln_(215, "sets.nim");
	T1_ = ((*s).data ? (*s).data->Sup.len : 0);
	TM_0JXiWyhP5OCO8jWMA6sb1w_24 = mulInt(T1_, ((NI) 2));
	n = (tySequence_q1CYcV9cohVCitBx05qim8w*) newSeq((&NTI_q1CYcV9cohVCitBx05qim8w_), ((NI)chckRange((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_24), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(216, "sets.nim");
	T2_ = (tySequence_q1CYcV9cohVCitBx05qim8w*)0;
	T2_ = (*s).data;
	unsureAsgnRef((void**) (&(*s).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(217, "sets.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI TM_0JXiWyhP5OCO8jWMA6sb1w_28;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(218, "sets.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					NI TM_0JXiWyhP5OCO8jWMA6sb1w_27;
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(n->data[i].Field0);
					if (!T9_) goto LA10_;
					nimln_(219, "sets.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					T12_ = (NI)0;
					T12_ = rawGetKnownHC_uywRz5J9a8U7EdX2uBD1STQsets((*s), n->data[i].Field1, n->data[i].Field0);
					TM_0JXiWyhP5OCO8jWMA6sb1w_27 = subInt(((NI) -1), T12_);
					j = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_27);
					nimln_(220, "sets.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_bjchl9a9azjh5QmKmO6rKikQ(s, (&(*s).data), n->data[i].Field1, n->data[i].Field0, j);
				}
				LA10_: ;
				nimln_(2035, "system.nim");
				TM_0JXiWyhP5OCO8jWMA6sb1w_28 = addInt(res, ((NI) 1));
				res = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_28);
			} LA6: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, incl_gmhOQGUZruf1x23vmefDPg)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q* s, tyObject_wResizablecolonObjectType__wctsRw6gBM4o9b7WTG7sM9aA* key) {
	NI hc;
	NI index;
	nimfr_("incl", "sets.nim");
	nimln_(254, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValid_HZCTm4DO9aqMj4q6jOwYfxA((*s));
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_12));
	}
	LA4_: ;
	hc = (NI)0;
	nimln_(224, "sets.nim");
	index = rawGet_4SH8egtmQSwLxrtOXlFagQsets((*s), key, (&hc));
	nimln_(255, "sets.nim");
	{
		NI TM_0JXiWyhP5OCO8jWMA6sb1w_29;
		NI TM_0JXiWyhP5OCO8jWMA6sb1w_30;
		nimln_(225, "sets.nim");
		if (!(index < ((NI) 0))) goto LA8_;
		nimln_(226, "sets.nim");
		{
			NI T12_;
			NIM_BOOL T13_;
			T12_ = ((*s).data ? (*s).data->Sup.len : 0);
			T13_ = (NIM_BOOL)0;
			T13_ = mustRehash_flzFqVXoQqeNJHN4qDyOhwsets(T12_, (*s).counter);
			if (!T13_) goto LA14_;
			nimln_(227, "sets.nim");
			enlarge_zQOA2HcogM6mJS9btK9blQ6w(s);
			nimln_(228, "sets.nim");
			index = rawGetKnownHC_uywRz5J9a8U7EdX2uBD1STQsets((*s), key, hc);
		}
		LA14_: ;
		nimln_(229, "sets.nim");
		TM_0JXiWyhP5OCO8jWMA6sb1w_29 = subInt(((NI) -1), index);
		rawInsert_bjchl9a9azjh5QmKmO6rKikQ(s, (&(*s).data), key, hc, (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_29));
		nimln_(230, "sets.nim");
		TM_0JXiWyhP5OCO8jWMA6sb1w_30 = addInt((*s).counter, ((NI) 1));
		(*s).counter = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_30);
	}
	LA8_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, init_SqlKePD661SUfX5UlV4sXg)(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q* s, NI initialSize) {
	nimfr_("init", "sets.nim");
	nimln_(377, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_14));
	}
	LA4_: ;
	nimln_(378, "sets.nim");
	(*s).counter = ((NI) 0);
	nimln_(379, "sets.nim");
	unsureAsgnRef((void**) (&(*s).data), (tySequence_q1CYcV9cohVCitBx05qim8w*) newSeq((&NTI_q1CYcV9cohVCitBx05qim8w_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initSet_vMMjaMXLup4W6S1NbwxSCQ)(NI initialSize, tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q* Result) {
	nimfr_("initSet", "sets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_slAuD5d9bFbK0rXC4DO235Q_));
	nimln_(391, "sets.nim");
	init_SqlKePD661SUfX5UlV4sXg(Result, initialSize);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValid_R64k0VbGpy5rYWPS9bz9aGlA)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA s) {
	NIM_BOOL result;
	nimfr_("isValid", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(77, "sets.nim");
	result = !((s.data == 0));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_1xOPFMnr2RA8UYg28Su7rQsets)(tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* o) {
	NI result;
	nimfr_("hash", "wTypes.nim");
	result = (NI)0;
	nimln_(505, "wTypes.nim");
	result = hash_M6zZEYz39abIOUmj0QsNREghashes(((NI) (o)));
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_UmRH9cn2qEuh132VO5uFSSAsets)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_32;
	nimfr_("rawGet", "sets.nim");
{	result = (NI)0;
	nimln_(155, "sets.nim");
	(*hc) = hash_1xOPFMnr2RA8UYg28Su7rQsets(key);
	nimln_(156, "sets.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(157, "sets.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(143, "sets.nim");
	T5_ = (s.data ? (s.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(144, "sets.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(s.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(149, "sets.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T11_ = (s.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T11_ = (s.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(150, "sets.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(151, "sets.nim");
			T15_ = (s.data ? (s.data->Sup.len-1) : -1);
			h = nextTry_iM1OyigHU0QXXBzsM5QjYAsets(h, T15_);
		} LA7: ;
	}
	nimln_(152, "sets.nim");
	TM_0JXiWyhP5OCO8jWMA6sb1w_32 = subInt(((NI) -1), h);
	result = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_32);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_h26ZlPH9aOPYIh58Am8MiyA)(void* p, NI op) {
	tySequence_h26ZlPH9aOPYIh58Am8MiyA* a;
	NI T1_;
	a = (tySequence_h26ZlPH9aOPYIh58Am8MiyA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}

static N_INLINE(NI, rawGetKnownHC_mhuFGqnh4VLGPOpiQfaXzQsets)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_36;
	nimfr_("rawGetKnownHC", "sets.nim");
{	result = (NI)0;
	nimln_(143, "sets.nim");
	T1_ = (s.data ? (s.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(144, "sets.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(s.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(149, "sets.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T7_ = (s.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T7_ = (s.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(150, "sets.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(151, "sets.nim");
			T11_ = (s.data ? (s.data->Sup.len-1) : -1);
			h = nextTry_iM1OyigHU0QXXBzsM5QjYAsets(h, T11_);
		} LA3: ;
	}
	nimln_(152, "sets.nim");
	TM_0JXiWyhP5OCO8jWMA6sb1w_36 = subInt(((NI) -1), h);
	result = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_36);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_yulUpVn9cD28rypLF9aPaejw)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s, tySequence_h26ZlPH9aOPYIh58Am8MiyA** data, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key, NI hc, NI h) {
	nimfr_("rawInsert", "sets.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(161, "sets.nim");
	asgnRef((void**) (&(*data)->data[h].Field1), key);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(162, "sets.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_k7eGk0qr8AynxR9cpixtrjQ)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s) {
	tySequence_h26ZlPH9aOPYIh58Am8MiyA* n;
	NI T1_;
	NI TM_0JXiWyhP5OCO8jWMA6sb1w_33;
	tySequence_h26ZlPH9aOPYIh58Am8MiyA* T2_;
	nimfr_("enlarge", "sets.nim");
	n = (tySequence_h26ZlPH9aOPYIh58Am8MiyA*)0;
	nimln_(215, "sets.nim");
	T1_ = ((*s).data ? (*s).data->Sup.len : 0);
	TM_0JXiWyhP5OCO8jWMA6sb1w_33 = mulInt(T1_, ((NI) 2));
	n = (tySequence_h26ZlPH9aOPYIh58Am8MiyA*) newSeq((&NTI_h26ZlPH9aOPYIh58Am8MiyA_), ((NI)chckRange((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_33), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(216, "sets.nim");
	T2_ = (tySequence_h26ZlPH9aOPYIh58Am8MiyA*)0;
	T2_ = (*s).data;
	unsureAsgnRef((void**) (&(*s).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(217, "sets.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI TM_0JXiWyhP5OCO8jWMA6sb1w_38;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(218, "sets.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					NI TM_0JXiWyhP5OCO8jWMA6sb1w_37;
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(n->data[i].Field0);
					if (!T9_) goto LA10_;
					nimln_(219, "sets.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					T12_ = (NI)0;
					T12_ = rawGetKnownHC_mhuFGqnh4VLGPOpiQfaXzQsets((*s), n->data[i].Field1, n->data[i].Field0);
					TM_0JXiWyhP5OCO8jWMA6sb1w_37 = subInt(((NI) -1), T12_);
					j = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_37);
					nimln_(220, "sets.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_yulUpVn9cD28rypLF9aPaejw(s, (&(*s).data), n->data[i].Field1, n->data[i].Field0, j);
				}
				LA10_: ;
				nimln_(2035, "system.nim");
				TM_0JXiWyhP5OCO8jWMA6sb1w_38 = addInt(res, ((NI) 1));
				res = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_38);
			} LA6: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, incl_IDKcyu8DVejf7xQ79ci8bOg)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key) {
	NI hc;
	NI index;
	nimfr_("incl", "sets.nim");
	nimln_(254, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValid_R64k0VbGpy5rYWPS9bz9aGlA((*s));
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_12));
	}
	LA4_: ;
	hc = (NI)0;
	nimln_(224, "sets.nim");
	index = rawGet_UmRH9cn2qEuh132VO5uFSSAsets((*s), key, (&hc));
	nimln_(255, "sets.nim");
	{
		NI TM_0JXiWyhP5OCO8jWMA6sb1w_39;
		NI TM_0JXiWyhP5OCO8jWMA6sb1w_40;
		nimln_(225, "sets.nim");
		if (!(index < ((NI) 0))) goto LA8_;
		nimln_(226, "sets.nim");
		{
			NI T12_;
			NIM_BOOL T13_;
			T12_ = ((*s).data ? (*s).data->Sup.len : 0);
			T13_ = (NIM_BOOL)0;
			T13_ = mustRehash_flzFqVXoQqeNJHN4qDyOhwsets(T12_, (*s).counter);
			if (!T13_) goto LA14_;
			nimln_(227, "sets.nim");
			enlarge_k7eGk0qr8AynxR9cpixtrjQ(s);
			nimln_(228, "sets.nim");
			index = rawGetKnownHC_mhuFGqnh4VLGPOpiQfaXzQsets((*s), key, hc);
		}
		LA14_: ;
		nimln_(229, "sets.nim");
		TM_0JXiWyhP5OCO8jWMA6sb1w_39 = subInt(((NI) -1), index);
		rawInsert_yulUpVn9cD28rypLF9aPaejw(s, (&(*s).data), key, hc, (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_39));
		nimln_(230, "sets.nim");
		TM_0JXiWyhP5OCO8jWMA6sb1w_40 = addInt((*s).counter, ((NI) 1));
		(*s).counter = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_40);
	}
	LA8_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_fRiaYjK2bcwQtWlpTiSNDA)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key) {
	NIM_BOOL result;
	NI hc;
	NI index;
	nimfr_("contains", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(204, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValid_R64k0VbGpy5rYWPS9bz9aGlA(s);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_12));
	}
	LA4_: ;
	hc = (NI)0;
	nimln_(206, "sets.nim");
	index = rawGet_UmRH9cn2qEuh132VO5uFSSAsets(s, key, (&hc));
	nimln_(207, "sets.nim");
	result = (((NI) 0) <= index);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, exclImpl_C9bJC0uBcQ69cBLuCK1xBICAsets)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key) {
	NIM_BOOL result;
	NI hc;
	NI i;
	NI msk;
	NI T6_;
	nimfr_("exclImpl", "sets.nim");
{	result = (NIM_BOOL)0;
	nimln_(282, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValid_R64k0VbGpy5rYWPS9bz9aGlA((*s));
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_12));
	}
	LA4_: ;
	hc = (NI)0;
	nimln_(284, "sets.nim");
	i = rawGet_UmRH9cn2qEuh132VO5uFSSAsets((*s), key, (&hc));
	nimln_(285, "sets.nim");
	T6_ = ((*s).data ? ((*s).data->Sup.len-1) : -1);
	msk = T6_;
	nimln_(286, "sets.nim");
	result = NIM_TRUE;
	nimln_(288, "sets.nim");
	{
		NI TM_0JXiWyhP5OCO8jWMA6sb1w_41;
		if (!(((NI) 0) <= i)) goto LA9_;
		nimln_(289, "sets.nim");
		result = NIM_FALSE;
		nimln_(290, "sets.nim");
		TM_0JXiWyhP5OCO8jWMA6sb1w_41 = subInt((*s).counter, ((NI) 1));
		(*s).counter = (NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_41);
		{
			nimln_(291, "sets.nim");
			while (1) {
				NI j;
				NI r;
				tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* v;
				nimln_(292, "sets.nim");
				j = i;
				nimln_(293, "sets.nim");
				r = j;
				if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
				nimln_(294, "sets.nim");
				(*s).data->data[i].Field0 = ((NI) 0);
				if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
				nimln_(295, "sets.nim");
				v = (tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg*)0;
				asgnRef((void**) (&(*s).data->data[i].Field1), v);
				{
					nimln_(296, "sets.nim");
					while (1) {
						NI TM_0JXiWyhP5OCO8jWMA6sb1w_42;
						nimln_(297, "sets.nim");
						TM_0JXiWyhP5OCO8jWMA6sb1w_42 = addInt(i, ((NI) 1));
						i = (NI)((NI)(TM_0JXiWyhP5OCO8jWMA6sb1w_42) & msk);
						nimln_(298, "sets.nim");
						{
							NIM_BOOL T17_;
							if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
							T17_ = (NIM_BOOL)0;
							T17_ = isEmpty_UshbaKGVTNLaJdFZ6zcwswsets((*s).data->data[i].Field0);
							if (!T17_) goto LA18_;
							nimln_(299, "sets.nim");
							goto BeforeRet_;
						}
						LA18_: ;
						nimln_(300, "sets.nim");
						if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
						r = (NI)((*s).data->data[i].Field0 & msk);
						nimln_(275, "sets.nim");
						{
							NIM_BOOL T22_;
							NIM_BOOL T23_;
							NIM_BOOL T24_;
							NIM_BOOL T27_;
							NIM_BOOL T30_;
							nimln_(296, "sets.nim");
							T22_ = (NIM_BOOL)0;
							T23_ = (NIM_BOOL)0;
							T24_ = (NIM_BOOL)0;
							T24_ = (r <= i);
							if (!(T24_)) goto LA25_;
							T24_ = (j < r);
							LA25_: ;
							T23_ = T24_;
							if (T23_) goto LA26_;
							T27_ = (NIM_BOOL)0;
							T27_ = (j < r);
							if (!(T27_)) goto LA28_;
							T27_ = (i < j);
							LA28_: ;
							T23_ = T27_;
							LA26_: ;
							T22_ = T23_;
							if (T22_) goto LA29_;
							T30_ = (NIM_BOOL)0;
							T30_ = (i < j);
							if (!(T30_)) goto LA31_;
							T30_ = (r <= i);
							LA31_: ;
							T22_ = T30_;
							LA29_: ;
							if (!!(T22_)) goto LA32_;
							nimln_(275, "sets.nim");
							goto LA13;
						}
						LA32_: ;
					}
				} LA13: ;
				if ((NU)(j) >= (NU)((*s).data->Sup.len)) raiseIndexError();
				nimln_(301, "sets.nim");
				if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
				(*s).data->data[j].Field0 = (*s).data->data[i].Field0;
				asgnRef((void**) (&(*s).data->data[j].Field1), (*s).data->data[i].Field1);
			}
		}
	}
	LA9_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, excl_IDKcyu8DVejf7xQ79ci8bOg_2)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s, tyObject_wFramecolonObjectType__x2B2BzMwueDS2nSIbTjBYg* key) {
	NIM_BOOL T1_;
	nimfr_("excl", "sets.nim");
	nimln_(325, "sets.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = exclImpl_C9bJC0uBcQ69cBLuCK1xBICAsets(s, key);
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, len_Te5PpWmX54lxGRiZBWa5qw)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA s) {
	NI result;
	nimfr_("len", "sets.nim");
	result = (NI)0;
	nimln_(91, "sets.nim");
	result = s.counter;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, init_LBss9bh9b7x9bkrVCgNGHUvJw)(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* s, NI initialSize) {
	nimfr_("init", "sets.nim");
	nimln_(377, "sets.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_0JXiWyhP5OCO8jWMA6sb1w_14));
	}
	LA4_: ;
	nimln_(378, "sets.nim");
	(*s).counter = ((NI) 0);
	nimln_(379, "sets.nim");
	unsureAsgnRef((void**) (&(*s).data), (tySequence_h26ZlPH9aOPYIh58Am8MiyA*) newSeq((&NTI_h26ZlPH9aOPYIh58Am8MiyA_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initSet_ZGoo3b89bcmW1vKEzLm9bJ9aQ)(NI initialSize, tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA* Result) {
	nimfr_("initSet", "sets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_NHIwwI53SsbxyRoPrbjsfA_));
	nimln_(391, "sets.nim");
	init_LBss9bh9b7x9bkrVCgNGHUvJw(Result, initialSize);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void) {
	nimfr_("sets", "sets.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void) {
static TNimNode* TM_0JXiWyhP5OCO8jWMA6sb1w_10[2];
static TNimNode* TM_0JXiWyhP5OCO8jWMA6sb1w_11[2];
static TNimNode* TM_0JXiWyhP5OCO8jWMA6sb1w_25[2];
static TNimNode* TM_0JXiWyhP5OCO8jWMA6sb1w_31[2];
static TNimNode* TM_0JXiWyhP5OCO8jWMA6sb1w_34[2];
static TNimNode* TM_0JXiWyhP5OCO8jWMA6sb1w_35[2];
static TNimNode TM_0JXiWyhP5OCO8jWMA6sb1w_0[18];
NTI_Kdjcw8t00DG9cPNKQvs5fnA_.size = sizeof(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA);
NTI_Kdjcw8t00DG9cPNKQvs5fnA_.kind = 18;
NTI_Kdjcw8t00DG9cPNKQvs5fnA_.base = 0;
NTI_Kdjcw8t00DG9cPNKQvs5fnA_.flags = 2;
TM_0JXiWyhP5OCO8jWMA6sb1w_10[0] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[1];
NTI_Ll5iolPASSzOEheeSNjmiw_.size = sizeof(tyTuple_Ll5iolPASSzOEheeSNjmiw);
NTI_Ll5iolPASSzOEheeSNjmiw_.kind = 18;
NTI_Ll5iolPASSzOEheeSNjmiw_.base = 0;
NTI_Ll5iolPASSzOEheeSNjmiw_.flags = 3;
TM_0JXiWyhP5OCO8jWMA6sb1w_11[0] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[3];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[3].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[3].offset = offsetof(tyTuple_Ll5iolPASSzOEheeSNjmiw, Field0);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[3].name = "Field0";
TM_0JXiWyhP5OCO8jWMA6sb1w_11[1] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[4];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[4].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[4].offset = offsetof(tyTuple_Ll5iolPASSzOEheeSNjmiw, Field1);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[4].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[4].name = "Field1";
TM_0JXiWyhP5OCO8jWMA6sb1w_0[2].len = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[2].kind = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[2].sons = &TM_0JXiWyhP5OCO8jWMA6sb1w_11[0];
NTI_Ll5iolPASSzOEheeSNjmiw_.node = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[2];
NTI_U5QYqmtUND3fb25zvpemlg_.size = sizeof(tySequence_U5QYqmtUND3fb25zvpemlg*);
NTI_U5QYqmtUND3fb25zvpemlg_.kind = 24;
NTI_U5QYqmtUND3fb25zvpemlg_.base = (&NTI_Ll5iolPASSzOEheeSNjmiw_);
NTI_U5QYqmtUND3fb25zvpemlg_.flags = 2;
NTI_U5QYqmtUND3fb25zvpemlg_.marker = Marker_tySequence_U5QYqmtUND3fb25zvpemlg;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[1].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[1].offset = offsetof(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA, data);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[1].typ = (&NTI_U5QYqmtUND3fb25zvpemlg_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[1].name = "data";
TM_0JXiWyhP5OCO8jWMA6sb1w_10[1] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[5];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[5].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[5].offset = offsetof(tyObject_HashSet_Kdjcw8t00DG9cPNKQvs5fnA, counter);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[5].name = "counter";
TM_0JXiWyhP5OCO8jWMA6sb1w_0[0].len = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[0].kind = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[0].sons = &TM_0JXiWyhP5OCO8jWMA6sb1w_10[0];
NTI_Kdjcw8t00DG9cPNKQvs5fnA_.node = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[0];
NTI_pNXh8jOAX7m9ahUugForVlw_.size = sizeof(tyTuple_pNXh8jOAX7m9ahUugForVlw);
NTI_pNXh8jOAX7m9ahUugForVlw_.kind = 18;
NTI_pNXh8jOAX7m9ahUugForVlw_.base = 0;
TM_0JXiWyhP5OCO8jWMA6sb1w_25[0] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[7];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[7].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[7].offset = offsetof(tyTuple_pNXh8jOAX7m9ahUugForVlw, Field0);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[7].name = "Field0";
TM_0JXiWyhP5OCO8jWMA6sb1w_25[1] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[8];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[8].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[8].offset = offsetof(tyTuple_pNXh8jOAX7m9ahUugForVlw, Field1);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[8].typ = (&NTI_ThjbtLtYFRDzc9cV2ZB6Npw_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[8].name = "Field1";
TM_0JXiWyhP5OCO8jWMA6sb1w_0[6].len = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[6].kind = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[6].sons = &TM_0JXiWyhP5OCO8jWMA6sb1w_25[0];
NTI_pNXh8jOAX7m9ahUugForVlw_.node = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[6];
NTI_q1CYcV9cohVCitBx05qim8w_.size = sizeof(tySequence_q1CYcV9cohVCitBx05qim8w*);
NTI_q1CYcV9cohVCitBx05qim8w_.kind = 24;
NTI_q1CYcV9cohVCitBx05qim8w_.base = (&NTI_pNXh8jOAX7m9ahUugForVlw_);
NTI_q1CYcV9cohVCitBx05qim8w_.marker = Marker_tySequence_q1CYcV9cohVCitBx05qim8w;
NTI_slAuD5d9bFbK0rXC4DO235Q_.size = sizeof(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q);
NTI_slAuD5d9bFbK0rXC4DO235Q_.kind = 18;
NTI_slAuD5d9bFbK0rXC4DO235Q_.base = 0;
TM_0JXiWyhP5OCO8jWMA6sb1w_31[0] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[10];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[10].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[10].offset = offsetof(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q, data);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[10].typ = (&NTI_q1CYcV9cohVCitBx05qim8w_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[10].name = "data";
TM_0JXiWyhP5OCO8jWMA6sb1w_31[1] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[11];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[11].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[11].offset = offsetof(tyObject_HashSet_slAuD5d9bFbK0rXC4DO235Q, counter);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[11].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[11].name = "counter";
TM_0JXiWyhP5OCO8jWMA6sb1w_0[9].len = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[9].kind = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[9].sons = &TM_0JXiWyhP5OCO8jWMA6sb1w_31[0];
NTI_slAuD5d9bFbK0rXC4DO235Q_.node = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[9];
NTI_eXmvJ9a9c9biYHSPeysfLxHig_.size = sizeof(tyTuple_eXmvJ9a9c9biYHSPeysfLxHig);
NTI_eXmvJ9a9c9biYHSPeysfLxHig_.kind = 18;
NTI_eXmvJ9a9c9biYHSPeysfLxHig_.base = 0;
TM_0JXiWyhP5OCO8jWMA6sb1w_34[0] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[13];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[13].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[13].offset = offsetof(tyTuple_eXmvJ9a9c9biYHSPeysfLxHig, Field0);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[13].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[13].name = "Field0";
TM_0JXiWyhP5OCO8jWMA6sb1w_34[1] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[14];
NTI_NHIwwI53SsbxyRoPrbjsfA_.size = sizeof(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA);
NTI_NHIwwI53SsbxyRoPrbjsfA_.kind = 18;
NTI_NHIwwI53SsbxyRoPrbjsfA_.base = 0;
TM_0JXiWyhP5OCO8jWMA6sb1w_35[0] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[16];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[16].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[16].offset = offsetof(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA, data);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[16].typ = (&NTI_h26ZlPH9aOPYIh58Am8MiyA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[16].name = "data";
TM_0JXiWyhP5OCO8jWMA6sb1w_35[1] = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[17];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[17].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[17].offset = offsetof(tyObject_HashSet_NHIwwI53SsbxyRoPrbjsfA, counter);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[17].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[17].name = "counter";
TM_0JXiWyhP5OCO8jWMA6sb1w_0[15].len = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[15].kind = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[15].sons = &TM_0JXiWyhP5OCO8jWMA6sb1w_35[0];
NTI_NHIwwI53SsbxyRoPrbjsfA_.node = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[15];
TM_0JXiWyhP5OCO8jWMA6sb1w_0[14].kind = 1;
TM_0JXiWyhP5OCO8jWMA6sb1w_0[14].offset = offsetof(tyTuple_eXmvJ9a9c9biYHSPeysfLxHig, Field1);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[14].typ = (&NTI_ctlP3m52lAF6P9cTNFq9ctAA_);
TM_0JXiWyhP5OCO8jWMA6sb1w_0[14].name = "Field1";
TM_0JXiWyhP5OCO8jWMA6sb1w_0[12].len = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[12].kind = 2; TM_0JXiWyhP5OCO8jWMA6sb1w_0[12].sons = &TM_0JXiWyhP5OCO8jWMA6sb1w_34[0];
NTI_eXmvJ9a9c9biYHSPeysfLxHig_.node = &TM_0JXiWyhP5OCO8jWMA6sb1w_0[12];
NTI_h26ZlPH9aOPYIh58Am8MiyA_.size = sizeof(tySequence_h26ZlPH9aOPYIh58Am8MiyA*);
NTI_h26ZlPH9aOPYIh58Am8MiyA_.kind = 24;
NTI_h26ZlPH9aOPYIh58Am8MiyA_.base = (&NTI_eXmvJ9a9c9biYHSPeysfLxHig_);
NTI_h26ZlPH9aOPYIh58Am8MiyA_.marker = Marker_tySequence_h26ZlPH9aOPYIh58Am8MiyA;
}

