/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   F:\nim\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IF:\nim\lib -o O:\nim\wnim\release\examples\nimcache\winim_winstr.o O:\nim\wnim\release\examples\nimcache\winim_winstr.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_pmstringcolonObjectType__zTUzbgPhv6VRKAr4vLcCJw tyObject_pmstringcolonObjectType__zTUzbgPhv6VRKAr4vLcCJw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA tyObject_IndexError_b0IIwghFQBADkB2c86kXQA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef N_STDCALL_PTR(NI32, tyProc_rDy4nTLLLNn01x5FehDIKg) (NI32 CodePage, NI32 dwFlags, NU16* lpWideCharStr, NI32 cchWideChar, NCSTRING lpMultiByteStr, NI32 cbMultiByte, NCSTRING lpDefaultChar, NI32* lpUsedDefaultChar);
struct tyObject_pmstringcolonObjectType__zTUzbgPhv6VRKAr4vLcCJw {
NI length;
NI capacity;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A {
NU32 size;
NU16 data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU16 tyArray_9a9aAlfXLJPjHXnuFdEbFDFg[32];
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA {
  Exception Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(void*, stringBuffer_zjiLV19ao4Nfs7MiRLpp9b9bg)(NI L, NIM_BOOL alloc);
N_LIB_PRIVATE N_NOCONV(void*, alloc0_sVm4rDImKK2ZDdylByayiA)(NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_CHAR*, amp__UF719b2d9bwKZx7XI3tQrEywwNim)(NimStringDesc* s);
static N_INLINE(NU16*, amp__Dkk3SjGl9ay2BZoX9aVCCBOQwinstr)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* s);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void*, wstringBuffer_zjiLV19ao4Nfs7MiRLpp9b9bg_2)(NI L, NIM_BOOL alloc);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_NIMCALL(void, Marker_tyRef_K9aqAvBsg5rtPpgIZn4jwsQ)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, lengtheq__pA9cXbQLyLAp3THEVThVOYgwinstr)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* x, NI L);
static N_INLINE(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*, plusdollar__ZIeOLbV8A7WW4rfGi2H9blQwNim)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void*, UTF8minusgtwstring__VC71MpyOPTe9cqdRNZwcehQ)(NIM_CHAR* source, NI L, NIM_BOOL alloc);
static N_INLINE(NI, length_oofNsbJA2r3sgNQGzNGrggwinstr)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* x);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, fillArray_t4Kvt6m9cQmp9bvzp9c9alnxZA)(NU16* a, tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* s, NIM_BOOL inclNull);
static N_INLINE(NI, len_oofNsbJA2r3sgNQGzNGrggwNim)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* x);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
extern tyProc_rDy4nTLLLNn01x5FehDIKg Dl_294253_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_C9b8rfrA3THHK7wuwo5q9c0A_;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_;
extern TNimType NTI_Ho4W3BYv4hTk8axhGpqWCQ_;
TNimType NTI_K9aqAvBsg5rtPpgIZn4jwsQ_;
extern TNimType NTI_z58cIdR0vOibqJ0QwYvB3Q_;
extern TNimType NTI_b0IIwghFQBADkB2c86kXQA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_zjeWotTwb2UTl5yWEPxJRw_4, "cast[uint](addr(dummy.data)) == 4 ", 34);
STRING_LITERAL(TM_zjeWotTwb2UTl5yWEPxJRw_30, "string length too long", 22);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void*, stringBuffer_zjiLV19ao4Nfs7MiRLpp9b9bg)(NI L, NIM_BOOL alloc) {
	void* result;
	nimfr_("stringBuffer", "winstr.nim");
	result = (void*)0;
	nimln_(308, "winstr.nim");
	{
		NI TM_zjeWotTwb2UTl5yWEPxJRw_2;
		NI TM_zjeWotTwb2UTl5yWEPxJRw_3;
		if (!alloc) goto LA3_;
		nimln_(309, "winstr.nim");
		TM_zjeWotTwb2UTl5yWEPxJRw_2 = addInt(((NI) (L)), ((NI) 16));
		TM_zjeWotTwb2UTl5yWEPxJRw_3 = addInt((NI)(TM_zjeWotTwb2UTl5yWEPxJRw_2), ((NI) 2));
		result = alloc0_sVm4rDImKK2ZDdylByayiA(((NI)chckRange((NI)(TM_zjeWotTwb2UTl5yWEPxJRw_3), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(310, "winstr.nim");
		(*((tyObject_pmstringcolonObjectType__zTUzbgPhv6VRKAr4vLcCJw*) (result))).length = ((NI) (L));
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringDesc* T6_;
		nimln_(312, "winstr.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = mnewString(L);
		result = ((void*) (T6_));
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_CHAR*, amp__UF719b2d9bwKZx7XI3tQrEywwNim)(NimStringDesc* s) {
	NIM_CHAR* result;
	nimfr_("&", "winstr.nim");
	result = (NIM_CHAR*)0;
	nimln_(281, "winstr.nim");
	{
		if (!(s == 0)) goto LA3_;
		nimln_(282, "winstr.nim");
		result = NIM_NIL;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(284, "winstr.nim");
		result = ((NIM_CHAR*) (s->data));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void*, UNICODEminusgtstring__Rf8on9bMvXfyW9aFPy44fmVw)(NU16* source, NI L, NIM_BOOL alloc) {
	void* result;
	NI32 mLen;
	NIM_CHAR* T5_;
	NI32 T6_;
	nimfr_("UNICODE->string", "winstr.nim");
{	result = (void*)0;
	nimln_(388, "winstr.nim");
	{
		if (!(source == 0)) goto LA3_;
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(390, "winstr.nim");
	mLen = Dl_294253_(((NI32) 65001), ((NI32) 0), source, ((NI32)chckRange(L, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), NIM_NIL, ((NI32) 0), NIM_NIL, NIM_NIL);
	nimln_(391, "winstr.nim");
	result = stringBuffer_zjiLV19ao4Nfs7MiRLpp9b9bg(((NI)chckRange(mLen, ((NI) 0), ((NI) IL64(9223372036854775807)))), alloc);
	nimln_(392, "winstr.nim");
	T5_ = (NIM_CHAR*)0;
	T5_ = amp__UF719b2d9bwKZx7XI3tQrEywwNim(((NimStringDesc*) (result)));
	T6_ = (NI32)0;
	T6_ = Dl_294253_(((NI32) 65001), ((NI32) 0), source, ((NI32)chckRange(L, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NCSTRING) (T5_)), mLen, NIM_NIL, NIM_NIL);
	T6_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU16*, winstringConverterPtrArrayToLPWSTR_ICKAHg9cNJ9bcjUOn8nnlVJA)(NU16* x) {
	NU16* result;
	nimfr_("winstringConverterPtrArrayToLPWSTR", "winstr.nim");
	result = (NU16*)0;
	nimln_(1093, "winstr.nim");
	result = ((NU16*) (x));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU16*, winstringConverterPtrArrayToLPWSTR_Q4wp2X5a38KGkN9aKzMJaFA)(NU16* x) {
	NU16* result;
	nimfr_("winstringConverterPtrArrayToLPWSTR", "winstr.nim");
	result = (NU16*)0;
	nimln_(1093, "winstr.nim");
	result = ((NU16*) (x));
	popFrame();
	return result;
}

static N_INLINE(NU16*, amp__Dkk3SjGl9ay2BZoX9aVCCBOQwinstr)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* s) {
	NU16* result;
	tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* dummy;
	NI T5_;
	nimfr_("&", "winstr.nim");
	result = (NU16*)0;
	dummy = (tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*)0;
	nimln_(297, "winstr.nim");
	{
		if (!!((((NU) (ptrdiff_t) ((*dummy).data)) == ((NI) 4)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_zjeWotTwb2UTl5yWEPxJRw_4));
	}
	LA3_: ;
	nimln_(299, "winstr.nim");
	T5_ = (NI)0;
	{
		if (!(s == 0)) goto LA8_;
		T5_ = ((NI) 0);
	}
	goto LA6_;
	LA8_: ;
	{
		T5_ = ((NI) 4);
	}
	LA6_: ;
	result = ((NU16*) ((NU)((NU64)(((NU) (s))) + (NU64)(T5_))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU16*, winstringConverterWStringToLPWSTR_ZcXSVuTPkkY9c8ayUdeT1SQ)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* x) {
	NU16* result;
	NU16* T1_;
	nimfr_("winstringConverterWStringToLPWSTR", "winstr.nim");
	result = (NU16*)0;
	nimln_(1074, "winstr.nim");
	T1_ = (NU16*)0;
	T1_ = amp__Dkk3SjGl9ay2BZoX9aVCCBOQwinstr(x);
	result = ((NU16*) (T1_));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_K9aqAvBsg5rtPpgIZn4jwsQ)(void* p, NI op) {
	tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* a;
	NI T1_;
	a = (tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*)p;
	T1_ = (NI)0;
}

static N_INLINE(void, lengtheq__pA9cXbQLyLAp3THEVThVOYgwinstr)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* x, NI L) {
	nimfr_("length=", "winstr.nim");
	nimln_(275, "winstr.nim");
	(*x).size = (NU32)((NU64)(((NU32) (L))) << (NU64)(((NI) 1)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void*, wstringBuffer_zjiLV19ao4Nfs7MiRLpp9b9bg_2)(NI L, NIM_BOOL alloc) {
	void* result;
	NI size;
	NI TM_zjeWotTwb2UTl5yWEPxJRw_5;
	NI TM_zjeWotTwb2UTl5yWEPxJRw_6;
	NI TM_zjeWotTwb2UTl5yWEPxJRw_7;
	nimfr_("wstringBuffer", "winstr.nim");
	result = (void*)0;
	nimln_(316, "winstr.nim");
	TM_zjeWotTwb2UTl5yWEPxJRw_5 = mulInt(((NI) (L)), ((NI) 2));
	TM_zjeWotTwb2UTl5yWEPxJRw_6 = addInt((NI)(TM_zjeWotTwb2UTl5yWEPxJRw_5), ((NI) 4));
	TM_zjeWotTwb2UTl5yWEPxJRw_7 = addInt((NI)(TM_zjeWotTwb2UTl5yWEPxJRw_6), ((NI) 4));
	size = (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_7);
	nimln_(317, "winstr.nim");
	{
		if (!alloc) goto LA3_;
		nimln_(318, "winstr.nim");
		result = alloc0_sVm4rDImKK2ZDdylByayiA(((NI)chckRange(size, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* ws;
		ws = (tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*)0;
		nimln_(321, "winstr.nim");
		ws = (tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) newObj((&NTI_K9aqAvBsg5rtPpgIZn4jwsQ_), ((NI)chckRange(size, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(322, "winstr.nim");
		result = ((void*) (ws));
	}
	LA1_: ;
	nimln_(324, "winstr.nim");
	lengtheq__pA9cXbQLyLAp3THEVThVOYgwinstr(((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (result)), L);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void*, UTF8minusgtwstring__VC71MpyOPTe9cqdRNZwcehQ)(NIM_CHAR* source, NI L, NIM_BOOL alloc) {
	void* result;
	NI TM_zjeWotTwb2UTl5yWEPxJRw_9;
	NI32 d;
	nimfr_("UTF8->wstring", "winstr.nim");
{	result = (void*)0;
	nimln_(330, "winstr.nim");
	{
		if (!(source == 0)) goto LA3_;
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(332, "winstr.nim");
	TM_zjeWotTwb2UTl5yWEPxJRw_9 = mulInt(((NI) (L)), ((NI) 2));
	result = wstringBuffer_zjiLV19ao4Nfs7MiRLpp9b9bg_2(((NI)chckRange((NI)(TM_zjeWotTwb2UTl5yWEPxJRw_9), ((NI) 0), ((NI) IL64(9223372036854775807)))), alloc);
	nimln_(334, "winstr.nim");
	d = ((NI32) 0);
	{
		NU16 u;
		NCSTRING colontmp_;
		NI colontmp__2;
		u = (NU16)0;
		colontmp_ = (NCSTRING)0;
		colontmp__2 = (NI)0;
		nimln_(335, "winstr.nim");
		colontmp_ = ((NCSTRING) (source));
		colontmp__2 = ((NI) (L));
		{
			NI ch;
			NI i;
			NI result_2;
			ch = (NI)0;
			nimln_(206, "winstr.nim");
			i = ((NI) 0);
			result_2 = (NI)0;
			{
				nimln_(208, "winstr.nim");
				while (1) {
					if (!(i < colontmp__2)) goto LA8;
					nimln_(209, "winstr.nim");
					{
						NI TM_zjeWotTwb2UTl5yWEPxJRw_10;
						nimln_(183, "winstr.nim");
						if (!((NU64)(((NU8)(colontmp_[i]))) <= (NU64)(((NI) 127)))) goto LA11_;
						nimln_(184, "winstr.nim");
						result_2 = ((NU8)(colontmp_[i]));
						nimln_(209, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_10 = addInt(i, ((NI) 1));
						i = (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_10);
					}
					goto LA9_;
					LA11_: ;
					{
						NI TM_zjeWotTwb2UTl5yWEPxJRw_11;
						NI TM_zjeWotTwb2UTl5yWEPxJRw_12;
						nimln_(186, "winstr.nim");
						if (!((NI)((NU64)(((NU8)(colontmp_[i]))) >> (NU64)(((NI) 5))) == ((NI) 6))) goto LA14_;
						nimln_(187, "winstr.nim");
						nimln_(209, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_11 = addInt(i, ((NI) 1));
						result_2 = (NI)((NI)((NU64)((NI)(((NU8)(colontmp_[i])) & ((NI) 31))) << (NU64)(((NI) 6))) | (NI)(((NU8)(colontmp_[(NI)(TM_zjeWotTwb2UTl5yWEPxJRw_11)])) & ((NI) 63)));
						TM_zjeWotTwb2UTl5yWEPxJRw_12 = addInt(i, ((NI) 2));
						i = (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_12);
					}
					goto LA9_;
					LA14_: ;
					{
						NI TM_zjeWotTwb2UTl5yWEPxJRw_13;
						NI TM_zjeWotTwb2UTl5yWEPxJRw_14;
						NI TM_zjeWotTwb2UTl5yWEPxJRw_15;
						nimln_(189, "winstr.nim");
						if (!((NI)((NU64)(((NU8)(colontmp_[i]))) >> (NU64)(((NI) 4))) == ((NI) 14))) goto LA17_;
						nimln_(190, "winstr.nim");
						nimln_(191, "winstr.nim");
						nimln_(209, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_13 = addInt(i, ((NI) 1));
						nimln_(192, "winstr.nim");
						nimln_(209, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_14 = addInt(i, ((NI) 2));
						result_2 = (NI)((NI)((NI)((NU64)((NI)(((NU8)(colontmp_[i])) & ((NI) 15))) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)(((NU8)(colontmp_[(NI)(TM_zjeWotTwb2UTl5yWEPxJRw_13)])) & ((NI) 63))) << (NU64)(((NI) 6)))) | (NI)(((NU8)(colontmp_[(NI)(TM_zjeWotTwb2UTl5yWEPxJRw_14)])) & ((NI) 63)));
						TM_zjeWotTwb2UTl5yWEPxJRw_15 = addInt(i, ((NI) 3));
						i = (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_15);
					}
					goto LA9_;
					LA17_: ;
					{
						NI TM_zjeWotTwb2UTl5yWEPxJRw_16;
						NI TM_zjeWotTwb2UTl5yWEPxJRw_17;
						NI TM_zjeWotTwb2UTl5yWEPxJRw_18;
						NI TM_zjeWotTwb2UTl5yWEPxJRw_19;
						nimln_(194, "winstr.nim");
						if (!((NI)((NU64)(((NU8)(colontmp_[i]))) >> (NU64)(((NI) 3))) == ((NI) 30))) goto LA20_;
						nimln_(196, "winstr.nim");
						nimln_(195, "winstr.nim");
						nimln_(196, "winstr.nim");
						nimln_(209, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_16 = addInt(i, ((NI) 1));
						nimln_(197, "winstr.nim");
						nimln_(209, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_17 = addInt(i, ((NI) 2));
						nimln_(198, "winstr.nim");
						nimln_(209, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_18 = addInt(i, ((NI) 3));
						result_2 = (NI)((NI)((NI)((NI)((NU64)((NI)(((NU8)(colontmp_[i])) & ((NI) 7))) << (NU64)(((NI) 18))) | (NI)((NU64)((NI)(((NU8)(colontmp_[(NI)(TM_zjeWotTwb2UTl5yWEPxJRw_16)])) & ((NI) 63))) << (NU64)(((NI) 12)))) | (NI)((NU64)((NI)(((NU8)(colontmp_[(NI)(TM_zjeWotTwb2UTl5yWEPxJRw_17)])) & ((NI) 63))) << (NU64)(((NI) 6)))) | (NI)(((NU8)(colontmp_[(NI)(TM_zjeWotTwb2UTl5yWEPxJRw_18)])) & ((NI) 63)));
						TM_zjeWotTwb2UTl5yWEPxJRw_19 = addInt(i, ((NI) 4));
						i = (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_19);
					}
					goto LA9_;
					LA20_: ;
					{
						NI TM_zjeWotTwb2UTl5yWEPxJRw_20;
						nimln_(201, "winstr.nim");
						result_2 = ((NI) 65533);
						nimln_(209, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_20 = addInt(i, ((NI) 1));
						i = (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_20);
					}
					LA9_: ;
					nimln_(210, "winstr.nim");
					ch = result_2;
					nimln_(214, "winstr.nim");
					{
						if (!((NU64)(ch) <= (NU64)(((NI) 65535)))) goto LA25_;
						nimln_(215, "winstr.nim");
						{
							NIM_BOOL T29_;
							NI TM_zjeWotTwb2UTl5yWEPxJRw_21;
							T29_ = (NIM_BOOL)0;
							T29_ = ((NU64)(((NI) 55296)) <= (NU64)(ch));
							if (!(T29_)) goto LA30_;
							T29_ = ((NU64)(ch) <= (NU64)(((NI) 57343)));
							LA30_: ;
							if (!T29_) goto LA31_;
							nimln_(216, "winstr.nim");
							u = ((NU16) -3);
							nimln_(336, "winstr.nim");
							(*((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (result))).data[(d)- 0] = u;
							nimln_(337, "winstr.nim");
							TM_zjeWotTwb2UTl5yWEPxJRw_21 = addInt(d, ((NI) 1));
							if (TM_zjeWotTwb2UTl5yWEPxJRw_21 < (-2147483647 -1) || TM_zjeWotTwb2UTl5yWEPxJRw_21 > 2147483647) raiseOverflow();
							d = (NI32)(TM_zjeWotTwb2UTl5yWEPxJRw_21);
						}
						goto LA27_;
						LA31_: ;
						{
							NI TM_zjeWotTwb2UTl5yWEPxJRw_22;
							nimln_(218, "winstr.nim");
							u = ((NU16) (ch));
							nimln_(336, "winstr.nim");
							(*((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (result))).data[(d)- 0] = u;
							nimln_(337, "winstr.nim");
							TM_zjeWotTwb2UTl5yWEPxJRw_22 = addInt(d, ((NI) 1));
							if (TM_zjeWotTwb2UTl5yWEPxJRw_22 < (-2147483647 -1) || TM_zjeWotTwb2UTl5yWEPxJRw_22 > 2147483647) raiseOverflow();
							d = (NI32)(TM_zjeWotTwb2UTl5yWEPxJRw_22);
						}
						LA27_: ;
					}
					goto LA23_;
					LA25_: ;
					{
						NI TM_zjeWotTwb2UTl5yWEPxJRw_23;
						nimln_(219, "winstr.nim");
						if (!((NU64)(((NI) 1114111)) < (NU64)(ch))) goto LA35_;
						nimln_(220, "winstr.nim");
						u = ((NU16) -3);
						nimln_(336, "winstr.nim");
						(*((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (result))).data[(d)- 0] = u;
						nimln_(337, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_23 = addInt(d, ((NI) 1));
						if (TM_zjeWotTwb2UTl5yWEPxJRw_23 < (-2147483647 -1) || TM_zjeWotTwb2UTl5yWEPxJRw_23 > 2147483647) raiseOverflow();
						d = (NI32)(TM_zjeWotTwb2UTl5yWEPxJRw_23);
					}
					goto LA23_;
					LA35_: ;
					{
						NI ch_2;
						NI TM_zjeWotTwb2UTl5yWEPxJRw_24;
						NI TM_zjeWotTwb2UTl5yWEPxJRw_25;
						nimln_(222, "winstr.nim");
						ch_2 = (NI)((NU64)(ch) - (NU64)(((NI) 65536)));
						nimln_(223, "winstr.nim");
						u = ((NU16) ((NI)((NU64)((NI)((NU64)(ch_2) >> (NU64)(((NI) 10)))) + (NU64)(((NI) 55296)))));
						nimln_(336, "winstr.nim");
						(*((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (result))).data[(d)- 0] = u;
						nimln_(337, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_24 = addInt(d, ((NI) 1));
						if (TM_zjeWotTwb2UTl5yWEPxJRw_24 < (-2147483647 -1) || TM_zjeWotTwb2UTl5yWEPxJRw_24 > 2147483647) raiseOverflow();
						d = (NI32)(TM_zjeWotTwb2UTl5yWEPxJRw_24);
						nimln_(224, "winstr.nim");
						u = ((NU16) ((NI)((NU64)((NI)(ch_2 & ((NI) 1023))) + (NU64)(((NI) 56320)))));
						nimln_(336, "winstr.nim");
						(*((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (result))).data[(d)- 0] = u;
						nimln_(337, "winstr.nim");
						TM_zjeWotTwb2UTl5yWEPxJRw_25 = addInt(d, ((NI) 1));
						if (TM_zjeWotTwb2UTl5yWEPxJRw_25 < (-2147483647 -1) || TM_zjeWotTwb2UTl5yWEPxJRw_25 > 2147483647) raiseOverflow();
						d = (NI32)(TM_zjeWotTwb2UTl5yWEPxJRw_25);
					}
					LA23_: ;
				} LA8: ;
			}
		}
	}
	nimln_(339, "winstr.nim");
	(*((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (result))).data[(d)- 0] = ((NU16) 0);
	nimln_(340, "winstr.nim");
	lengtheq__pA9cXbQLyLAp3THEVThVOYgwinstr(((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (result)), ((NI)chckRange(d, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*, plusdollar__ZIeOLbV8A7WW4rfGi2H9blQwNim)(NimStringDesc* s) {
	tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* result;
	NIM_CHAR* T1_;
	void* T2_;
	nimfr_("+$", "winstr.nim");
	result = (tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*)0;
	nimln_(788, "winstr.nim");
	nimln_(792, "winstr.nim");
	T1_ = (NIM_CHAR*)0;
	T1_ = amp__UF719b2d9bwKZx7XI3tQrEywwNim(s);
	T2_ = (void*)0;
	T2_ = UTF8minusgtwstring__VC71MpyOPTe9cqdRNZwcehQ(T1_, ((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))), NIM_FALSE);
	result = ((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (T2_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU16*, winstringConverterStringToLPWSTR_j5XaAjYuDj9c2utB4McsEpQ)(NimStringDesc* x) {
	NU16* result;
	tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* T1_;
	NU16* T2_;
	nimfr_("winstringConverterStringToLPWSTR", "winstr.nim");
	result = (NU16*)0;
	nimln_(1072, "winstr.nim");
	T1_ = (tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*)0;
	T1_ = plusdollar__ZIeOLbV8A7WW4rfGi2H9blQwNim(x);
	T2_ = (NU16*)0;
	T2_ = amp__Dkk3SjGl9ay2BZoX9aVCCBOQwinstr(T1_);
	result = ((NU16*) (T2_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*, newWString_rHgYCTJaKMkrL2MrAlkIgw)(NI s) {
	tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* result;
	void* T1_;
	nimfr_("newWString", "winstr.nim");
	result = (tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*)0;
	nimln_(703, "winstr.nim");
	T1_ = (void*)0;
	T1_ = wstringBuffer_zjiLV19ao4Nfs7MiRLpp9b9bg_2(((NI)chckRange(s, ((NI) 0), ((NI) IL64(9223372036854775807)))), NIM_FALSE);
	result = ((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (T1_));
	popFrame();
	return result;
}

static N_INLINE(NI, length_oofNsbJA2r3sgNQGzNGrggwinstr)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* x) {
	NI result;
	nimfr_("length", "winstr.nim");
	result = (NI)0;
	nimln_(272, "winstr.nim");
	result = ((NI) ((NU32)((NU32)((*x).size) >> (NU64)(((NI) 1)))));
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

N_LIB_PRIVATE N_NIMCALL(void, setLen_XrDQ1BhAPHWWXsNDF9bqtSQ)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A** s, NI newLen) {
	nimfr_("setLen", "winstr.nim");
	nimln_(407, "winstr.nim");
	{
		NI T3_;
		T3_ = (NI)0;
		T3_ = length_oofNsbJA2r3sgNQGzNGrggwinstr((*s));
		if (!(((NI) (newLen)) < T3_)) goto LA4_;
		nimln_(408, "winstr.nim");
		(*(*s)).data[(((NI) (newLen)))- 0] = ((NU16) 0);
		nimln_(409, "winstr.nim");
		lengtheq__pA9cXbQLyLAp3THEVThVOYgwinstr((*s), ((NI)chckRange(((NI32)chckRange(newLen, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	goto LA1_;
	LA4_: ;
	{
		tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* n;
		void* T7_;
		NU16* T8_;
		NU16* T9_;
		NI T10_;
		NI TM_zjeWotTwb2UTl5yWEPxJRw_26;
		nimln_(411, "winstr.nim");
		T7_ = (void*)0;
		T7_ = wstringBuffer_zjiLV19ao4Nfs7MiRLpp9b9bg_2(newLen, NIM_FALSE);
		n = ((tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*) (T7_));
		nimln_(412, "winstr.nim");
		T8_ = (NU16*)0;
		T8_ = amp__Dkk3SjGl9ay2BZoX9aVCCBOQwinstr(n);
		T9_ = (NU16*)0;
		T9_ = amp__Dkk3SjGl9ay2BZoX9aVCCBOQwinstr((*s));
		T10_ = (NI)0;
		T10_ = length_oofNsbJA2r3sgNQGzNGrggwinstr((*s));
		TM_zjeWotTwb2UTl5yWEPxJRw_26 = mulInt(T10_, ((NI) 2));
		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) (T8_)), ((void*) (T9_)), ((NI)chckRange((NI)(TM_zjeWotTwb2UTl5yWEPxJRw_26), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(413, "winstr.nim");
		unsureAsgnRef((void**) (&(*s)), n);
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(NI, len_oofNsbJA2r3sgNQGzNGrggwNim)(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* x) {
	NI result;
	nimfr_("len", "winstr.nim");
	result = (NI)0;
	nimln_(402, "winstr.nim");
	result = length_oofNsbJA2r3sgNQGzNGrggwinstr(x);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, fillArray_t4Kvt6m9cQmp9bvzp9c9alnxZA)(NU16* a, tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* s, NIM_BOOL inclNull) {
	nimfr_("fillArray", "winstr.nim");
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI TM_zjeWotTwb2UTl5yWEPxJRw_27;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(974, "winstr.nim");
		T2_ = (NI)0;
		T2_ = len_oofNsbJA2r3sgNQGzNGrggwNim(s);
		TM_zjeWotTwb2UTl5yWEPxJRw_27 = subInt(T2_, ((NI) 1));
		colontmp_ = ((NI)chckRange(((((NI) 31) <= (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_27)) ? ((NI) 31) : (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_27)), ((NI) 0), ((NI) 31)));
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_zjeWotTwb2UTl5yWEPxJRw_28;
				if (!(res <= ((NI) (colontmp_)))) goto LA4;
				nimln_(2047, "system.nim");
				i = ((NI)chckRange(res, ((NI) 0), ((NI) 31)));
				nimln_(975, "winstr.nim");
				a[(i)- 0] = ((NU16) ((*s).data[(((NI) (i)))- 0]));
				nimln_(2048, "system.nim");
				TM_zjeWotTwb2UTl5yWEPxJRw_28 = addInt(res, ((NI) 1));
				res = (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_28);
			} LA4: ;
		}
	}
	nimln_(977, "winstr.nim");
	{
		NIM_BOOL T7_;
		NI T9_;
		NI T12_;
		T7_ = (NIM_BOOL)0;
		T7_ = inclNull;
		if (!(T7_)) goto LA8_;
		T9_ = (NI)0;
		T9_ = len_oofNsbJA2r3sgNQGzNGrggwNim(s);
		T7_ = (T9_ <= ((NI) 31));
		LA8_: ;
		if (!T7_) goto LA10_;
		nimln_(978, "winstr.nim");
		T12_ = (NI)0;
		T12_ = len_oofNsbJA2r3sgNQGzNGrggwNim(s);
		if ((NU)(T12_) > (NU)(31)) raiseIndexError();
		a[(T12_)- 0] = ((NU16) (((NI) 0)));
	}
	LA10_: ;
	nimln_(981, "winstr.nim");
	{
		NIM_BOOL T15_;
		NIM_BOOL T16_;
		NI T18_;
		NI TM_zjeWotTwb2UTl5yWEPxJRw_29;
		NIM_BOOL T20_;
		NI T22_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T25_;
		T15_ = (NIM_BOOL)0;
		T16_ = (NIM_BOOL)0;
		T16_ = !(inclNull);
		if (!(T16_)) goto LA17_;
		T18_ = (NI)0;
		T18_ = len_oofNsbJA2r3sgNQGzNGrggwNim(s);
		TM_zjeWotTwb2UTl5yWEPxJRw_29 = subInt(T18_, ((NI) 1));
		T16_ = (((NI) 31) < (NI)(TM_zjeWotTwb2UTl5yWEPxJRw_29));
		LA17_: ;
		T15_ = T16_;
		if (T15_) goto LA19_;
		T20_ = (NIM_BOOL)0;
		T20_ = inclNull;
		if (!(T20_)) goto LA21_;
		T22_ = (NI)0;
		T22_ = len_oofNsbJA2r3sgNQGzNGrggwNim(s);
		T20_ = (((NI) 31) < T22_);
		LA21_: ;
		T15_ = T20_;
		LA19_: ;
		if (!T15_) goto LA23_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		nimln_(982, "winstr.nim");
		T25_ = (NimStringDesc*)0;
		T25_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_zjeWotTwb2UTl5yWEPxJRw_30));
		if (T25_) nimGCunrefNoCycle(T25_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(982, "winstr.nim");
		raiseException((Exception*)e, "IndexError");
	}
	LA23_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, fillArray_p1T9b6Ni1VBySgQswnDzP3A)(tyArray_9a9aAlfXLJPjHXnuFdEbFDFg a, tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A* s, NIM_BOOL inclNull) {
	nimfr_("fillArray", "winstr.nim");
	nimln_(985, "winstr.nim");
	fillArray_t4Kvt6m9cQmp9bvzp9c9alnxZA(a, s, inclNull);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NU16*, winstringConverterPtrArrayToLPWSTR_UieaOO9cH5kcpRsF6C0tNbw)(NU16* x) {
	NU16* result;
	nimfr_("winstringConverterPtrArrayToLPWSTR", "winstr.nim");
	result = (NU16*)0;
	nimln_(1093, "winstr.nim");
	result = ((NU16*) (x));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, winim_winstrInit000)(void) {
	nimfr_("winstr", "winstr.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, winim_winstrDatInit000)(void) {
static TNimNode* TM_zjeWotTwb2UTl5yWEPxJRw_8[2];
static TNimNode TM_zjeWotTwb2UTl5yWEPxJRw_0[3];
NTI_C9b8rfrA3THHK7wuwo5q9c0A_.size = sizeof(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A);
NTI_C9b8rfrA3THHK7wuwo5q9c0A_.kind = 18;
NTI_C9b8rfrA3THHK7wuwo5q9c0A_.base = 0;
NTI_C9b8rfrA3THHK7wuwo5q9c0A_.flags = 3;
TM_zjeWotTwb2UTl5yWEPxJRw_8[0] = &TM_zjeWotTwb2UTl5yWEPxJRw_0[1];
TM_zjeWotTwb2UTl5yWEPxJRw_0[1].kind = 1;
TM_zjeWotTwb2UTl5yWEPxJRw_0[1].offset = offsetof(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A, size);
TM_zjeWotTwb2UTl5yWEPxJRw_0[1].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_zjeWotTwb2UTl5yWEPxJRw_0[1].name = "size";
TM_zjeWotTwb2UTl5yWEPxJRw_8[1] = &TM_zjeWotTwb2UTl5yWEPxJRw_0[2];
TM_zjeWotTwb2UTl5yWEPxJRw_0[2].kind = 1;
TM_zjeWotTwb2UTl5yWEPxJRw_0[2].offset = offsetof(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A, data);
TM_zjeWotTwb2UTl5yWEPxJRw_0[2].typ = (&NTI_Ho4W3BYv4hTk8axhGpqWCQ_);
TM_zjeWotTwb2UTl5yWEPxJRw_0[2].name = "data";
TM_zjeWotTwb2UTl5yWEPxJRw_0[0].len = 2; TM_zjeWotTwb2UTl5yWEPxJRw_0[0].kind = 2; TM_zjeWotTwb2UTl5yWEPxJRw_0[0].sons = &TM_zjeWotTwb2UTl5yWEPxJRw_8[0];
NTI_C9b8rfrA3THHK7wuwo5q9c0A_.node = &TM_zjeWotTwb2UTl5yWEPxJRw_0[0];
NTI_K9aqAvBsg5rtPpgIZn4jwsQ_.size = sizeof(tyObject_wstringcolonObjectType__C9b8rfrA3THHK7wuwo5q9c0A*);
NTI_K9aqAvBsg5rtPpgIZn4jwsQ_.kind = 22;
NTI_K9aqAvBsg5rtPpgIZn4jwsQ_.base = (&NTI_C9b8rfrA3THHK7wuwo5q9c0A_);
NTI_K9aqAvBsg5rtPpgIZn4jwsQ_.flags = 2;
NTI_K9aqAvBsg5rtPpgIZn4jwsQ_.marker = Marker_tyRef_K9aqAvBsg5rtPpgIZn4jwsQ;
}

