/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   F:\nim\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IF:\nim\lib -o O:\nim\wnim\release\examples\nimcache\winim_virtdisk.o O:\nim\wnim\release\examples\nimcache\winim_virtdisk.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ;
typedef struct tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g;
typedef struct tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA;
typedef struct tyObject_VIRTUAL_STORAGE_TYPE_aR6Dfjppo8SB89bgYMGUtpA tyObject_VIRTUAL_STORAGE_TYPE_aR6Dfjppo8SB89bgYMGUtpA;
typedef struct tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q;
typedef struct tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg;
typedef struct tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA;
typedef struct tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ;
typedef struct tyObject_VIRTUAL_DISK_PROGRESS_RZcHQzWSHyFet21rgphFHA tyObject_VIRTUAL_DISK_PROGRESS_RZcHQzWSHyFet21rgphFHA;
typedef struct tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ;
typedef struct tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig;
typedef struct tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg;
typedef struct tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A;
typedef union tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_JwGFueLjI9cRDHThSw0gGqQ tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_JwGFueLjI9cRDHThSw0gGqQ;
typedef struct tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg;
typedef union tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_OOzWQBqJ8dVzoKLv1Ip14Q tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_OOzWQBqJ8dVzoKLv1Ip14Q;
typedef struct tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ;
typedef union tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Ds1snMhRof9c4fjhX7r04pw tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Ds1snMhRof9c4fjhX7r04pw;
typedef struct tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA;
typedef struct tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA;
typedef union tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_wxCwgvSVedLPDLI7eUdjHg tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_wxCwgvSVedLPDLI7eUdjHg;
typedef union tyObject_GET_VIRTUAL_DISK_INFO_UNION1_LH4od14Li3Tq3mka6lpaNA tyObject_GET_VIRTUAL_DISK_INFO_UNION1_LH4od14Li3Tq3mka6lpaNA;
typedef struct tyObject_GET_VIRTUAL_DISK_INFO_UNION1_Size_hhrRPYcDw6pcaZZCZNizBQ tyObject_GET_VIRTUAL_DISK_INFO_UNION1_Size_hhrRPYcDw6pcaZZCZNizBQ;
typedef struct tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w;
typedef struct tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg;
typedef union tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_xdIWwzzbjoyy19cuJeeX9avQ tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_xdIWwzzbjoyy19cuJeeX9avQ;
typedef struct tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw;
typedef union tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_D2Hdtf9bE0KbDffPM8mavig tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_D2Hdtf9bE0KbDffPM8mavig;
typedef union tyObject_SET_VIRTUAL_DISK_INFO_UNION1_CmVY9bmWcq4w3sVAcHPTVPw tyObject_SET_VIRTUAL_DISK_INFO_UNION1_CmVY9bmWcq4w3sVAcHPTVPw;
typedef struct tyObject_STORAGE_DEPENDENCY_INFO_TYPE1_KFhqBDEARoPFAcbb6EBtGA tyObject_STORAGE_DEPENDENCY_INFO_TYPE1_KFhqBDEARoPFAcbb6EBtGA;
typedef union tyObject_STORAGE_DEPENDENCY_INFO_UNION1_c59aaWdNdaQlb6pb9baQKduA tyObject_STORAGE_DEPENDENCY_INFO_UNION1_c59aaWdNdaQlb6pb9baQKduA;
typedef struct tyObject_STORAGE_DEPENDENCY_INFO_TYPE2_vdD6RkSDrl1mE6NECHdrTQ tyObject_STORAGE_DEPENDENCY_INFO_TYPE2_vdD6RkSDrl1mE6NECHdrTQ;
typedef union tyObject_OVERLAPPED_UNION1_AVbfcQStGnh3fZbJC3cvzg tyObject_OVERLAPPED_UNION1_AVbfcQStGnh3fZbJC3cvzg;
typedef struct tyObject_OVERLAPPED_UNION1_STRUCT1_Tw4imf9bYItly5rbLz303yA tyObject_OVERLAPPED_UNION1_STRUCT1_Tw4imf9bYItly5rbLz303yA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, tyProc_ZuTEyl9cg2rpd7xBbRhYjeQ) (NI VirtualDiskHandle, void* SecurityDescriptor, NI32 Flags, NI32 ProviderSpecificFlags, tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ* Parameters, tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g* Overlapped);
typedef N_STDCALL_PTR(NI32, tyProc_QIKLqykTE7dIrM9bFLwwJ8A) (NI VirtualDiskHandle, NI32 Flags, tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA* Parameters, tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g* Overlapped);
typedef N_STDCALL_PTR(NI32, tyProc_2hU715aCvdkAoU2UX7oCSg) (tyObject_VIRTUAL_STORAGE_TYPE_aR6Dfjppo8SB89bgYMGUtpA* VirtualStorageType, NU16* Path, NI32 VirtualDiskAccessMask, void* SecurityDescriptor, NI32 Flags, NI32 ProviderSpecificFlags, tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q* Parameters, tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g* Overlapped, NI* Handle);
typedef N_STDCALL_PTR(NI32, tyProc_mBVOPXmpGfUrrbA9a5K9cMbQ) (NI VirtualDiskHandle, NI32 Flags, NI32 ProviderSpecificFlags);
typedef N_STDCALL_PTR(NI32, tyProc_If2FO4Wv8m84UknSxCB9a5A) (NI VirtualDiskHandle, NI32 Flags, tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg* Parameters, tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g* Overlapped);
typedef N_STDCALL_PTR(NI32, tyProc_02vLxryyRhAvosORshlGuw) (NI ObjectHandle, NI32 Flags, NI32 StorageDependencyInfoSize, tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* StorageDependencyInfo, NI32* SizeUsed);
typedef N_STDCALL_PTR(NI32, tyProc_zNnG3Jjv1IBShy60Ti1mww) (NI VirtualDiskHandle, NI32* VirtualDiskInfoSize, tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* VirtualDiskInfo, NI32* SizeUsed);
typedef N_STDCALL_PTR(NI32, tyProc_S4yGHUS9aGZMK59b9corBGr5w) (NI VirtualDiskHandle, tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g* Overlapped, tyObject_VIRTUAL_DISK_PROGRESS_RZcHQzWSHyFet21rgphFHA* Progress);
typedef N_STDCALL_PTR(NI32, tyProc_TQx9ajhr9bWjvgFt9cGET7y1Q) (NI VirtualDiskHandle, NI32* DiskPathSizeInBytes, NU16* DiskPath);
typedef N_STDCALL_PTR(NI32, tyProc_3P9aegprzS9aWzVPIG4iIMDQ) (NI VirtualDiskHandle, NI32 Flags, tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ* Parameters, tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g* Overlapped);
typedef N_STDCALL_PTR(NI32, tyProc_2EaxwQsemqru70jv9aS9bWXA) (tyObject_VIRTUAL_STORAGE_TYPE_aR6Dfjppo8SB89bgYMGUtpA* VirtualStorageType, NU16* Path, NI32 VirtualDiskAccessMask, NI32 Flags, tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig* Parameters, NI* Handle);
typedef N_STDCALL_PTR(NI32, tyProc_9cfs9cQDoLHV39bI5uZSvzC7w) (NI VirtualDiskHandle, tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* VirtualDiskInfo);
struct tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A {
NI32 Reserved;
};
union tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_JwGFueLjI9cRDHThSw0gGqQ {
tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A Version1;
};
struct tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ {
NI32 Version;
tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_JwGFueLjI9cRDHThSw0gGqQ union1;
};
struct tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg {
NI32 Reserved;
};
union tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_OOzWQBqJ8dVzoKLv1Ip14Q {
tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg Version1;
};
struct tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA {
NI32 Version;
tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_OOzWQBqJ8dVzoKLv1Ip14Q union1;
};
typedef NU8 tyArray_cdsir9aPB24hAk6k77P9b9bCA[8];
struct tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA {
NI32 Data1;
NU16 Data2;
NU16 Data3;
tyArray_cdsir9aPB24hAk6k77P9b9bCA Data4;
};
struct tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ {
tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA UniqueId;
NU64 MaximumSize;
NI32 BlockSizeInBytes;
NI32 SectorSizeInBytes;
NU16* ParentPath;
NU16* SourcePath;
};
union tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Ds1snMhRof9c4fjhX7r04pw {
tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ Version1;
};
struct tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q {
NI32 Version;
tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Ds1snMhRof9c4fjhX7r04pw union1;
};
struct tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA {
NU64 NewSize;
};
union tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_wxCwgvSVedLPDLI7eUdjHg {
tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA Version1;
};
struct tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg {
NI32 Version;
tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_wxCwgvSVedLPDLI7eUdjHg union1;
};
struct tyObject_GET_VIRTUAL_DISK_INFO_UNION1_Size_hhrRPYcDw6pcaZZCZNizBQ {
NU64 VirtualSize;
NU64 PhysicalSize;
NI32 BlockSize;
NI32 SectorSize;
};
typedef NU16 tyArray_8ukKyGE9bOapwMgK0A10LHw[1];
struct tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w {
NI32 ParentResolved;
tyArray_8ukKyGE9bOapwMgK0A10LHw ParentLocationBuffer;
};
struct tyObject_VIRTUAL_STORAGE_TYPE_aR6Dfjppo8SB89bgYMGUtpA {
NI32 DeviceId;
tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA VendorId;
};
union tyObject_GET_VIRTUAL_DISK_INFO_UNION1_LH4od14Li3Tq3mka6lpaNA {
tyObject_GET_VIRTUAL_DISK_INFO_UNION1_Size_hhrRPYcDw6pcaZZCZNizBQ Size;
tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA Identifier;
tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w ParentLocation;
tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA ParentIdentifier;
NI32 ParentTimestamp;
tyObject_VIRTUAL_STORAGE_TYPE_aR6Dfjppo8SB89bgYMGUtpA VirtualStorageType;
NI32 ProviderSubtype;
};
struct tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ {
NI32 Version;
tyObject_GET_VIRTUAL_DISK_INFO_UNION1_LH4od14Li3Tq3mka6lpaNA union1;
};
struct tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg {
NI32 MergeDepth;
};
union tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_xdIWwzzbjoyy19cuJeeX9avQ {
tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg Version1;
};
struct tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ {
NI32 Version;
tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_xdIWwzzbjoyy19cuJeeX9avQ union1;
};
struct tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw {
NI32 RWDepth;
};
union tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_D2Hdtf9bE0KbDffPM8mavig {
tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw Version1;
};
struct tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig {
NI32 Version;
tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_D2Hdtf9bE0KbDffPM8mavig union1;
};
union tyObject_SET_VIRTUAL_DISK_INFO_UNION1_CmVY9bmWcq4w3sVAcHPTVPw {
NU16* ParentFilePath;
tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA UniqueIdentifier;
};
struct tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg {
NI32 Version;
tyObject_SET_VIRTUAL_DISK_INFO_UNION1_CmVY9bmWcq4w3sVAcHPTVPw union1;
};
struct tyObject_STORAGE_DEPENDENCY_INFO_TYPE1_KFhqBDEARoPFAcbb6EBtGA {
NI32 DependencyTypeFlags;
NI32 ProviderSpecificFlags;
tyObject_VIRTUAL_STORAGE_TYPE_aR6Dfjppo8SB89bgYMGUtpA VirtualStorageType;
};
typedef tyObject_STORAGE_DEPENDENCY_INFO_TYPE1_KFhqBDEARoPFAcbb6EBtGA tyArray_lGFC8OrbT9aoaguRXzp9a2Ng[1];
struct tyObject_STORAGE_DEPENDENCY_INFO_TYPE2_vdD6RkSDrl1mE6NECHdrTQ {
NI32 DependencyTypeFlags;
NI32 ProviderSpecificFlags;
tyObject_VIRTUAL_STORAGE_TYPE_aR6Dfjppo8SB89bgYMGUtpA VirtualStorageType;
NI32 AncestorLevel;
NU16* DependencyDeviceName;
NU16* HostVolumeName;
NU16* DependentVolumeName;
NU16* DependentVolumeRelativePath;
};
typedef tyObject_STORAGE_DEPENDENCY_INFO_TYPE2_vdD6RkSDrl1mE6NECHdrTQ tyArray_2a0W9b6WLiQYr2WITy7c4Dw[1];
union tyObject_STORAGE_DEPENDENCY_INFO_UNION1_c59aaWdNdaQlb6pb9baQKduA {
tyArray_lGFC8OrbT9aoaguRXzp9a2Ng Version1Entries;
tyArray_2a0W9b6WLiQYr2WITy7c4Dw Version2Entries;
};
struct tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA {
NI32 Version;
NI32 NumberEntries;
tyObject_STORAGE_DEPENDENCY_INFO_UNION1_c59aaWdNdaQlb6pb9baQKduA union1;
};
struct tyObject_OVERLAPPED_UNION1_STRUCT1_Tw4imf9bYItly5rbLz303yA {
NI32 Offset;
NI32 OffsetHigh;
};
union tyObject_OVERLAPPED_UNION1_AVbfcQStGnh3fZbJC3cvzg {
tyObject_OVERLAPPED_UNION1_STRUCT1_Tw4imf9bYItly5rbLz303yA struct1;
void* Pointer;
};
struct tyObject_OVERLAPPED_LHlIhlydQGyLOxqVYjrm2g {
NU64 Internal;
NU64 InternalHigh;
tyObject_OVERLAPPED_UNION1_AVbfcQStGnh3fZbJC3cvzg union1;
NI hEvent;
};
struct tyObject_VIRTUAL_DISK_PROGRESS_RZcHQzWSHyFet21rgphFHA {
NI32 OperationStatus;
NU64 CurrentValue;
NU64 CompletionValue;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, Version1eq__lmmJ5NZqbLiIJsELVM6vKgvirtdisk)(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ* self, tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A, Version1_Hgd9cnullN4Uh0ixm1oNi9cgvirtdisk)(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ self);
static N_INLINE(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A*, Version1_Lm9bYBbyrBda9ag2hfIMZFOQvirtdisk)(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ* self);
static N_INLINE(void, Version1eq__z9bPbOB6ZvO9acIh57hVfmjQvirtdisk)(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA* self, tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg x);
static N_INLINE(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg, Version1_p4dYFDV3W9bBaqR6yWGitDwvirtdisk)(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA self);
static N_INLINE(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg*, Version1_AgMnjPkjSyejWwpqvWw89cgvirtdisk)(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA* self);
static N_INLINE(void, Version1eq__n7UJ9bTyXeEM7ZpiJEXCAPgvirtdisk)(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q* self, tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ* x);
static N_INLINE(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ, Version1_J1wYUcErdzO9baF9cpo81MrQvirtdisk)(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q* self);
static N_INLINE(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ*, Version1_Kk7mAux7c0ZRyOfTiKQq6Avirtdisk)(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q* self);
static N_INLINE(void, Version1eq__5czENKWPsPckXfaDUvsBHwvirtdisk)(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg* self, tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA x);
static N_INLINE(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA, Version1_05ftZpfsPiZZKsJd8RwCzAvirtdisk)(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg self);
static N_INLINE(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA*, Version1_f4ybR0ZKsgPnk9b5L9aNChogvirtdisk)(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg* self);
static N_INLINE(void, Identifiereq__FIvkGnaUzI41FOpQY3qt0Avirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA x);
static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA, Identifier_oMxYvIR4TGTFJ9cSt0zq47Avirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*, Identifier_SwmcTsqqktgzabEGwOCuLgvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(void, ParentLocationeq__mqfinN1nFZbwUGOCfBdY7gvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w x);
static N_INLINE(tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w, ParentLocation_SA29bJyNNZI9b4G63LOtkEhgvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w*, ParentLocation_II0p9a16qRmPaIrhU9aY9aW0wvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(void, ParentIdentifiereq__FIvkGnaUzI41FOpQY3qt0A_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA x);
static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA, ParentIdentifier_oMxYvIR4TGTFJ9cSt0zq47A_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*, ParentIdentifier_SwmcTsqqktgzabEGwOCuLg_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(void, ParentTimestampeq__bgrzULm3ow9cT20w3vIEESQvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, NI32 x);
static N_INLINE(NI32, ParentTimestamp_Joz09b29clSWCfTIxYsFcA2Avirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(NI32*, ParentTimestamp_8PKAjAKvPZOoNj6SSs4SkAvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(void, ProviderSubtypeeq__bgrzULm3ow9cT20w3vIEESQ_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, NI32 x);
static N_INLINE(NI32, ProviderSubtype_Joz09b29clSWCfTIxYsFcA2A_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(NI32*, ProviderSubtype_8PKAjAKvPZOoNj6SSs4SkA_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self);
static N_INLINE(void, Version1eq__vTHQKsAiWWyNulATB6Ja9bgvirtdisk)(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ* self, tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg x);
static N_INLINE(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg, Version1_O8kWSa9b9avg5PIG4H3l9cEKQvirtdisk)(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ self);
static N_INLINE(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg*, Version1_dQ0hU7EAxP49crCg0PT9bj9cAvirtdisk)(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ* self);
static N_INLINE(void, Version1eq__h1Cdqouwuk9blDa682nri1gvirtdisk)(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig* self, tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw x);
static N_INLINE(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw, Version1_9csLCfGlPuXUjf2C7MgV9a7Qvirtdisk)(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig self);
static N_INLINE(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw*, Version1_sutWakQoz1i9cecMxYHrBVgvirtdisk)(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig* self);
static N_INLINE(void, ParentFilePatheq__JiFcFvJJbkCgdrDOUsyY6Avirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self, NU16* x);
static N_INLINE(NU16*, ParentFilePath_hUPG8KU51aIa9bP4BUZosAgvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self);
static N_INLINE(NU16**, ParentFilePath_9bJ8aqHG0kJ39ambSJIj9cwqwvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self);
static N_INLINE(void, UniqueIdentifiereq__er2lTyV9bgMHx9bpnqnnEEcAvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self, tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA x);
static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA, UniqueIdentifier_rdwk9bD7N5tvkLJd2YI9bquQvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self);
static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*, UniqueIdentifier_zmjKmFd2lbJfLV0u4z2JZgvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self);
static N_INLINE(void, Version1Entrieseq__lk7DK9adiABH9aLDnLdKY0GQvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self, tyArray_lGFC8OrbT9aoaguRXzp9a2Ng x);
static N_INLINE(void, Version1Entries_lOaSGX2GIiVJ8rfzwNastwvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self, tyArray_lGFC8OrbT9aoaguRXzp9a2Ng Result);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(tyObject_STORAGE_DEPENDENCY_INFO_TYPE1_KFhqBDEARoPFAcbb6EBtGA*, Version1Entries_A0L0VRSVthssS8pH2x4LOwvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self);
static N_INLINE(void, Version2Entrieseq__dgxyNnx8IB2KbumbyNAzfwvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self, tyArray_2a0W9b6WLiQYr2WITy7c4Dw x);
static N_INLINE(void, Version2Entries_mveQihddoxKAg9cMtWBAU9aAvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self, tyArray_2a0W9b6WLiQYr2WITy7c4Dw Result);
static N_INLINE(tyObject_STORAGE_DEPENDENCY_INFO_TYPE2_vdD6RkSDrl1mE6NECHdrTQ*, Version2Entries_kLcQgb0hR2cQ0kY0BW1pywvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self);
static void* TM_4Q3Fp3DyaliCi78oLMU1dw_2;
tyProc_ZuTEyl9cg2rpd7xBbRhYjeQ Dl_303308_;
tyProc_QIKLqykTE7dIrM9bFLwwJ8A Dl_303316_;
tyProc_2hU715aCvdkAoU2UX7oCSg Dl_303322_;
tyProc_mBVOPXmpGfUrrbA9a5K9cMbQ Dl_303333_;
tyProc_If2FO4Wv8m84UknSxCB9a5A Dl_303338_;
tyProc_02vLxryyRhAvosORshlGuw Dl_303344_;
tyProc_zNnG3Jjv1IBShy60Ti1mww Dl_303351_;
tyProc_S4yGHUS9aGZMK59b9corBGr5w Dl_303357_;
tyProc_TQx9ajhr9bWjvgFt9cGET7y1Q Dl_303362_;
tyProc_3P9aegprzS9aWzVPIG4iIMDQ Dl_303367_;
tyProc_2EaxwQsemqru70jv9aS9bWXA Dl_303373_;
tyProc_9cfs9cQDoLHV39bI5uZSvzC7w Dl_303381_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_4Q3Fp3DyaliCi78oLMU1dw_4, "virtdisk", 8);
STRING_LITERAL(TM_4Q3Fp3DyaliCi78oLMU1dw_5, "virtdisk", 8);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, Version1eq__lmmJ5NZqbLiIJsELVM6vKgvirtdisk)(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ* self, tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A x) {
	nimfr_("Version1=", "virtdisk.nim");
	nimln_(226, "virtdisk.nim");
	(*self).union1.Version1 = x;
	popFrame();
}

static N_INLINE(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A, Version1_Hgd9cnullN4Uh0ixm1oNi9cgvirtdisk)(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ self) {
	tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A result;
	nimfr_("Version1", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(227, "virtdisk.nim");
	result = self.union1.Version1;
	popFrame();
	return result;
}

static N_INLINE(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A*, Version1_Lm9bYBbyrBda9ag2hfIMZFOQvirtdisk)(tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_2ztPdrbzqnzHSuj0GhaJAQ* self) {
	tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A* result;
	nimfr_("Version1", "virtdisk.nim");
	result = (tyObject_ATTACH_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_jlHNDY9aMZsP5WKXvBUYp7A*)0;
	nimln_(228, "virtdisk.nim");
	result = (&(*self).union1.Version1);
	popFrame();
	return result;
}

static N_INLINE(void, Version1eq__z9bPbOB6ZvO9acIh57hVfmjQvirtdisk)(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA* self, tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg x) {
	nimfr_("Version1=", "virtdisk.nim");
	nimln_(229, "virtdisk.nim");
	(*self).union1.Version1 = x;
	popFrame();
}

static N_INLINE(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg, Version1_p4dYFDV3W9bBaqR6yWGitDwvirtdisk)(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA self) {
	tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg result;
	nimfr_("Version1", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(230, "virtdisk.nim");
	result = self.union1.Version1;
	popFrame();
	return result;
}

static N_INLINE(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg*, Version1_AgMnjPkjSyejWwpqvWw89cgvirtdisk)(tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_vE0QwG1vvmLfQAds542GdA* self) {
	tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg* result;
	nimfr_("Version1", "virtdisk.nim");
	result = (tyObject_COMPACT_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_e1ey6OP5WwZpHuEGpGbJFg*)0;
	nimln_(231, "virtdisk.nim");
	result = (&(*self).union1.Version1);
	popFrame();
	return result;
}

static N_INLINE(void, Version1eq__n7UJ9bTyXeEM7ZpiJEXCAPgvirtdisk)(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q* self, tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ* x) {
	nimfr_("Version1=", "virtdisk.nim");
	nimln_(232, "virtdisk.nim");
	(*self).union1.Version1 = (*x);
	popFrame();
}

static N_INLINE(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ, Version1_J1wYUcErdzO9baF9cpo81MrQvirtdisk)(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q* self) {
	tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ result;
	nimfr_("Version1", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(233, "virtdisk.nim");
	result = (*self).union1.Version1;
	popFrame();
	return result;
}

static N_INLINE(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ*, Version1_Kk7mAux7c0ZRyOfTiKQq6Avirtdisk)(tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_JAHwfk7w2d9a3aYi79b9a4a8Q* self) {
	tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ* result;
	nimfr_("Version1", "virtdisk.nim");
	result = (tyObject_CREATE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_q69aBAdeKA34hyluDmVtrfQ*)0;
	nimln_(234, "virtdisk.nim");
	result = (&(*self).union1.Version1);
	popFrame();
	return result;
}

static N_INLINE(void, Version1eq__5czENKWPsPckXfaDUvsBHwvirtdisk)(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg* self, tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA x) {
	nimfr_("Version1=", "virtdisk.nim");
	nimln_(235, "virtdisk.nim");
	(*self).union1.Version1 = x;
	popFrame();
}

static N_INLINE(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA, Version1_05ftZpfsPiZZKsJd8RwCzAvirtdisk)(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg self) {
	tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA result;
	nimfr_("Version1", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(236, "virtdisk.nim");
	result = self.union1.Version1;
	popFrame();
	return result;
}

static N_INLINE(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA*, Version1_f4ybR0ZKsgPnk9b5L9aNChogvirtdisk)(tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_mXbAu9b4etVZK0n82l8SSNg* self) {
	tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA* result;
	nimfr_("Version1", "virtdisk.nim");
	result = (tyObject_EXPAND_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_8A6UBx241RqtFy9ap9bBdVaA*)0;
	nimln_(237, "virtdisk.nim");
	result = (&(*self).union1.Version1);
	popFrame();
	return result;
}

static N_INLINE(void, Identifiereq__FIvkGnaUzI41FOpQY3qt0Avirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA x) {
	nimfr_("Identifier=", "virtdisk.nim");
	nimln_(238, "virtdisk.nim");
	(*self).union1.Identifier = x;
	popFrame();
}

static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA, Identifier_oMxYvIR4TGTFJ9cSt0zq47Avirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA result;
	nimfr_("Identifier", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(239, "virtdisk.nim");
	result = (*self).union1.Identifier;
	popFrame();
	return result;
}

static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*, Identifier_SwmcTsqqktgzabEGwOCuLgvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA* result;
	nimfr_("Identifier", "virtdisk.nim");
	result = (tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*)0;
	nimln_(240, "virtdisk.nim");
	result = (&(*self).union1.Identifier);
	popFrame();
	return result;
}

static N_INLINE(void, ParentLocationeq__mqfinN1nFZbwUGOCfBdY7gvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w x) {
	nimfr_("ParentLocation=", "virtdisk.nim");
	nimln_(241, "virtdisk.nim");
	(*self).union1.ParentLocation = x;
	popFrame();
}

static N_INLINE(tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w, ParentLocation_SA29bJyNNZI9b4G63LOtkEhgvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w result;
	nimfr_("ParentLocation", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(242, "virtdisk.nim");
	result = (*self).union1.ParentLocation;
	popFrame();
	return result;
}

static N_INLINE(tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w*, ParentLocation_II0p9a16qRmPaIrhU9aY9aW0wvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w* result;
	nimfr_("ParentLocation", "virtdisk.nim");
	result = (tyObject_GET_VIRTUAL_DISK_INFO_UNION1_ParentLocation_sFPvPgiILXmZNF0y9cJT72w*)0;
	nimln_(243, "virtdisk.nim");
	result = (&(*self).union1.ParentLocation);
	popFrame();
	return result;
}

static N_INLINE(void, ParentIdentifiereq__FIvkGnaUzI41FOpQY3qt0A_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA x) {
	nimfr_("ParentIdentifier=", "virtdisk.nim");
	nimln_(244, "virtdisk.nim");
	(*self).union1.ParentIdentifier = x;
	popFrame();
}

static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA, ParentIdentifier_oMxYvIR4TGTFJ9cSt0zq47A_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA result;
	nimfr_("ParentIdentifier", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(245, "virtdisk.nim");
	result = (*self).union1.ParentIdentifier;
	popFrame();
	return result;
}

static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*, ParentIdentifier_SwmcTsqqktgzabEGwOCuLg_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA* result;
	nimfr_("ParentIdentifier", "virtdisk.nim");
	result = (tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*)0;
	nimln_(246, "virtdisk.nim");
	result = (&(*self).union1.ParentIdentifier);
	popFrame();
	return result;
}

static N_INLINE(void, ParentTimestampeq__bgrzULm3ow9cT20w3vIEESQvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, NI32 x) {
	nimfr_("ParentTimestamp=", "virtdisk.nim");
	nimln_(247, "virtdisk.nim");
	(*self).union1.ParentTimestamp = x;
	popFrame();
}

static N_INLINE(NI32, ParentTimestamp_Joz09b29clSWCfTIxYsFcA2Avirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	NI32 result;
	nimfr_("ParentTimestamp", "virtdisk.nim");
	result = (NI32)0;
	nimln_(248, "virtdisk.nim");
	result = (*self).union1.ParentTimestamp;
	popFrame();
	return result;
}

static N_INLINE(NI32*, ParentTimestamp_8PKAjAKvPZOoNj6SSs4SkAvirtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	NI32* result;
	nimfr_("ParentTimestamp", "virtdisk.nim");
	result = (NI32*)0;
	nimln_(249, "virtdisk.nim");
	result = (&(*self).union1.ParentTimestamp);
	popFrame();
	return result;
}

static N_INLINE(void, ProviderSubtypeeq__bgrzULm3ow9cT20w3vIEESQ_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self, NI32 x) {
	nimfr_("ProviderSubtype=", "virtdisk.nim");
	nimln_(250, "virtdisk.nim");
	(*self).union1.ProviderSubtype = x;
	popFrame();
}

static N_INLINE(NI32, ProviderSubtype_Joz09b29clSWCfTIxYsFcA2A_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	NI32 result;
	nimfr_("ProviderSubtype", "virtdisk.nim");
	result = (NI32)0;
	nimln_(251, "virtdisk.nim");
	result = (*self).union1.ProviderSubtype;
	popFrame();
	return result;
}

static N_INLINE(NI32*, ProviderSubtype_8PKAjAKvPZOoNj6SSs4SkA_2virtdisk)(tyObject_GET_VIRTUAL_DISK_INFO_LaWjAEwqAwJynkZT3awRsQ* self) {
	NI32* result;
	nimfr_("ProviderSubtype", "virtdisk.nim");
	result = (NI32*)0;
	nimln_(252, "virtdisk.nim");
	result = (&(*self).union1.ProviderSubtype);
	popFrame();
	return result;
}

static N_INLINE(void, Version1eq__vTHQKsAiWWyNulATB6Ja9bgvirtdisk)(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ* self, tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg x) {
	nimfr_("Version1=", "virtdisk.nim");
	nimln_(253, "virtdisk.nim");
	(*self).union1.Version1 = x;
	popFrame();
}

static N_INLINE(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg, Version1_O8kWSa9b9avg5PIG4H3l9cEKQvirtdisk)(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ self) {
	tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg result;
	nimfr_("Version1", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(254, "virtdisk.nim");
	result = self.union1.Version1;
	popFrame();
	return result;
}

static N_INLINE(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg*, Version1_dQ0hU7EAxP49crCg0PT9bj9cAvirtdisk)(tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_LdbP1Ahb1Dv9b9cCGW7qOquQ* self) {
	tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg* result;
	nimfr_("Version1", "virtdisk.nim");
	result = (tyObject_MERGE_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_xbKsBS8BItK6p744T3U5vg*)0;
	nimln_(255, "virtdisk.nim");
	result = (&(*self).union1.Version1);
	popFrame();
	return result;
}

static N_INLINE(void, Version1eq__h1Cdqouwuk9blDa682nri1gvirtdisk)(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig* self, tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw x) {
	nimfr_("Version1=", "virtdisk.nim");
	nimln_(256, "virtdisk.nim");
	(*self).union1.Version1 = x;
	popFrame();
}

static N_INLINE(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw, Version1_9csLCfGlPuXUjf2C7MgV9a7Qvirtdisk)(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig self) {
	tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw result;
	nimfr_("Version1", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(257, "virtdisk.nim");
	result = self.union1.Version1;
	popFrame();
	return result;
}

static N_INLINE(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw*, Version1_sutWakQoz1i9cecMxYHrBVgvirtdisk)(tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_9a6VOpQZ5QmznONl9anLN2Ig* self) {
	tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw* result;
	nimfr_("Version1", "virtdisk.nim");
	result = (tyObject_OPEN_VIRTUAL_DISK_PARAMETERS_UNION1_Version1_3qbQQK2hVirpPlLNGAgqHw*)0;
	nimln_(258, "virtdisk.nim");
	result = (&(*self).union1.Version1);
	popFrame();
	return result;
}

static N_INLINE(void, ParentFilePatheq__JiFcFvJJbkCgdrDOUsyY6Avirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self, NU16* x) {
	nimfr_("ParentFilePath=", "virtdisk.nim");
	nimln_(259, "virtdisk.nim");
	(*self).union1.ParentFilePath = x;
	popFrame();
}

static N_INLINE(NU16*, ParentFilePath_hUPG8KU51aIa9bP4BUZosAgvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self) {
	NU16* result;
	nimfr_("ParentFilePath", "virtdisk.nim");
	result = (NU16*)0;
	nimln_(260, "virtdisk.nim");
	result = (*self).union1.ParentFilePath;
	popFrame();
	return result;
}

static N_INLINE(NU16**, ParentFilePath_9bJ8aqHG0kJ39ambSJIj9cwqwvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self) {
	NU16** result;
	nimfr_("ParentFilePath", "virtdisk.nim");
	result = (NU16**)0;
	nimln_(261, "virtdisk.nim");
	result = &(*self).union1.ParentFilePath;
	popFrame();
	return result;
}

static N_INLINE(void, UniqueIdentifiereq__er2lTyV9bgMHx9bpnqnnEEcAvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self, tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA x) {
	nimfr_("UniqueIdentifier=", "virtdisk.nim");
	nimln_(262, "virtdisk.nim");
	(*self).union1.UniqueIdentifier = x;
	popFrame();
}

static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA, UniqueIdentifier_rdwk9bD7N5tvkLJd2YI9bquQvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self) {
	tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA result;
	nimfr_("UniqueIdentifier", "virtdisk.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(263, "virtdisk.nim");
	result = (*self).union1.UniqueIdentifier;
	popFrame();
	return result;
}

static N_INLINE(tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*, UniqueIdentifier_zmjKmFd2lbJfLV0u4z2JZgvirtdisk)(tyObject_SET_VIRTUAL_DISK_INFO_Cp8d9bPG8T9aDtX1Ral5HYPg* self) {
	tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA* result;
	nimfr_("UniqueIdentifier", "virtdisk.nim");
	result = (tyObject_GUID_vR9aKCQzKs1RAi9cxPq9bGGlA*)0;
	nimln_(264, "virtdisk.nim");
	result = (&(*self).union1.UniqueIdentifier);
	popFrame();
	return result;
}

static N_INLINE(void, Version1Entrieseq__lk7DK9adiABH9aLDnLdKY0GQvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self, tyArray_lGFC8OrbT9aoaguRXzp9a2Ng x) {
	nimfr_("Version1Entries=", "virtdisk.nim");
	nimln_(265, "virtdisk.nim");
	memcpy((void*)(*self).union1.Version1Entries, (NIM_CONST void*)x, sizeof(tyArray_lGFC8OrbT9aoaguRXzp9a2Ng));
	popFrame();
}

static N_INLINE(void, Version1Entries_lOaSGX2GIiVJ8rfzwNastwvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self, tyArray_lGFC8OrbT9aoaguRXzp9a2Ng Result) {
	nimfr_("Version1Entries", "virtdisk.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	nimln_(266, "virtdisk.nim");
	memcpy((void*)Result, (NIM_CONST void*)(*self).union1.Version1Entries, sizeof(tyArray_lGFC8OrbT9aoaguRXzp9a2Ng));
	popFrame();
}

static N_INLINE(tyObject_STORAGE_DEPENDENCY_INFO_TYPE1_KFhqBDEARoPFAcbb6EBtGA*, Version1Entries_A0L0VRSVthssS8pH2x4LOwvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self) {
	tyObject_STORAGE_DEPENDENCY_INFO_TYPE1_KFhqBDEARoPFAcbb6EBtGA* result;
	nimfr_("Version1Entries", "virtdisk.nim");
	result = (tyObject_STORAGE_DEPENDENCY_INFO_TYPE1_KFhqBDEARoPFAcbb6EBtGA*)0;
	nimln_(267, "virtdisk.nim");
	result = (*self).union1.Version1Entries;
	popFrame();
	return result;
}

static N_INLINE(void, Version2Entrieseq__dgxyNnx8IB2KbumbyNAzfwvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self, tyArray_2a0W9b6WLiQYr2WITy7c4Dw x) {
	nimfr_("Version2Entries=", "virtdisk.nim");
	nimln_(268, "virtdisk.nim");
	memcpy((void*)(*self).union1.Version2Entries, (NIM_CONST void*)x, sizeof(tyArray_2a0W9b6WLiQYr2WITy7c4Dw));
	popFrame();
}

static N_INLINE(void, Version2Entries_mveQihddoxKAg9cMtWBAU9aAvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self, tyArray_2a0W9b6WLiQYr2WITy7c4Dw Result) {
	nimfr_("Version2Entries", "virtdisk.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	nimln_(269, "virtdisk.nim");
	memcpy((void*)Result, (NIM_CONST void*)(*self).union1.Version2Entries, sizeof(tyArray_2a0W9b6WLiQYr2WITy7c4Dw));
	popFrame();
}

static N_INLINE(tyObject_STORAGE_DEPENDENCY_INFO_TYPE2_vdD6RkSDrl1mE6NECHdrTQ*, Version2Entries_kLcQgb0hR2cQ0kY0BW1pywvirtdisk)(tyObject_STORAGE_DEPENDENCY_INFO_OT9buwBXwL2do8WUahtViZA* self) {
	tyObject_STORAGE_DEPENDENCY_INFO_TYPE2_vdD6RkSDrl1mE6NECHdrTQ* result;
	nimfr_("Version2Entries", "virtdisk.nim");
	result = (tyObject_STORAGE_DEPENDENCY_INFO_TYPE2_vdD6RkSDrl1mE6NECHdrTQ*)0;
	nimln_(270, "virtdisk.nim");
	result = (*self).union1.Version2Entries;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, winim_virtdiskInit000)(void) {
	nimfr_("virtdisk", "virtdisk.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, winim_virtdiskDatInit000)(void) {
if (!((TM_4Q3Fp3DyaliCi78oLMU1dw_2 = nimLoadLibrary((NimStringDesc*) &TM_4Q3Fp3DyaliCi78oLMU1dw_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_4Q3Fp3DyaliCi78oLMU1dw_5);
	Dl_303308_ = (tyProc_ZuTEyl9cg2rpd7xBbRhYjeQ) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "AttachVirtualDisk");
	Dl_303316_ = (tyProc_QIKLqykTE7dIrM9bFLwwJ8A) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "CompactVirtualDisk");
	Dl_303322_ = (tyProc_2hU715aCvdkAoU2UX7oCSg) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "CreateVirtualDisk");
	Dl_303333_ = (tyProc_mBVOPXmpGfUrrbA9a5K9cMbQ) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "DetachVirtualDisk");
	Dl_303338_ = (tyProc_If2FO4Wv8m84UknSxCB9a5A) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "ExpandVirtualDisk");
	Dl_303344_ = (tyProc_02vLxryyRhAvosORshlGuw) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "GetStorageDependencyInformation");
	Dl_303351_ = (tyProc_zNnG3Jjv1IBShy60Ti1mww) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "GetVirtualDiskInformation");
	Dl_303357_ = (tyProc_S4yGHUS9aGZMK59b9corBGr5w) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "GetVirtualDiskOperationProgress");
	Dl_303362_ = (tyProc_TQx9ajhr9bWjvgFt9cGET7y1Q) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "GetVirtualDiskPhysicalPath");
	Dl_303367_ = (tyProc_3P9aegprzS9aWzVPIG4iIMDQ) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "MergeVirtualDisk");
	Dl_303373_ = (tyProc_2EaxwQsemqru70jv9aS9bWXA) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "OpenVirtualDisk");
	Dl_303381_ = (tyProc_9cfs9cQDoLHV39bI5uZSvzC7w) nimGetProcAddr(TM_4Q3Fp3DyaliCi78oLMU1dw_2, "SetVirtualDiskInformation");
}

