/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   F:\nim\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IF:\nim\lib -o O:\nim\wnim\release\examples\nimcache\winim_wininet.o O:\nim\wnim\release\examples\nimcache\winim_wininet.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_SYSTEMTIME_q9bsrqEZlPrhj7CNuiTyxRA tyObject_SYSTEMTIME_q9bsrqEZlPrhj7CNuiTyxRA;
typedef struct tyObject_URL_COMPONENTSA_T0sOuVk9cp9bfuuus8QUoVyg tyObject_URL_COMPONENTSA_T0sOuVk9cp9bfuuus8QUoVyg;
typedef struct tyObject_URL_COMPONENTSW_RCAVYkbjqpqzbU3Tn5BETg tyObject_URL_COMPONENTSW_RCAVYkbjqpqzbU3Tn5BETg;
typedef struct tyObject_INTERNET_BUFFERSA_CGERgjOJGsTbGoD1cIRxhQ tyObject_INTERNET_BUFFERSA_CGERgjOJGsTbGoD1cIRxhQ;
typedef struct tyObject_INTERNET_BUFFERSW_bI6n0p5n5dTRTIjn7Rax1g tyObject_INTERNET_BUFFERSW_bI6n0p5n5dTRTIjn7Rax1g;
typedef struct tyObject_WIN32_FIND_DATAA_OhSrkM18OF56m9a9ai1Kcp2w tyObject_WIN32_FIND_DATAA_OhSrkM18OF56m9a9ai1Kcp2w;
typedef struct tyObject_WIN32_FIND_DATAW_3vgJKpSpYm04oR5zPMm5iw tyObject_WIN32_FIND_DATAW_3vgJKpSpYm04oR5zPMm5iw;
typedef struct tyObject_GOPHER_FIND_DATAA_ldu4TiK4becHbvmjWXESVA tyObject_GOPHER_FIND_DATAA_ldu4TiK4becHbvmjWXESVA;
typedef struct tyObject_GOPHER_FIND_DATAW_K0KjKs7kXTNRWPMt3QdoBg tyObject_GOPHER_FIND_DATAW_K0KjKs7kXTNRWPMt3QdoBg;
typedef struct tyObject_GOPHER_ATTRIBUTE_TYPE_bzo3DatS9bVUWf3T9aIwDPGA tyObject_GOPHER_ATTRIBUTE_TYPE_bzo3DatS9bVUWf3T9aIwDPGA;
typedef struct tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw;
typedef struct tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA;
typedef struct tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw;
typedef struct tyObject_INTERNET_CACHE_GROUP_INFOA_GHCVesFO3mB80gkX1uow9cw tyObject_INTERNET_CACHE_GROUP_INFOA_GHCVesFO3mB80gkX1uow9cw;
typedef struct tyObject_INTERNET_CACHE_GROUP_INFOW_6C2kFY9czvOMl9cEiWV4AViA tyObject_INTERNET_CACHE_GROUP_INFOW_6C2kFY9czvOMl9cEiWV4AViA;
typedef union tyObject_INTERNET_CACHE_ENTRY_INFOA_UNION1_SfhKWAPRTQnu8LXW0TApDw tyObject_INTERNET_CACHE_ENTRY_INFOA_UNION1_SfhKWAPRTQnu8LXW0TApDw;
typedef union tyObject_INTERNET_CACHE_ENTRY_INFOW_UNION1_CuV9b9aUmqeA1QYA9brfbWxaw tyObject_INTERNET_CACHE_ENTRY_INFOW_UNION1_CuV9b9aUmqeA1QYA9brfbWxaw;
typedef union tyObject_GOPHER_ATTRIBUTE_TYPE_AttributeType_ZPBULJmC7IREo8VRhoLwgw tyObject_GOPHER_ATTRIBUTE_TYPE_AttributeType_ZPBULJmC7IREo8VRhoLwgw;
typedef struct tyObject_GOPHER_ADMIN_ATTRIBUTE_TYPE_ro7DmVo9bhX25MRuOhh8j9aA tyObject_GOPHER_ADMIN_ATTRIBUTE_TYPE_ro7DmVo9bhX25MRuOhh8j9aA;
typedef struct tyObject_GOPHER_MOD_DATE_ATTRIBUTE_TYPE_FS9bVgyabqqmRtY54JoLNIg tyObject_GOPHER_MOD_DATE_ATTRIBUTE_TYPE_FS9bVgyabqqmRtY54JoLNIg;
typedef struct tyObject_GOPHER_TTL_ATTRIBUTE_TYPE_PqgcfaELLS9brzh1eCSQcCA tyObject_GOPHER_TTL_ATTRIBUTE_TYPE_PqgcfaELLS9brzh1eCSQcCA;
typedef struct tyObject_GOPHER_SCORE_ATTRIBUTE_TYPE_pgLJGj4fvszl4R1uKH6BSg tyObject_GOPHER_SCORE_ATTRIBUTE_TYPE_pgLJGj4fvszl4R1uKH6BSg;
typedef struct tyObject_GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE_f5uRFJRCZ43jKpedd78Yzg tyObject_GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE_f5uRFJRCZ43jKpedd78Yzg;
typedef struct tyObject_GOPHER_SITE_ATTRIBUTE_TYPE_jmUUia2x3NjTHiBtP8XGdA tyObject_GOPHER_SITE_ATTRIBUTE_TYPE_jmUUia2x3NjTHiBtP8XGdA;
typedef struct tyObject_GOPHER_ORGANIZATION_ATTRIBUTE_TYPE_7XalBLPX8qcFXKosHtH9azg tyObject_GOPHER_ORGANIZATION_ATTRIBUTE_TYPE_7XalBLPX8qcFXKosHtH9azg;
typedef struct tyObject_GOPHER_LOCATION_ATTRIBUTE_TYPE_S1bTa9cDjnCFYUDERq9cLnnw tyObject_GOPHER_LOCATION_ATTRIBUTE_TYPE_S1bTa9cDjnCFYUDERq9cLnnw;
typedef struct tyObject_GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE_JOYP9cPYRKobJ5Y2VVjTOvg tyObject_GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE_JOYP9cPYRKobJ5Y2VVjTOvg;
typedef struct tyObject_GOPHER_TIMEZONE_ATTRIBUTE_TYPE_FRLvXxkWfZ576bsQ3L9aPlA tyObject_GOPHER_TIMEZONE_ATTRIBUTE_TYPE_FRLvXxkWfZ576bsQ3L9aPlA;
typedef struct tyObject_GOPHER_PROVIDER_ATTRIBUTE_TYPE_9al7xeBHL2dWnesaZholckQ tyObject_GOPHER_PROVIDER_ATTRIBUTE_TYPE_9al7xeBHL2dWnesaZholckQ;
typedef struct tyObject_GOPHER_VERSION_ATTRIBUTE_TYPE_A5pwPmPzRVnGSr8JsEiT8w tyObject_GOPHER_VERSION_ATTRIBUTE_TYPE_A5pwPmPzRVnGSr8JsEiT8w;
typedef struct tyObject_GOPHER_ABSTRACT_ATTRIBUTE_TYPE_kJhVqKLWXitizBS7Rwf3KA tyObject_GOPHER_ABSTRACT_ATTRIBUTE_TYPE_kJhVqKLWXitizBS7Rwf3KA;
typedef struct tyObject_GOPHER_VIEW_ATTRIBUTE_TYPE_hUJcy61i3I9bJJwis6zQp9ag tyObject_GOPHER_VIEW_ATTRIBUTE_TYPE_hUJcy61i3I9bJJwis6zQp9ag;
typedef struct tyObject_GOPHER_VERONICA_ATTRIBUTE_TYPE_nfrvlTOumYXJb9cqdY9a8sHA tyObject_GOPHER_VERONICA_ATTRIBUTE_TYPE_nfrvlTOumYXJb9cqdY9a8sHA;
typedef struct tyObject_GOPHER_ASK_ATTRIBUTE_TYPE_eXuK9cJz79aVJXbFxC8Y9aG7w tyObject_GOPHER_ASK_ATTRIBUTE_TYPE_eXuK9cJz79aVJXbFxC8Y9aG7w;
typedef struct tyObject_GOPHER_UNKNOWN_ATTRIBUTE_TYPE_fpEvNaphzW9bG69cd9cJZuB4g tyObject_GOPHER_UNKNOWN_ATTRIBUTE_TYPE_fpEvNaphzW9bG69cd9cJZuB4g;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, tyProc_wK4s9a3X4xfFw44ptrAzVPA) (tyObject_SYSTEMTIME_q9bsrqEZlPrhj7CNuiTyxRA* pst, NI32 dwRFC, NCSTRING lpszTime, NI32 cbTime);
typedef N_STDCALL_PTR(NI32, tyProc_35C5Jy9bv719cLBXZdEji9aCg) (tyObject_SYSTEMTIME_q9bsrqEZlPrhj7CNuiTyxRA* pst, NI32 dwRFC, NU16* lpszTime, NI32 cbTime);
typedef N_STDCALL_PTR(NI32, tyProc_8b9cE9a9cOakDWDeOUBUvFg2w) (NCSTRING lpszTime, tyObject_SYSTEMTIME_q9bsrqEZlPrhj7CNuiTyxRA* pst, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_v6FU7HBc3TqIDHV4Fx5IOQ) (NU16* lpszTime, tyObject_SYSTEMTIME_q9bsrqEZlPrhj7CNuiTyxRA* pst, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_8ySzjH3QKQJWHuQDQ88Idg) (NCSTRING lpszUrl, NI32 dwUrlLength, NI32 dwFlags, tyObject_URL_COMPONENTSA_T0sOuVk9cp9bfuuus8QUoVyg* lpUrlComponents);
typedef N_STDCALL_PTR(NI32, tyProc_K4OzLFhLp6H1MEU0m007mA) (NU16* lpszUrl, NI32 dwUrlLength, NI32 dwFlags, tyObject_URL_COMPONENTSW_RCAVYkbjqpqzbU3Tn5BETg* lpUrlComponents);
typedef N_STDCALL_PTR(NI32, tyProc_rpUrQpyOs1IYdPeB4dXzaA) (tyObject_URL_COMPONENTSA_T0sOuVk9cp9bfuuus8QUoVyg* lpUrlComponents, NI32 dwFlags, NCSTRING lpszUrl, NI32* lpdwUrlLength);
typedef N_STDCALL_PTR(NI32, tyProc_g39bQdN20SIZOPT0oqNoTPQ) (tyObject_URL_COMPONENTSW_RCAVYkbjqpqzbU3Tn5BETg* lpUrlComponents, NI32 dwFlags, NU16* lpszUrl, NI32* lpdwUrlLength);
typedef N_STDCALL_PTR(NI32, tyProc_MiB7U6RjM3MCqqMLirNURw) (NCSTRING lpszUrl, NCSTRING lpszBuffer, NI32* lpdwBufferLength, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_NDE1Wz6MLFk5KS7JJEJ18w) (NU16* lpszUrl, NU16* lpszBuffer, NI32* lpdwBufferLength, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_UcZGhzu26aA9bJwPZnJ3K1A) (NCSTRING lpszBaseUrl, NCSTRING lpszRelativeUrl, NCSTRING lpszBuffer, NI32* lpdwBufferLength, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_WE0t5XxU0pEHgtwUGwCYug) (NU16* lpszBaseUrl, NU16* lpszRelativeUrl, NU16* lpszBuffer, NI32* lpdwBufferLength, NI32 dwFlags);
typedef N_STDCALL_PTR(void*, tyProc_yjp7kWDst33b4p4W0KvsXg) (NCSTRING lpszAgent, NI32 dwAccessType, NCSTRING lpszProxy, NCSTRING lpszProxyBypass, NI32 dwFlags);
typedef N_STDCALL_PTR(void*, tyProc_81VIzYkqwzDl7rl3af0pZg) (NU16* lpszAgent, NI32 dwAccessType, NU16* lpszProxy, NU16* lpszProxyBypass, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_ah5wcFv3UG20t2vgXBy0Fg) (void* hInternet);
typedef N_STDCALL_PTR(void*, tyProc_oCXddxrs9aklJE9bc2asK5EQ) (void* hInternet, NCSTRING lpszServerName, NU16 nServerPort, NCSTRING lpszUserName, NCSTRING lpszPassword, NI32 dwService, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_P2lHXOiBZr7SMt9b1gl6ptA) (void* hInternet, NU16* lpszServerName, NU16 nServerPort, NU16* lpszUserName, NU16* lpszPassword, NI32 dwService, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_Z2wy9bjX9cDNXj2fFBT2kcWA) (void* hInternet, NCSTRING lpszUrl, NCSTRING lpszHeaders, NI32 dwHeadersLength, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_k7gzG6e9b9bnzbZvYShWFTLg) (void* hInternet, NU16* lpszUrl, NU16* lpszHeaders, NI32 dwHeadersLength, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_mID4zaJ5rXbvlxUmzwPGLw) (void* hFile, void* lpBuffer, NI32 dwNumberOfBytesToRead, NI32* lpdwNumberOfBytesRead);
typedef N_STDCALL_PTR(NI32, tyProc_9aWznLiR5YCCrF53nsjUfGg) (void* hFile, tyObject_INTERNET_BUFFERSA_CGERgjOJGsTbGoD1cIRxhQ* lpBuffersOut, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_DHwEOkGuBcGhrfKi2seYRQ) (void* hFile, tyObject_INTERNET_BUFFERSW_bI6n0p5n5dTRTIjn7Rax1g* lpBuffersOut, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_d7MQpLTvlYs9aaBJS9cE16nw) (void* hFile, NI32 lDistanceToMove, void* pReserved, NI32 dwMoveMethod, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_xOJnQFQyW4yXVg660FSygg) (void* hFile, NI32* lpdwNumberOfBytesAvailable, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_wS8JrJMcfFBzgzuqJGOAAg) (void* hFind, void* lpvFindData);
typedef N_STDCALL_PTR(NI32, tyProc_p9acI9c9chaDF2CTXkYiH9bPlw) (void* hInternet, NI32 dwOption, void* lpBuffer, NI32* lpdwBufferLength);
typedef N_STDCALL_PTR(NI32, tyProc_OygtxCk9aDjhab6i7UhdJdQ) (void* hInternet, NI32 dwOption, void* lpBuffer, NI32 dwBufferLength);
typedef N_STDCALL_PTR(NI32, tyProc_TxuhRZrGfx2HNJbRLGdbvA) (void* hInternet, NI32 dwOption, void* lpBuffer, NI32 dwBufferLength, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_oo9c2maRM62Fyq6FOpmmHEA) (void* hInternet, NI* lphLockRequestInfo);
typedef N_STDCALL_PTR(NI32, tyProc_P13srMBg9b3d3yEV9aW4NCoA) (NI hLockRequestInfo);
typedef N_STDCALL_PTR(NI32, tyProc_wdLLm8TIuW9az9bTDFVD9aHlA) (NI32* lpdwError, NCSTRING lpszBuffer, NI32* lpdwBufferLength);
typedef N_STDCALL_PTR(NI32, tyProc_ghb0s1syaKEjHpgg9bpy5lA) (NI32* lpdwError, NU16* lpszBuffer, NI32* lpdwBufferLength);
typedef N_STDCALL_PTR(void, tyProc_gZROOZbNneomOVFWCu9cJfQ) (void* hInternet, NU64 dwContext, NI32 dwInternetStatus, void* lpvStatusInformation, NI32 dwStatusInformationLength);
typedef N_STDCALL_PTR(tyProc_gZROOZbNneomOVFWCu9cJfQ, tyProc_Dmq9b2yaUhM9bVc5PPuvIAPw) (void* hInternet, tyProc_gZROOZbNneomOVFWCu9cJfQ lpfnInternetCallback);
typedef N_STDCALL_PTR(void*, tyProc_m9c5iIvSrePZLE75MhxqrsA) (void* hConnect, NCSTRING lpszSearchFile, tyObject_WIN32_FIND_DATAA_OhSrkM18OF56m9a9ai1Kcp2w* lpFindFileData, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_pXd9cx04FDRRnxBxs9aoG2KA) (void* hConnect, NU16* lpszSearchFile, tyObject_WIN32_FIND_DATAW_3vgJKpSpYm04oR5zPMm5iw* lpFindFileData, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_51E0cFSg9bDNqNXb61cndfQ) (void* hConnect, NCSTRING lpszRemoteFile, NCSTRING lpszNewFile, NI32 fFailIfExists, NI32 dwFlagsAndAttributes, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_cAC5ip3WKhbUcKGbKG9aKWA) (void* hConnect, NU16* lpszRemoteFile, NU16* lpszNewFile, NI32 fFailIfExists, NI32 dwFlagsAndAttributes, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_kLND6E9bR7RhKtfVfD5OAxQ) (void* hConnect, NCSTRING lpszLocalFile, NCSTRING lpszNewRemoteFile, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_qjBREOMCyD2CvslzTsUgjg) (void* hConnect, NU16* lpszLocalFile, NU16* lpszNewRemoteFile, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_pYFEA6qdfZT1dGNrN639bCg) (void* hFtpSession, NCSTRING lpszRemoteFile, NU16* lpszNewFile, NI32 fFailIfExists, NI32 dwFlagsAndAttributes, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_c1IA1lj3yLt29c5iA4kDGeQ) (void* hFtpSession, NU16* lpszLocalFile, NCSTRING lpszNewRemoteFile, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_IBq5TENC0hs6XbsecLkH2g) (void* hConnect, NCSTRING lpszFileName);
typedef N_STDCALL_PTR(NI32, tyProc_zpIbd6qEt9a2fDaFRY6iS4A) (void* hConnect, NU16* lpszFileName);
typedef N_STDCALL_PTR(NI32, tyProc_4vvMuwAGLRwXgAi0Oe9cSZw) (void* hConnect, NCSTRING lpszExisting, NCSTRING lpszNew);
typedef N_STDCALL_PTR(NI32, tyProc_8kIgXqTQk0UfvD54m0PVUQ) (void* hConnect, NU16* lpszExisting, NU16* lpszNew);
typedef N_STDCALL_PTR(void*, tyProc_43y7vyIDoqTJOPjL9aMMGXw) (void* hConnect, NCSTRING lpszFileName, NI32 dwAccess, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_OMHy9aHn1HP29cDAD8ta0f2g) (void* hConnect, NU16* lpszFileName, NI32 dwAccess, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_1X1qFDGqVZtr0FNdqKPPyQ) (void* hConnect, NCSTRING lpszCurrentDirectory, NI32* lpdwCurrentDirectory);
typedef N_STDCALL_PTR(NI32, tyProc_xjWfD6JL61TePeffRuJvNw) (void* hConnect, NU16* lpszCurrentDirectory, NI32* lpdwCurrentDirectory);
typedef N_STDCALL_PTR(NI32, tyProc_eex9c6ByuGqswZB801XCW6Q) (void* hConnect, NI32 fExpectResponse, NI32 dwFlags, NCSTRING lpszCommand, NU64 dwContext, void** phFtpCommand);
typedef N_STDCALL_PTR(NI32, tyProc_qhfr9b7vEKBVn9c2TQ1MDiWw) (void* hConnect, NI32 fExpectResponse, NI32 dwFlags, NU16* lpszCommand, NU64 dwContext, void** phFtpCommand);
typedef N_STDCALL_PTR(NI32, tyProc_hmzku9acjH9bP9a9cEj2lReMig) (void* hFile, NI32* lpdwFileSizeHigh);
typedef N_STDCALL_PTR(NI32, tyProc_Qi9aHNdTw0bNfAccvLdvMzQ) (NCSTRING lpszHost, NU16 nServerPort, NCSTRING lpszDisplayString, NCSTRING lpszSelectorString, NI32 dwGopherType, NCSTRING lpszLocator, NI32* lpdwBufferLength);
typedef N_STDCALL_PTR(NI32, tyProc_bA9bcKawSwUkcYVGbYDAukQ) (NU16* lpszHost, NU16 nServerPort, NU16* lpszDisplayString, NU16* lpszSelectorString, NI32 dwGopherType, NU16* lpszLocator, NI32* lpdwBufferLength);
typedef N_STDCALL_PTR(NI32, tyProc_8e3Pc9bDmk0y4L2XN8nKBfQ) (NCSTRING lpszLocator, NI32* lpdwGopherType);
typedef N_STDCALL_PTR(NI32, tyProc_gxkCuWdOe6iDXo10iWshaA) (NU16* lpszLocator, NI32* lpdwGopherType);
typedef N_STDCALL_PTR(void*, tyProc_UDiFTVUA9bAB9a9aGX9cGZW6eQ) (void* hConnect, NCSTRING lpszLocator, NCSTRING lpszSearchString, tyObject_GOPHER_FIND_DATAA_ldu4TiK4becHbvmjWXESVA* lpFindData, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_9c19a9bNwSc8b5r3ShY5BDukg) (void* hConnect, NU16* lpszLocator, NU16* lpszSearchString, tyObject_GOPHER_FIND_DATAW_K0KjKs7kXTNRWPMt3QdoBg* lpFindData, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_519bNrk9bPAHJy9bD0U81xSjA) (void* hConnect, NCSTRING lpszLocator, NCSTRING lpszView, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_IotBtDeviRFtvznQvFtb9aQ) (void* hConnect, NU16* lpszLocator, NU16* lpszView, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_5a26KHdRQiJ0FnNPKZQijQ) (tyObject_GOPHER_ATTRIBUTE_TYPE_bzo3DatS9bVUWf3T9aIwDPGA* lpAttributeInfo, NI32 dwError);
typedef N_STDCALL_PTR(NI32, tyProc_v2Qau7p9clikFEJPznyWp9aQ) (void* hConnect, NCSTRING lpszLocator, NCSTRING lpszAttributeName, NU8* lpBuffer, NI32 dwBufferLength, NI32* lpdwCharactersReturned, tyProc_5a26KHdRQiJ0FnNPKZQijQ lpfnEnumerator, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_yocxcokGSKFQxaqqVdalgg) (void* hConnect, NU16* lpszLocator, NU16* lpszAttributeName, NU8* lpBuffer, NI32 dwBufferLength, NI32* lpdwCharactersReturned, tyProc_5a26KHdRQiJ0FnNPKZQijQ lpfnEnumerator, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_39bvRsZ2NWyNmTxldSroDpg) (void* hConnect, NCSTRING lpszVerb, NCSTRING lpszObjectName, NCSTRING lpszVersion, NCSTRING lpszReferrer, NCSTRING* lplpszAcceptTypes, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(void*, tyProc_jYD3iltB9cC1EDm3YFqpWQw) (void* hConnect, NU16* lpszVerb, NU16* lpszObjectName, NU16* lpszVersion, NU16* lpszReferrer, NU16** lplpszAcceptTypes, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_n7uqtUBZA9cah5cMlbu9aYvw) (void* hRequest, NCSTRING lpszHeaders, NI32 dwHeadersLength, NI32 dwModifiers);
typedef N_STDCALL_PTR(NI32, tyProc_GDtgFkYwnC8EJx7gppgoYg) (void* hRequest, NU16* lpszHeaders, NI32 dwHeadersLength, NI32 dwModifiers);
typedef N_STDCALL_PTR(NI32, tyProc_g7sgbb4KeafvPq9cLmwRcpw) (void* hRequest, NCSTRING lpszHeaders, NI32 dwHeadersLength, void* lpOptional, NI32 dwOptionalLength);
typedef N_STDCALL_PTR(NI32, tyProc_WUiVDobayRMfSL5cBE4TnQ) (void* hRequest, NU16* lpszHeaders, NI32 dwHeadersLength, void* lpOptional, NI32 dwOptionalLength);
typedef N_STDCALL_PTR(NI32, tyProc_vSwYi5jbo0kfRe9ciLWbVuA) (void* hRequest, tyObject_INTERNET_BUFFERSA_CGERgjOJGsTbGoD1cIRxhQ* lpBuffersIn, tyObject_INTERNET_BUFFERSA_CGERgjOJGsTbGoD1cIRxhQ* lpBuffersOut, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_DK4rtfuwEr1Jwgpf9aFxYng) (void* hRequest, tyObject_INTERNET_BUFFERSW_bI6n0p5n5dTRTIjn7Rax1g* lpBuffersIn, tyObject_INTERNET_BUFFERSW_bI6n0p5n5dTRTIjn7Rax1g* lpBuffersOut, NI32 dwFlags, NU64 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc_QE3D0vERbcDUZ3vh8kM53w) (void* hRequest, NI32 dwInfoLevel, void* lpBuffer, NI32* lpdwBufferLength, NI32* lpdwIndex);
typedef N_STDCALL_PTR(NI32, tyProc_uHbNDtUHhLpn9ayW9alFCA1g) (NCSTRING lpszUrl, NCSTRING lpszCookieName, NCSTRING lpszCookieData);
typedef N_STDCALL_PTR(NI32, tyProc_TZyzM64ehR6MYFFuadIvRw) (NU16* lpszUrl, NU16* lpszCookieName, NU16* lpszCookieData);
typedef N_STDCALL_PTR(NI32, tyProc_llTOQ9bz6AdtOIqBq7OtlYA) (NCSTRING lpszUrl, NCSTRING lpszCookieName, NCSTRING lpszCookieData, NI32* lpdwSize);
typedef N_STDCALL_PTR(NI32, tyProc_VoxY9bI1PG6msz4ykdSNJZA) (NU16* lpszUrl, NU16* lpszCookieName, NU16* lpszCookieData, NI32* lpdwSize);
typedef N_STDCALL_PTR(NI32, tyProc_m5kaRwJiiF9bAxwGY3ksKDw) (NCSTRING lpszUrl, NCSTRING lpszCookieName, NCSTRING lpszCookieData, NI32 dwFlags, NU64 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_T9cy1IWeW7pZ7m2cZdvkX1A) (NU16* lpszUrl, NU16* lpszCookieName, NU16* lpszCookieData, NI32 dwFlags, NU64 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_rOfJfVVcWJ4OiS8z0Dct3w) (NCSTRING lpszUrl, NCSTRING lpszCookieName, NCSTRING lpszCookieData, NI32* lpdwSize, NI32 dwFlags, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_NZ1LgKIViXnB9byV3PmBXSw) (NU16* lpszUrl, NU16* lpszCookieName, NU16* lpszCookieData, NI32* lpdwSize, NI32 dwFlags, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_78ER49aUeWMW9b9c9aDqn5uqBg) (NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_npwuIjepzLxnErJxDI15Bw) (NCSTRING lpszUrl, NI32 dwFlags, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_C2HPPnPs38qWChg6HAUbKQ) (NU16* lpszUrl, NI32 dwFlags, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_IJ8vvlYbVRxpIZFy4xyteg) (void* hRequest, NI32 dwResultCode);
typedef N_STDCALL_PTR(NI32, tyProc_V5ObZeuO9a1Jj3umz39cGLJA) (NI hWnd, void* hRequest, NI32 dwError, NI32 dwFlags, void** lppvData);
typedef N_STDCALL_PTR(NI32, tyProc_cAT3HCJ3BlnK47CHaJExzg) (NI hWnd, NCSTRING szUrlPrev, NCSTRING szUrlNew, NI32 bPost);
typedef N_STDCALL_PTR(NI32, tyProc_CWEdM7t4AIIGMHwMzG2F4A) (NI hWnd, NU16* szUrlPrev, NU16* szUrlNew, NI32 bPost);
typedef N_STDCALL_PTR(NI32, tyProc_Rgp6n1s0KykPQupsOwW01A) (NCSTRING lpszUrlName, NI32 dwExpectedFileSize, NCSTRING lpszFileExtension, NCSTRING lpszFileName, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_wj9aPLjX9cs71aKYqXtbq9b9cg) (NU16* lpszUrlName, NI32 dwExpectedFileSize, NU16* lpszFileExtension, NU16* lpszFileName, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_sroQuCsif34Jckj50zHinQ) (NCSTRING lpszUrlName, NCSTRING lpszLocalFileName, tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ExpireTime, tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastModifiedTime, NI32 CacheEntryType, NU8* lpHeaderInfo, NI32 dwHeaderSize, NCSTRING lpszFileExtension, NCSTRING lpszOriginalUrl);
typedef N_STDCALL_PTR(NI32, tyProc_QTEfuhI4ZvHYcE5ptxgJJQ) (NU16* lpszUrlName, NU16* lpszLocalFileName, tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ExpireTime, tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastModifiedTime, NI32 CacheEntryType, NU16* lpszHeaderInfo, NI32 dwHeaders, NU16* lpszFileExtension, NU16* lpszOriginalUrl);
typedef N_STDCALL_PTR(NI32, tyProc_V1DwSfF9cF1FJkID9bg8xajw) (NCSTRING lpszUrlName, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpCacheEntryInfo, NI32* lpcbCacheEntryInfo, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_1BV4zcCrUPN9amuao4lDaUA) (NU16* lpszUrlName, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpCacheEntryInfo, NI32* lpcbCacheEntryInfo, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_80L3Z6UegUoaV03fstCgIA) (NCSTRING lpszUrlName, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_YMWms6jt9axreas9bJGMtTMA) (NU16* lpszUrlName, NI32 dwReserved);
typedef N_STDCALL_PTR(NI, tyProc_xjQPX6Ok4btsdPJAz1LtZA) (NCSTRING lpszUrlName, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpCacheEntryInfo, NI32* lpcbCacheEntryInfo, NI32 fRandomRead, NI32 dwReserved);
typedef N_STDCALL_PTR(NI, tyProc_XlKzC6ac7y6uN9b3dZ0laEg) (NU16* lpszUrlName, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpCacheEntryInfo, NI32* lpcbCacheEntryInfo, NI32 fRandomRead, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_EmyS3bz8dwyBVVC5PvwCDA) (NI hUrlCacheStream, NI32 dwLocation, void* lpBuffer, NI32* lpdwLen, NI32 Reserved);
typedef N_STDCALL_PTR(NI32, tyProc_FprzxJFfqQdWyyGxiUsmeQ) (NI hUrlCacheStream, NI32 Reserved);
typedef N_STDCALL_PTR(NI32, tyProc_Bx8co4J5c39a74b3mGUlFzg) (NCSTRING lpszUrlName, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpCacheEntryInfo, NI32* lpcbCacheEntryInfo);
typedef N_STDCALL_PTR(NI32, tyProc_lQNu1EXmL3nhDsEpkJPe9cA) (NU16* lpszUrlName, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpCacheEntryInfo, NI32* lpcbCacheEntryInfo);
typedef N_STDCALL_PTR(NI, tyProc_gbtYhwh5ObtDGJPrINBU4A) (NI32 dwFlags, NI32 dwFilter, void* lpSearchCondition, NI32 dwSearchCondition, NI64* lpGroupId, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_o89cqX00gc5sX4oMqC2WegA) (NI hFind, NI64* lpGroupId, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_9b0Xc3PcaOW9cvn9bmwCs9bv6w) (NI64 gid, NI32 dwFlags, NI32 dwAttributes, tyObject_INTERNET_CACHE_GROUP_INFOA_GHCVesFO3mB80gkX1uow9cw* lpGroupInfo, NI32* lpdwGroupInfo, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_LHbwrYhcZAmmJxgsHSzCYw) (NI64 gid, NI32 dwFlags, NI32 dwAttributes, tyObject_INTERNET_CACHE_GROUP_INFOW_6C2kFY9czvOMl9cEiWV4AViA* lpGroupInfo, NI32* lpdwGroupInfo, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_LuANEz54Su9ccSmaGzXAOng) (NI64 gid, NI32 dwFlags, NI32 dwAttributes, tyObject_INTERNET_CACHE_GROUP_INFOA_GHCVesFO3mB80gkX1uow9cw* lpGroupInfo, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_LuY1thm5hcscDVU4hhpPIg) (NI64 gid, NI32 dwFlags, NI32 dwAttributes, tyObject_INTERNET_CACHE_GROUP_INFOW_6C2kFY9czvOMl9cEiWV4AViA* lpGroupInfo, void* lpReserved);
typedef N_STDCALL_PTR(NI64, tyProc_HIgFc5j5zgC05A9cNOLmg1w) (NI32 dwFlags, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_XR9a4iQtkL6QDQ19cu9a4jjFw) (NI64 GroupId, NI32 dwFlags, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_ygQs32zsiSaVDY9ayRdUYAQ) (NCSTRING lpszUrl, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpCacheEntryInfo, NI32* lpcbCacheEntryInfo, NCSTRING lpszRedirectUrl, NI32* lpcbRedirectUrl, void* lpReserved, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_toL9bm9c5Ne65smhfALHcgvQ) (NU16* lpszUrl, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpCacheEntryInfo, NI32* lpcbCacheEntryInfo, NU16* lpszRedirectUrl, NI32* lpcbRedirectUrl, void* lpReserved, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_yZNtE6xy5rcp3DDq71kwfA) (NCSTRING lpszUrlName, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpCacheEntryInfo, NI32 dwFieldControl);
typedef N_STDCALL_PTR(NI32, tyProc_9cmnBYbNnkS9cL9czR6krANEw) (NU16* lpszUrlName, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpCacheEntryInfo, NI32 dwFieldControl);
typedef N_STDCALL_PTR(NI32, tyProc_ow4WOYsmQgsldqeza9a88FQ) (NCSTRING lpszUrlName, NI32 dwFlags, NI64 GroupId, NU8* pbGroupAttributes, NI32 cbGroupAttributes, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_LZ8LGGS31Ukf6ie2ByFP5A) (NU16* lpszUrlName, NI32 dwFlags, NI64 GroupId, NU8* pbGroupAttributes, NI32 cbGroupAttributes, void* lpReserved);
typedef N_STDCALL_PTR(NI, tyProc_dyrC4pmz4aGBO9cVfBWs78A) (NCSTRING lpszUrlSearchPattern, NI32 dwFlags, NI32 dwFilter, NI64 GroupId, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpFirstCacheEntryInfo, NI32* lpcbEntryInfo, void* lpGroupAttributes, NI32* lpcbGroupAttributes, void* lpReserved);
typedef N_STDCALL_PTR(NI, tyProc_AY6Qc5d734LzFhiAgm9axVw) (NU16* lpszUrlSearchPattern, NI32 dwFlags, NI32 dwFilter, NI64 GroupId, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpFirstCacheEntryInfo, NI32* lpcbEntryInfo, void* lpGroupAttributes, NI32* lpcbGroupAttributes, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_dHTNA0REpG3mOWtsGFcK8w) (NI hEnumHandle, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpNextCacheEntryInfo, NI32* lpcbEntryInfo, void* lpGroupAttributes, NI32* lpcbGroupAttributes, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc_qsTAIqdcfIGlFGdYgXooNA) (NI hEnumHandle, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpNextCacheEntryInfo, NI32* lpcbEntryInfo, void* lpGroupAttributes, NI32* lpcbGroupAttributes, void* lpReserved);
typedef N_STDCALL_PTR(NI, tyProc_yR2gT9bBADC9agQOWOq1p37w) (NCSTRING lpszUrlSearchPattern, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpFirstCacheEntryInfo, NI32* lpcbCacheEntryInfo);
typedef N_STDCALL_PTR(NI, tyProc_Zsw3dpID8Cjlt9bKyI9a54ow) (NU16* lpszUrlSearchPattern, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpFirstCacheEntryInfo, NI32* lpcbCacheEntryInfo);
typedef N_STDCALL_PTR(NI32, tyProc_WhceJN4pt1xcC2McMkmcPA) (NI hEnumHandle, tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* lpNextCacheEntryInfo, NI32* lpcbCacheEntryInfo);
typedef N_STDCALL_PTR(NI32, tyProc_77LKcxVxiaK4AiK9cXtLTJg) (NI hEnumHandle, tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* lpNextCacheEntryInfo, NI32* lpcbCacheEntryInfo);
typedef N_STDCALL_PTR(NI32, tyProc_yDWFOVVnqizp6M8D0kw9aVg) (NCSTRING lpszUrlName);
typedef N_STDCALL_PTR(NI32, tyProc_uaa3EeY5nSKYBlex9baos2Q) (NU16* lpszUrlName);
typedef N_STDCALL_PTR(NI32, tyProc_KT0ShBylKYFzgT40PxF9cMA) (NI hwndParent, NCSTRING lpszConnectoid, NI32 dwFlags, NU64* lpdwConnection, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_wETW8F3oXFBPxGEMIUi3Ng) (NI hwndParent, NU16* lpszConnectoid, NI32 dwFlags, NU64* lpdwConnection, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_8Dmqcbk03OzAn3kfUB9bxMQ) (NU64 dwConnection, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_9bBHkTLQdF9bS6fgH9aW9bGHzA) (NCSTRING lpszURL, NI hwndParent, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_e0CAZd8piR1d8Mhnmhxx4w) (NU16* lpszURL, NI hwndParent, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_EIsGESqSaU8RXWpB8OLznw) (NI32 dwFlags, NI hwndParent);
typedef N_STDCALL_PTR(NI32, tyProc_ZMYPd7BOgovcnmXIh85rUQ) (NI32* lpdwFlags, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_KWKTc68BOA9bxliOrmvtkBA) (NI32* lpdwFlags, NCSTRING lpszConnectionName, NI32 dwBufLen, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_qLN066ctYabzFgMmWhVe9aw) (NI32* lpdwFlags, NU16* lpszConnectionName, NI32 dwBufLen, NI32 dwReserved);
typedef N_STDCALL_PTR(NI32, tyProc_8zxj8hHidNnmY39a2Qmks1A) (NU16* pszChallengeInfo, NU16* pwszRealm, NU16* pwszTarget, NU8* pbHexHash);
typedef N_STDCALL_PTR(NI32, tyProc_9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI32, tyProc_WobKuZ6sZlpLjWq0eOmh1g) (NCSTRING pszSiteName, NI32* pcSiteNameSize, NI32* pdwDecision, NI32 dwIndex);
typedef N_STDCALL_PTR(NI32, tyProc_dR7tySHCzyuUHadQKu9abuw) (NU16* pszSiteName, NI32* pcSiteNameSize, NI32* pdwDecision, NI32 dwIndex);
typedef N_STDCALL_PTR(NI32, tyProc_nwLuJEx85btRONfl5MaiPg) (NI32 dwZone, NI32 dwType, NI32 dwTemplate, NU16* pszPreference);
typedef N_STDCALL_PTR(NI32, tyProc_BsIhBpJUmxj9cbJv0LXh3eA) (NI32 dwZone, NI32 dwType, NI32* pdwTemplate, NU16* pszBuffer, NI32* pdwBufferLength);
struct tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw {
NI32 dwLowDateTime;
NI32 dwHighDateTime;
};
union tyObject_INTERNET_CACHE_ENTRY_INFOA_UNION1_SfhKWAPRTQnu8LXW0TApDw {
NI32 dwReserved;
NI32 dwExemptDelta;
};
struct tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA {
NI32 dwStructSize;
NCSTRING lpszSourceUrlName;
NCSTRING lpszLocalFileName;
NI32 CacheEntryType;
NI32 dwUseCount;
NI32 dwHitRate;
NI32 dwSizeLow;
NI32 dwSizeHigh;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastModifiedTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ExpireTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastAccessTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastSyncTime;
NCSTRING lpHeaderInfo;
NI32 dwHeaderInfoSize;
NCSTRING lpszFileExtension;
tyObject_INTERNET_CACHE_ENTRY_INFOA_UNION1_SfhKWAPRTQnu8LXW0TApDw union1;
};
union tyObject_INTERNET_CACHE_ENTRY_INFOW_UNION1_CuV9b9aUmqeA1QYA9brfbWxaw {
NI32 dwReserved;
NI32 dwExemptDelta;
};
struct tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw {
NI32 dwStructSize;
NU16* lpszSourceUrlName;
NU16* lpszLocalFileName;
NI32 CacheEntryType;
NI32 dwUseCount;
NI32 dwHitRate;
NI32 dwSizeLow;
NI32 dwSizeHigh;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastModifiedTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ExpireTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastAccessTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastSyncTime;
NU16* lpHeaderInfo;
NI32 dwHeaderInfoSize;
NU16* lpszFileExtension;
tyObject_INTERNET_CACHE_ENTRY_INFOW_UNION1_CuV9b9aUmqeA1QYA9brfbWxaw union1;
};
struct tyObject_SYSTEMTIME_q9bsrqEZlPrhj7CNuiTyxRA {
NU16 wYear;
NU16 wMonth;
NU16 wDayOfWeek;
NU16 wDay;
NU16 wHour;
NU16 wMinute;
NU16 wSecond;
NU16 wMilliseconds;
};
struct tyObject_URL_COMPONENTSA_T0sOuVk9cp9bfuuus8QUoVyg {
NI32 dwStructSize;
NCSTRING lpszScheme;
NI32 dwSchemeLength;
NI32 nScheme;
NCSTRING lpszHostName;
NI32 dwHostNameLength;
NU16 nPort;
NCSTRING lpszUserName;
NI32 dwUserNameLength;
NCSTRING lpszPassword;
NI32 dwPasswordLength;
NCSTRING lpszUrlPath;
NI32 dwUrlPathLength;
NCSTRING lpszExtraInfo;
NI32 dwExtraInfoLength;
};
struct tyObject_URL_COMPONENTSW_RCAVYkbjqpqzbU3Tn5BETg {
NI32 dwStructSize;
NU16* lpszScheme;
NI32 dwSchemeLength;
NI32 nScheme;
NU16* lpszHostName;
NI32 dwHostNameLength;
NU16 nPort;
NU16* lpszUserName;
NI32 dwUserNameLength;
NU16* lpszPassword;
NI32 dwPasswordLength;
NU16* lpszUrlPath;
NI32 dwUrlPathLength;
NU16* lpszExtraInfo;
NI32 dwExtraInfoLength;
};
struct tyObject_INTERNET_BUFFERSA_CGERgjOJGsTbGoD1cIRxhQ {
NI32 dwStructSize;
tyObject_INTERNET_BUFFERSA_CGERgjOJGsTbGoD1cIRxhQ* Next;
NCSTRING lpcszHeader;
NI32 dwHeadersLength;
NI32 dwHeadersTotal;
void* lpvBuffer;
NI32 dwBufferLength;
NI32 dwBufferTotal;
NI32 dwOffsetLow;
NI32 dwOffsetHigh;
};
struct tyObject_INTERNET_BUFFERSW_bI6n0p5n5dTRTIjn7Rax1g {
NI32 dwStructSize;
tyObject_INTERNET_BUFFERSW_bI6n0p5n5dTRTIjn7Rax1g* Next;
NU16* lpcszHeader;
NI32 dwHeadersLength;
NI32 dwHeadersTotal;
void* lpvBuffer;
NI32 dwBufferLength;
NI32 dwBufferTotal;
NI32 dwOffsetLow;
NI32 dwOffsetHigh;
};
typedef NIM_CHAR tyArray_9aRCo8XKKgPYTiahX008zvw[260];
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
struct tyObject_WIN32_FIND_DATAA_OhSrkM18OF56m9a9ai1Kcp2w {
NI32 dwFileAttributes;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ftCreationTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ftLastAccessTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ftLastWriteTime;
NI32 nFileSizeHigh;
NI32 nFileSizeLow;
NI32 dwReserved0;
NI32 dwReserved1;
tyArray_9aRCo8XKKgPYTiahX008zvw cFileName;
tyArray_NSMq3FMCIrS8gSbyinBZ8w cAlternateFileName;
};
typedef NU16 tyArray_B9ccXAGccyBTjUnYtvGvTuA[260];
typedef NU16 tyArray_yOwOOC4dN9bCtkPWTQKIsoQ[14];
struct tyObject_WIN32_FIND_DATAW_3vgJKpSpYm04oR5zPMm5iw {
NI32 dwFileAttributes;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ftCreationTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ftLastAccessTime;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw ftLastWriteTime;
NI32 nFileSizeHigh;
NI32 nFileSizeLow;
NI32 dwReserved0;
NI32 dwReserved1;
tyArray_B9ccXAGccyBTjUnYtvGvTuA cFileName;
tyArray_yOwOOC4dN9bCtkPWTQKIsoQ cAlternateFileName;
};
typedef NIM_CHAR tyArray_4249al09aeC68W9cvqMnjIYOA[129];
typedef NIM_CHAR tyArray_vDVCrMGRHrBxbl82oZdNLA[654];
struct tyObject_GOPHER_FIND_DATAA_ldu4TiK4becHbvmjWXESVA {
tyArray_4249al09aeC68W9cvqMnjIYOA DisplayString;
NI32 GopherType;
NI32 SizeLow;
NI32 SizeHigh;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastModificationTime;
tyArray_vDVCrMGRHrBxbl82oZdNLA Locator;
};
typedef NU16 tyArray_e7SPLyXW7Y9a6uYYvSkxaEw[129];
typedef NU16 tyArray_xdUlkCabVCuiRJw8c9cY7Jw[654];
struct tyObject_GOPHER_FIND_DATAW_K0KjKs7kXTNRWPMt3QdoBg {
tyArray_e7SPLyXW7Y9a6uYYvSkxaEw DisplayString;
NI32 GopherType;
NI32 SizeLow;
NI32 SizeHigh;
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw LastModificationTime;
tyArray_xdUlkCabVCuiRJw8c9cY7Jw Locator;
};
struct tyObject_GOPHER_ADMIN_ATTRIBUTE_TYPE_ro7DmVo9bhX25MRuOhh8j9aA {
NU16* Comment;
NU16* EmailAddress;
};
struct tyObject_GOPHER_MOD_DATE_ATTRIBUTE_TYPE_FS9bVgyabqqmRtY54JoLNIg {
tyObject_FILETIME_wAXHPksCwulPpluwoCJlxw DateAndTime;
};
struct tyObject_GOPHER_TTL_ATTRIBUTE_TYPE_PqgcfaELLS9brzh1eCSQcCA {
NI32 Ttl;
};
struct tyObject_GOPHER_SCORE_ATTRIBUTE_TYPE_pgLJGj4fvszl4R1uKH6BSg {
NI32 Score;
};
struct tyObject_GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE_f5uRFJRCZ43jKpedd78Yzg {
NI32 LowerBound;
NI32 UpperBound;
};
struct tyObject_GOPHER_SITE_ATTRIBUTE_TYPE_jmUUia2x3NjTHiBtP8XGdA {
NU16* Site;
};
struct tyObject_GOPHER_ORGANIZATION_ATTRIBUTE_TYPE_7XalBLPX8qcFXKosHtH9azg {
NU16* Organization;
};
struct tyObject_GOPHER_LOCATION_ATTRIBUTE_TYPE_S1bTa9cDjnCFYUDERq9cLnnw {
NU16* Location;
};
struct tyObject_GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE_JOYP9cPYRKobJ5Y2VVjTOvg {
NI32 DegreesNorth;
NI32 MinutesNorth;
NI32 SecondsNorth;
NI32 DegreesEast;
NI32 MinutesEast;
NI32 SecondsEast;
};
struct tyObject_GOPHER_TIMEZONE_ATTRIBUTE_TYPE_FRLvXxkWfZ576bsQ3L9aPlA {
NI32 Zone;
};
struct tyObject_GOPHER_PROVIDER_ATTRIBUTE_TYPE_9al7xeBHL2dWnesaZholckQ {
NU16* Provider;
};
struct tyObject_GOPHER_VERSION_ATTRIBUTE_TYPE_A5pwPmPzRVnGSr8JsEiT8w {
NU16* Version;
};
struct tyObject_GOPHER_ABSTRACT_ATTRIBUTE_TYPE_kJhVqKLWXitizBS7Rwf3KA {
NU16* ShortAbstract;
NU16* AbstractFile;
};
struct tyObject_GOPHER_VIEW_ATTRIBUTE_TYPE_hUJcy61i3I9bJJwis6zQp9ag {
NU16* ContentType;
NU16* Language;
NI32 Size;
};
struct tyObject_GOPHER_VERONICA_ATTRIBUTE_TYPE_nfrvlTOumYXJb9cqdY9a8sHA {
NI32 TreeWalk;
};
struct tyObject_GOPHER_ASK_ATTRIBUTE_TYPE_eXuK9cJz79aVJXbFxC8Y9aG7w {
NU16* QuestionType;
NU16* QuestionText;
};
struct tyObject_GOPHER_UNKNOWN_ATTRIBUTE_TYPE_fpEvNaphzW9bG69cd9cJZuB4g {
NU16* Text;
};
union tyObject_GOPHER_ATTRIBUTE_TYPE_AttributeType_ZPBULJmC7IREo8VRhoLwgw {
tyObject_GOPHER_ADMIN_ATTRIBUTE_TYPE_ro7DmVo9bhX25MRuOhh8j9aA Admin;
tyObject_GOPHER_MOD_DATE_ATTRIBUTE_TYPE_FS9bVgyabqqmRtY54JoLNIg ModDate;
tyObject_GOPHER_TTL_ATTRIBUTE_TYPE_PqgcfaELLS9brzh1eCSQcCA Ttl;
tyObject_GOPHER_SCORE_ATTRIBUTE_TYPE_pgLJGj4fvszl4R1uKH6BSg Score;
tyObject_GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE_f5uRFJRCZ43jKpedd78Yzg ScoreRange;
tyObject_GOPHER_SITE_ATTRIBUTE_TYPE_jmUUia2x3NjTHiBtP8XGdA Site;
tyObject_GOPHER_ORGANIZATION_ATTRIBUTE_TYPE_7XalBLPX8qcFXKosHtH9azg Organization;
tyObject_GOPHER_LOCATION_ATTRIBUTE_TYPE_S1bTa9cDjnCFYUDERq9cLnnw Location;
tyObject_GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE_JOYP9cPYRKobJ5Y2VVjTOvg GeographicalLocation;
tyObject_GOPHER_TIMEZONE_ATTRIBUTE_TYPE_FRLvXxkWfZ576bsQ3L9aPlA TimeZone;
tyObject_GOPHER_PROVIDER_ATTRIBUTE_TYPE_9al7xeBHL2dWnesaZholckQ Provider;
tyObject_GOPHER_VERSION_ATTRIBUTE_TYPE_A5pwPmPzRVnGSr8JsEiT8w Version;
tyObject_GOPHER_ABSTRACT_ATTRIBUTE_TYPE_kJhVqKLWXitizBS7Rwf3KA Abstract;
tyObject_GOPHER_VIEW_ATTRIBUTE_TYPE_hUJcy61i3I9bJJwis6zQp9ag View;
tyObject_GOPHER_VERONICA_ATTRIBUTE_TYPE_nfrvlTOumYXJb9cqdY9a8sHA Veronica;
tyObject_GOPHER_ASK_ATTRIBUTE_TYPE_eXuK9cJz79aVJXbFxC8Y9aG7w Ask;
tyObject_GOPHER_UNKNOWN_ATTRIBUTE_TYPE_fpEvNaphzW9bG69cd9cJZuB4g Unknown;
};
struct tyObject_GOPHER_ATTRIBUTE_TYPE_bzo3DatS9bVUWf3T9aIwDPGA {
NI32 CategoryId;
NI32 AttributeId;
tyObject_GOPHER_ATTRIBUTE_TYPE_AttributeType_ZPBULJmC7IREo8VRhoLwgw AttributeType;
};
typedef NI32 tyArray_7pxmxukJp9aDJpjDIdzM2gw[4];
typedef NIM_CHAR tyArray_0iqO1Ae7c0hdX5sR5ADMsw[120];
struct tyObject_INTERNET_CACHE_GROUP_INFOA_GHCVesFO3mB80gkX1uow9cw {
NI32 dwGroupSize;
NI32 dwGroupFlags;
NI32 dwGroupType;
NI32 dwDiskUsage;
NI32 dwDiskQuota;
tyArray_7pxmxukJp9aDJpjDIdzM2gw dwOwnerStorage;
tyArray_0iqO1Ae7c0hdX5sR5ADMsw szGroupName;
};
typedef NU16 tyArray_SqalBuwKn0TeiJFMZvPJ9bw[120];
struct tyObject_INTERNET_CACHE_GROUP_INFOW_6C2kFY9czvOMl9cEiWV4AViA {
NI32 dwGroupSize;
NI32 dwGroupFlags;
NI32 dwGroupType;
NI32 dwDiskUsage;
NI32 dwDiskQuota;
tyArray_7pxmxukJp9aDJpjDIdzM2gw dwOwnerStorage;
tyArray_SqalBuwKn0TeiJFMZvPJ9bw szGroupName;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, dwReservedeq__jB3kKURywRfmTOC854Zy2gwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self, NI32 x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI32, dwReserved_CiOS4nprwIygdH1nJcWfTQwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self);
static N_INLINE(NI32*, dwReserved_szBjtMQh5Z5f1rYCFPV5Dwwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self);
static N_INLINE(void, dwExemptDeltaeq__jB3kKURywRfmTOC854Zy2g_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self, NI32 x);
static N_INLINE(NI32, dwExemptDelta_CiOS4nprwIygdH1nJcWfTQ_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self);
static N_INLINE(NI32*, dwExemptDelta_szBjtMQh5Z5f1rYCFPV5Dw_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self);
static N_INLINE(void, dwReservedeq__OiTlrBw9bxDmu9azeH9b7jagQwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self, NI32 x);
static N_INLINE(NI32, dwReserved_yD9bbhQVF1uvCVcgto2VAigwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self);
static N_INLINE(NI32*, dwReserved_pkb9areluoS2ulqeEN6QEogwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self);
static N_INLINE(void, dwExemptDeltaeq__OiTlrBw9bxDmu9azeH9b7jagQ_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self, NI32 x);
static N_INLINE(NI32, dwExemptDelta_yD9bbhQVF1uvCVcgto2VAig_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self);
static N_INLINE(NI32*, dwExemptDelta_pkb9areluoS2ulqeEN6QEog_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self);
static void* TM_yWPAFHUOrlH9cmyrd88npxA_2;
tyProc_wK4s9a3X4xfFw44ptrAzVPA Dl_415708_;
tyProc_35C5Jy9bv719cLBXZdEji9aCg Dl_415715_;
tyProc_8b9cE9a9cOakDWDeOUBUvFg2w Dl_415722_;
tyProc_v6FU7HBc3TqIDHV4Fx5IOQ Dl_415728_;
tyProc_8ySzjH3QKQJWHuQDQ88Idg Dl_415734_;
tyProc_K4OzLFhLp6H1MEU0m007mA Dl_415740_;
tyProc_rpUrQpyOs1IYdPeB4dXzaA Dl_415746_;
tyProc_g39bQdN20SIZOPT0oqNoTPQ Dl_415752_;
tyProc_MiB7U6RjM3MCqqMLirNURw Dl_415758_;
tyProc_NDE1Wz6MLFk5KS7JJEJ18w Dl_415764_;
tyProc_UcZGhzu26aA9bJwPZnJ3K1A Dl_415770_;
tyProc_WE0t5XxU0pEHgtwUGwCYug Dl_415777_;
tyProc_yjp7kWDst33b4p4W0KvsXg Dl_415784_;
tyProc_81VIzYkqwzDl7rl3af0pZg Dl_415791_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_415798_;
tyProc_oCXddxrs9aklJE9bc2asK5EQ Dl_415801_;
tyProc_P2lHXOiBZr7SMt9b1gl6ptA Dl_415811_;
tyProc_Z2wy9bjX9cDNXj2fFBT2kcWA Dl_415821_;
tyProc_k7gzG6e9b9bnzbZvYShWFTLg Dl_415829_;
tyProc_mID4zaJ5rXbvlxUmzwPGLw Dl_415837_;
tyProc_9aWznLiR5YCCrF53nsjUfGg Dl_415843_;
tyProc_DHwEOkGuBcGhrfKi2seYRQ Dl_415849_;
tyProc_d7MQpLTvlYs9aaBJS9cE16nw Dl_415855_;
tyProc_mID4zaJ5rXbvlxUmzwPGLw Dl_415862_;
tyProc_xOJnQFQyW4yXVg660FSygg Dl_415868_;
tyProc_wS8JrJMcfFBzgzuqJGOAAg Dl_415874_;
tyProc_wS8JrJMcfFBzgzuqJGOAAg Dl_415878_;
tyProc_p9acI9c9chaDF2CTXkYiH9bPlw Dl_415882_;
tyProc_p9acI9c9chaDF2CTXkYiH9bPlw Dl_415888_;
tyProc_OygtxCk9aDjhab6i7UhdJdQ Dl_415894_;
tyProc_OygtxCk9aDjhab6i7UhdJdQ Dl_415900_;
tyProc_TxuhRZrGfx2HNJbRLGdbvA Dl_415906_;
tyProc_TxuhRZrGfx2HNJbRLGdbvA Dl_415913_;
tyProc_oo9c2maRM62Fyq6FOpmmHEA Dl_415920_;
tyProc_P13srMBg9b3d3yEV9aW4NCoA Dl_415925_;
tyProc_wdLLm8TIuW9az9bTDFVD9aHlA Dl_415928_;
tyProc_ghb0s1syaKEjHpgg9bpy5lA Dl_415933_;
tyProc_Dmq9b2yaUhM9bVc5PPuvIAPw Dl_415938_;
tyProc_Dmq9b2yaUhM9bVc5PPuvIAPw Dl_415942_;
tyProc_m9c5iIvSrePZLE75MhxqrsA Dl_415946_;
tyProc_pXd9cx04FDRRnxBxs9aoG2KA Dl_415953_;
tyProc_51E0cFSg9bDNqNXb61cndfQ Dl_415960_;
tyProc_cAC5ip3WKhbUcKGbKG9aKWA Dl_415969_;
tyProc_kLND6E9bR7RhKtfVfD5OAxQ Dl_415978_;
tyProc_qjBREOMCyD2CvslzTsUgjg Dl_415985_;
tyProc_pYFEA6qdfZT1dGNrN639bCg Dl_415992_;
tyProc_c1IA1lj3yLt29c5iA4kDGeQ Dl_416001_;
tyProc_IBq5TENC0hs6XbsecLkH2g Dl_416008_;
tyProc_zpIbd6qEt9a2fDaFRY6iS4A Dl_416012_;
tyProc_4vvMuwAGLRwXgAi0Oe9cSZw Dl_416016_;
tyProc_8kIgXqTQk0UfvD54m0PVUQ Dl_416021_;
tyProc_43y7vyIDoqTJOPjL9aMMGXw Dl_416026_;
tyProc_OMHy9aHn1HP29cDAD8ta0f2g Dl_416033_;
tyProc_IBq5TENC0hs6XbsecLkH2g Dl_416040_;
tyProc_zpIbd6qEt9a2fDaFRY6iS4A Dl_416044_;
tyProc_IBq5TENC0hs6XbsecLkH2g Dl_416048_;
tyProc_zpIbd6qEt9a2fDaFRY6iS4A Dl_416052_;
tyProc_IBq5TENC0hs6XbsecLkH2g Dl_416056_;
tyProc_zpIbd6qEt9a2fDaFRY6iS4A Dl_416060_;
tyProc_1X1qFDGqVZtr0FNdqKPPyQ Dl_416064_;
tyProc_xjWfD6JL61TePeffRuJvNw Dl_416069_;
tyProc_eex9c6ByuGqswZB801XCW6Q Dl_416074_;
tyProc_qhfr9b7vEKBVn9c2TQ1MDiWw Dl_416083_;
tyProc_hmzku9acjH9bP9a9cEj2lReMig Dl_416092_;
tyProc_Qi9aHNdTw0bNfAccvLdvMzQ Dl_416096_;
tyProc_bA9bcKawSwUkcYVGbYDAukQ Dl_416105_;
tyProc_8e3Pc9bDmk0y4L2XN8nKBfQ Dl_416114_;
tyProc_gxkCuWdOe6iDXo10iWshaA Dl_416118_;
tyProc_UDiFTVUA9bAB9a9aGX9cGZW6eQ Dl_416122_;
tyProc_9c19a9bNwSc8b5r3ShY5BDukg Dl_416130_;
tyProc_519bNrk9bPAHJy9bD0U81xSjA Dl_416138_;
tyProc_IotBtDeviRFtvznQvFtb9aQ Dl_416145_;
tyProc_v2Qau7p9clikFEJPznyWp9aQ Dl_416152_;
tyProc_yocxcokGSKFQxaqqVdalgg Dl_416162_;
tyProc_39bvRsZ2NWyNmTxldSroDpg Dl_416172_;
tyProc_jYD3iltB9cC1EDm3YFqpWQw Dl_416183_;
tyProc_n7uqtUBZA9cah5cMlbu9aYvw Dl_416194_;
tyProc_GDtgFkYwnC8EJx7gppgoYg Dl_416200_;
tyProc_g7sgbb4KeafvPq9cLmwRcpw Dl_416206_;
tyProc_WUiVDobayRMfSL5cBE4TnQ Dl_416213_;
tyProc_vSwYi5jbo0kfRe9ciLWbVuA Dl_416220_;
tyProc_DK4rtfuwEr1Jwgpf9aFxYng Dl_416227_;
tyProc_9aWznLiR5YCCrF53nsjUfGg Dl_416234_;
tyProc_DHwEOkGuBcGhrfKi2seYRQ Dl_416240_;
tyProc_QE3D0vERbcDUZ3vh8kM53w Dl_416246_;
tyProc_QE3D0vERbcDUZ3vh8kM53w Dl_416253_;
tyProc_uHbNDtUHhLpn9ayW9alFCA1g Dl_416260_;
tyProc_TZyzM64ehR6MYFFuadIvRw Dl_416265_;
tyProc_llTOQ9bz6AdtOIqBq7OtlYA Dl_416270_;
tyProc_VoxY9bI1PG6msz4ykdSNJZA Dl_416276_;
tyProc_m5kaRwJiiF9bAxwGY3ksKDw Dl_416282_;
tyProc_T9cy1IWeW7pZ7m2cZdvkX1A Dl_416289_;
tyProc_rOfJfVVcWJ4OiS8z0Dct3w Dl_416296_;
tyProc_NZ1LgKIViXnB9byV3PmBXSw Dl_416304_;
tyProc_78ER49aUeWMW9b9c9aDqn5uqBg Dl_416312_;
tyProc_npwuIjepzLxnErJxDI15Bw Dl_416315_;
tyProc_C2HPPnPs38qWChg6HAUbKQ Dl_416320_;
tyProc_IJ8vvlYbVRxpIZFy4xyteg Dl_416325_;
tyProc_V5ObZeuO9a1Jj3umz39cGLJA Dl_416329_;
tyProc_cAT3HCJ3BlnK47CHaJExzg Dl_416337_;
tyProc_CWEdM7t4AIIGMHwMzG2F4A Dl_416343_;
tyProc_Rgp6n1s0KykPQupsOwW01A Dl_416349_;
tyProc_wj9aPLjX9cs71aKYqXtbq9b9cg Dl_416356_;
tyProc_sroQuCsif34Jckj50zHinQ Dl_416363_;
tyProc_QTEfuhI4ZvHYcE5ptxgJJQ Dl_416374_;
tyProc_V1DwSfF9cF1FJkID9bg8xajw Dl_416385_;
tyProc_1BV4zcCrUPN9amuao4lDaUA Dl_416391_;
tyProc_80L3Z6UegUoaV03fstCgIA Dl_416397_;
tyProc_YMWms6jt9axreas9bJGMtTMA Dl_416401_;
tyProc_xjQPX6Ok4btsdPJAz1LtZA Dl_416405_;
tyProc_XlKzC6ac7y6uN9b3dZ0laEg Dl_416412_;
tyProc_EmyS3bz8dwyBVVC5PvwCDA Dl_416419_;
tyProc_FprzxJFfqQdWyyGxiUsmeQ Dl_416426_;
tyProc_Bx8co4J5c39a74b3mGUlFzg Dl_416430_;
tyProc_lQNu1EXmL3nhDsEpkJPe9cA Dl_416435_;
tyProc_gbtYhwh5ObtDGJPrINBU4A Dl_416440_;
tyProc_o89cqX00gc5sX4oMqC2WegA Dl_416449_;
tyProc_9b0Xc3PcaOW9cvn9bmwCs9bv6w Dl_416455_;
tyProc_LHbwrYhcZAmmJxgsHSzCYw Dl_416463_;
tyProc_LuANEz54Su9ccSmaGzXAOng Dl_416471_;
tyProc_LuY1thm5hcscDVU4hhpPIg Dl_416478_;
tyProc_HIgFc5j5zgC05A9cNOLmg1w Dl_416485_;
tyProc_XR9a4iQtkL6QDQ19cu9a4jjFw Dl_416489_;
tyProc_ygQs32zsiSaVDY9ayRdUYAQ Dl_416494_;
tyProc_toL9bm9c5Ne65smhfALHcgvQ Dl_416503_;
tyProc_yZNtE6xy5rcp3DDq71kwfA Dl_416512_;
tyProc_9cmnBYbNnkS9cL9czR6krANEw Dl_416517_;
tyProc_ow4WOYsmQgsldqeza9a88FQ Dl_416522_;
tyProc_LZ8LGGS31Ukf6ie2ByFP5A Dl_416530_;
tyProc_dyrC4pmz4aGBO9cVfBWs78A Dl_416538_;
tyProc_AY6Qc5d734LzFhiAgm9axVw Dl_416549_;
tyProc_dHTNA0REpG3mOWtsGFcK8w Dl_416560_;
tyProc_qsTAIqdcfIGlFGdYgXooNA Dl_416568_;
tyProc_yR2gT9bBADC9agQOWOq1p37w Dl_416576_;
tyProc_Zsw3dpID8Cjlt9bKyI9a54ow Dl_416581_;
tyProc_WhceJN4pt1xcC2McMkmcPA Dl_416586_;
tyProc_77LKcxVxiaK4AiK9cXtLTJg Dl_416591_;
tyProc_P13srMBg9b3d3yEV9aW4NCoA Dl_416596_;
tyProc_yDWFOVVnqizp6M8D0kw9aVg Dl_416599_;
tyProc_uaa3EeY5nSKYBlex9baos2Q Dl_416602_;
tyProc_KT0ShBylKYFzgT40PxF9cMA Dl_416605_;
tyProc_wETW8F3oXFBPxGEMIUi3Ng Dl_416613_;
tyProc_8Dmqcbk03OzAn3kfUB9bxMQ Dl_416621_;
tyProc_9bBHkTLQdF9bS6fgH9aW9bGHzA Dl_416625_;
tyProc_e0CAZd8piR1d8Mhnmhxx4w Dl_416630_;
tyProc_EIsGESqSaU8RXWpB8OLznw Dl_416635_;
tyProc_78ER49aUeWMW9b9c9aDqn5uqBg Dl_416639_;
tyProc_ZMYPd7BOgovcnmXIh85rUQ Dl_416642_;
tyProc_KWKTc68BOA9bxliOrmvtkBA Dl_416646_;
tyProc_qLN066ctYabzFgMmWhVe9aw Dl_416652_;
tyProc_78ER49aUeWMW9b9c9aDqn5uqBg Dl_416658_;
tyProc_npwuIjepzLxnErJxDI15Bw Dl_416661_;
tyProc_8zxj8hHidNnmY39a2Qmks1A Dl_416666_;
tyProc_npwuIjepzLxnErJxDI15Bw Dl_416672_;
tyProc_C2HPPnPs38qWChg6HAUbKQ Dl_416677_;
tyProc_80L3Z6UegUoaV03fstCgIA Dl_416682_;
tyProc_YMWms6jt9axreas9bJGMtTMA Dl_416686_;
tyProc_8e3Pc9bDmk0y4L2XN8nKBfQ Dl_416690_;
tyProc_gxkCuWdOe6iDXo10iWshaA Dl_416695_;
tyProc_9bXer9a4ps9aSGctILcxWReVw Dl_416700_;
tyProc_WobKuZ6sZlpLjWq0eOmh1g Dl_416702_;
tyProc_dR7tySHCzyuUHadQKu9abuw Dl_416710_;
tyProc_nwLuJEx85btRONfl5MaiPg Dl_416718_;
tyProc_BsIhBpJUmxj9cbJv0LXh3eA Dl_416724_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyProc_K4OzLFhLp6H1MEU0m007mA Dl_416831_;
tyProc_g39bQdN20SIZOPT0oqNoTPQ Dl_416837_;
tyProc_NDE1Wz6MLFk5KS7JJEJ18w Dl_416843_;
tyProc_WE0t5XxU0pEHgtwUGwCYug Dl_416849_;
tyProc_81VIzYkqwzDl7rl3af0pZg Dl_416856_;
tyProc_P2lHXOiBZr7SMt9b1gl6ptA Dl_416863_;
tyProc_k7gzG6e9b9bnzbZvYShWFTLg Dl_416873_;
tyProc_DHwEOkGuBcGhrfKi2seYRQ Dl_416881_;
tyProc_wS8JrJMcfFBzgzuqJGOAAg Dl_416887_;
tyProc_p9acI9c9chaDF2CTXkYiH9bPlw Dl_416891_;
tyProc_OygtxCk9aDjhab6i7UhdJdQ Dl_416897_;
tyProc_TxuhRZrGfx2HNJbRLGdbvA Dl_416903_;
tyProc_ghb0s1syaKEjHpgg9bpy5lA Dl_416910_;
tyProc_pXd9cx04FDRRnxBxs9aoG2KA Dl_416915_;
tyProc_cAC5ip3WKhbUcKGbKG9aKWA Dl_416922_;
tyProc_qjBREOMCyD2CvslzTsUgjg Dl_416931_;
tyProc_zpIbd6qEt9a2fDaFRY6iS4A Dl_416938_;
tyProc_8kIgXqTQk0UfvD54m0PVUQ Dl_416942_;
tyProc_OMHy9aHn1HP29cDAD8ta0f2g Dl_416947_;
tyProc_zpIbd6qEt9a2fDaFRY6iS4A Dl_416954_;
tyProc_zpIbd6qEt9a2fDaFRY6iS4A Dl_416958_;
tyProc_zpIbd6qEt9a2fDaFRY6iS4A Dl_416962_;
tyProc_xjWfD6JL61TePeffRuJvNw Dl_416966_;
tyProc_qhfr9b7vEKBVn9c2TQ1MDiWw Dl_416971_;
tyProc_bA9bcKawSwUkcYVGbYDAukQ Dl_416980_;
tyProc_gxkCuWdOe6iDXo10iWshaA Dl_416989_;
tyProc_9c19a9bNwSc8b5r3ShY5BDukg Dl_416993_;
tyProc_IotBtDeviRFtvznQvFtb9aQ Dl_417001_;
tyProc_yocxcokGSKFQxaqqVdalgg Dl_417008_;
tyProc_jYD3iltB9cC1EDm3YFqpWQw Dl_417018_;
tyProc_GDtgFkYwnC8EJx7gppgoYg Dl_417029_;
tyProc_WUiVDobayRMfSL5cBE4TnQ Dl_417035_;
tyProc_DK4rtfuwEr1Jwgpf9aFxYng Dl_417042_;
tyProc_DHwEOkGuBcGhrfKi2seYRQ Dl_417049_;
tyProc_QE3D0vERbcDUZ3vh8kM53w Dl_417055_;
tyProc_TZyzM64ehR6MYFFuadIvRw Dl_417062_;
tyProc_VoxY9bI1PG6msz4ykdSNJZA Dl_417067_;
tyProc_T9cy1IWeW7pZ7m2cZdvkX1A Dl_417073_;
tyProc_NZ1LgKIViXnB9byV3PmBXSw Dl_417080_;
tyProc_C2HPPnPs38qWChg6HAUbKQ Dl_417088_;
tyProc_wj9aPLjX9cs71aKYqXtbq9b9cg Dl_417093_;
tyProc_QTEfuhI4ZvHYcE5ptxgJJQ Dl_417100_;
tyProc_1BV4zcCrUPN9amuao4lDaUA Dl_417111_;
tyProc_YMWms6jt9axreas9bJGMtTMA Dl_417117_;
tyProc_XlKzC6ac7y6uN9b3dZ0laEg Dl_417121_;
tyProc_lQNu1EXmL3nhDsEpkJPe9cA Dl_417128_;
tyProc_LHbwrYhcZAmmJxgsHSzCYw Dl_417133_;
tyProc_LuY1thm5hcscDVU4hhpPIg Dl_417141_;
tyProc_toL9bm9c5Ne65smhfALHcgvQ Dl_417148_;
tyProc_9cmnBYbNnkS9cL9czR6krANEw Dl_417157_;
tyProc_AY6Qc5d734LzFhiAgm9axVw Dl_417162_;
tyProc_qsTAIqdcfIGlFGdYgXooNA Dl_417173_;
tyProc_Zsw3dpID8Cjlt9bKyI9a54ow Dl_417181_;
tyProc_77LKcxVxiaK4AiK9cXtLTJg Dl_417186_;
tyProc_YMWms6jt9axreas9bJGMtTMA Dl_417191_;
tyProc_gxkCuWdOe6iDXo10iWshaA Dl_417195_;
tyProc_dR7tySHCzyuUHadQKu9abuw Dl_417200_;
tyProc_35C5Jy9bv719cLBXZdEji9aCg Dl_417208_;
tyProc_v6FU7HBc3TqIDHV4Fx5IOQ Dl_417215_;
tyProc_Dmq9b2yaUhM9bVc5PPuvIAPw Dl_417221_;
tyProc_CWEdM7t4AIIGMHwMzG2F4A Dl_417225_;
tyProc_wETW8F3oXFBPxGEMIUi3Ng Dl_417231_;
tyProc_e0CAZd8piR1d8Mhnmhxx4w Dl_417239_;
tyProc_uaa3EeY5nSKYBlex9baos2Q Dl_417244_;
tyProc_LZ8LGGS31Ukf6ie2ByFP5A Dl_417247_;
tyProc_C2HPPnPs38qWChg6HAUbKQ Dl_417255_;
tyProc_qLN066ctYabzFgMmWhVe9aw Dl_417260_;
STRING_LITERAL(TM_yWPAFHUOrlH9cmyrd88npxA_4, "wininet", 7);
STRING_LITERAL(TM_yWPAFHUOrlH9cmyrd88npxA_5, "wininet", 7);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, dwReservedeq__jB3kKURywRfmTOC854Zy2gwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self, NI32 x) {
	nimfr_("dwReserved=", "wininet.nim");
	nimln_(1255, "wininet.nim");
	(*self).union1.dwReserved = x;
	popFrame();
}

static N_INLINE(NI32, dwReserved_CiOS4nprwIygdH1nJcWfTQwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self) {
	NI32 result;
	nimfr_("dwReserved", "wininet.nim");
	result = (NI32)0;
	nimln_(1256, "wininet.nim");
	result = (*self).union1.dwReserved;
	popFrame();
	return result;
}

static N_INLINE(NI32*, dwReserved_szBjtMQh5Z5f1rYCFPV5Dwwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self) {
	NI32* result;
	nimfr_("dwReserved", "wininet.nim");
	result = (NI32*)0;
	nimln_(1257, "wininet.nim");
	result = (&(*self).union1.dwReserved);
	popFrame();
	return result;
}

static N_INLINE(void, dwExemptDeltaeq__jB3kKURywRfmTOC854Zy2g_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self, NI32 x) {
	nimfr_("dwExemptDelta=", "wininet.nim");
	nimln_(1258, "wininet.nim");
	(*self).union1.dwExemptDelta = x;
	popFrame();
}

static N_INLINE(NI32, dwExemptDelta_CiOS4nprwIygdH1nJcWfTQ_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self) {
	NI32 result;
	nimfr_("dwExemptDelta", "wininet.nim");
	result = (NI32)0;
	nimln_(1259, "wininet.nim");
	result = (*self).union1.dwExemptDelta;
	popFrame();
	return result;
}

static N_INLINE(NI32*, dwExemptDelta_szBjtMQh5Z5f1rYCFPV5Dw_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOA_N2M9amA9avwup1aBggIsBHAA* self) {
	NI32* result;
	nimfr_("dwExemptDelta", "wininet.nim");
	result = (NI32*)0;
	nimln_(1260, "wininet.nim");
	result = (&(*self).union1.dwExemptDelta);
	popFrame();
	return result;
}

static N_INLINE(void, dwReservedeq__OiTlrBw9bxDmu9azeH9b7jagQwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self, NI32 x) {
	nimfr_("dwReserved=", "wininet.nim");
	nimln_(1261, "wininet.nim");
	(*self).union1.dwReserved = x;
	popFrame();
}

static N_INLINE(NI32, dwReserved_yD9bbhQVF1uvCVcgto2VAigwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self) {
	NI32 result;
	nimfr_("dwReserved", "wininet.nim");
	result = (NI32)0;
	nimln_(1262, "wininet.nim");
	result = (*self).union1.dwReserved;
	popFrame();
	return result;
}

static N_INLINE(NI32*, dwReserved_pkb9areluoS2ulqeEN6QEogwininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self) {
	NI32* result;
	nimfr_("dwReserved", "wininet.nim");
	result = (NI32*)0;
	nimln_(1263, "wininet.nim");
	result = (&(*self).union1.dwReserved);
	popFrame();
	return result;
}

static N_INLINE(void, dwExemptDeltaeq__OiTlrBw9bxDmu9azeH9b7jagQ_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self, NI32 x) {
	nimfr_("dwExemptDelta=", "wininet.nim");
	nimln_(1264, "wininet.nim");
	(*self).union1.dwExemptDelta = x;
	popFrame();
}

static N_INLINE(NI32, dwExemptDelta_yD9bbhQVF1uvCVcgto2VAig_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self) {
	NI32 result;
	nimfr_("dwExemptDelta", "wininet.nim");
	result = (NI32)0;
	nimln_(1265, "wininet.nim");
	result = (*self).union1.dwExemptDelta;
	popFrame();
	return result;
}

static N_INLINE(NI32*, dwExemptDelta_pkb9areluoS2ulqeEN6QEog_2wininet)(tyObject_INTERNET_CACHE_ENTRY_INFOW_67OTnXWNVGoFke6tNL9bdFw* self) {
	NI32* result;
	nimfr_("dwExemptDelta", "wininet.nim");
	result = (NI32*)0;
	nimln_(1266, "wininet.nim");
	result = (&(*self).union1.dwExemptDelta);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, winim_wininetInit000)(void) {
	nimfr_("wininet", "wininet.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, winim_wininetDatInit000)(void) {
if (!((TM_yWPAFHUOrlH9cmyrd88npxA_2 = nimLoadLibrary((NimStringDesc*) &TM_yWPAFHUOrlH9cmyrd88npxA_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_yWPAFHUOrlH9cmyrd88npxA_5);
	Dl_415708_ = (tyProc_wK4s9a3X4xfFw44ptrAzVPA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetTimeFromSystemTimeA");
	Dl_415715_ = (tyProc_35C5Jy9bv719cLBXZdEji9aCg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetTimeFromSystemTimeW");
	Dl_415722_ = (tyProc_8b9cE9a9cOakDWDeOUBUvFg2w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetTimeToSystemTimeA");
	Dl_415728_ = (tyProc_v6FU7HBc3TqIDHV4Fx5IOQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetTimeToSystemTimeW");
	Dl_415734_ = (tyProc_8ySzjH3QKQJWHuQDQ88Idg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCrackUrlA");
	Dl_415740_ = (tyProc_K4OzLFhLp6H1MEU0m007mA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCrackUrlW");
	Dl_415746_ = (tyProc_rpUrQpyOs1IYdPeB4dXzaA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCreateUrlA");
	Dl_415752_ = (tyProc_g39bQdN20SIZOPT0oqNoTPQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCreateUrlW");
	Dl_415758_ = (tyProc_MiB7U6RjM3MCqqMLirNURw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCanonicalizeUrlA");
	Dl_415764_ = (tyProc_NDE1Wz6MLFk5KS7JJEJ18w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCanonicalizeUrlW");
	Dl_415770_ = (tyProc_UcZGhzu26aA9bJwPZnJ3K1A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCombineUrlA");
	Dl_415777_ = (tyProc_WE0t5XxU0pEHgtwUGwCYug) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCombineUrlW");
	Dl_415784_ = (tyProc_yjp7kWDst33b4p4W0KvsXg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetOpenA");
	Dl_415791_ = (tyProc_81VIzYkqwzDl7rl3af0pZg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetOpenW");
	Dl_415798_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCloseHandle");
	Dl_415801_ = (tyProc_oCXddxrs9aklJE9bc2asK5EQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetConnectA");
	Dl_415811_ = (tyProc_P2lHXOiBZr7SMt9b1gl6ptA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetConnectW");
	Dl_415821_ = (tyProc_Z2wy9bjX9cDNXj2fFBT2kcWA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetOpenUrlA");
	Dl_415829_ = (tyProc_k7gzG6e9b9bnzbZvYShWFTLg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetOpenUrlW");
	Dl_415837_ = (tyProc_mID4zaJ5rXbvlxUmzwPGLw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetReadFile");
	Dl_415843_ = (tyProc_9aWznLiR5YCCrF53nsjUfGg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetReadFileExA");
	Dl_415849_ = (tyProc_DHwEOkGuBcGhrfKi2seYRQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetReadFileExW");
	Dl_415855_ = (tyProc_d7MQpLTvlYs9aaBJS9cE16nw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetFilePointer");
	Dl_415862_ = (tyProc_mID4zaJ5rXbvlxUmzwPGLw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetWriteFile");
	Dl_415868_ = (tyProc_xOJnQFQyW4yXVg660FSygg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetQueryDataAvailable");
	Dl_415874_ = (tyProc_wS8JrJMcfFBzgzuqJGOAAg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetFindNextFileA");
	Dl_415878_ = (tyProc_wS8JrJMcfFBzgzuqJGOAAg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetFindNextFileW");
	Dl_415882_ = (tyProc_p9acI9c9chaDF2CTXkYiH9bPlw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetQueryOptionA");
	Dl_415888_ = (tyProc_p9acI9c9chaDF2CTXkYiH9bPlw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetQueryOptionW");
	Dl_415894_ = (tyProc_OygtxCk9aDjhab6i7UhdJdQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetOptionA");
	Dl_415900_ = (tyProc_OygtxCk9aDjhab6i7UhdJdQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetOptionW");
	Dl_415906_ = (tyProc_TxuhRZrGfx2HNJbRLGdbvA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetOptionExA");
	Dl_415913_ = (tyProc_TxuhRZrGfx2HNJbRLGdbvA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetOptionExW");
	Dl_415920_ = (tyProc_oo9c2maRM62Fyq6FOpmmHEA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetLockRequestFile");
	Dl_415925_ = (tyProc_P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetUnlockRequestFile");
	Dl_415928_ = (tyProc_wdLLm8TIuW9az9bTDFVD9aHlA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetLastResponseInfoA");
	Dl_415933_ = (tyProc_ghb0s1syaKEjHpgg9bpy5lA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetLastResponseInfoW");
	Dl_415938_ = (tyProc_Dmq9b2yaUhM9bVc5PPuvIAPw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetStatusCallbackA");
	Dl_415942_ = (tyProc_Dmq9b2yaUhM9bVc5PPuvIAPw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetStatusCallbackW");
	Dl_415946_ = (tyProc_m9c5iIvSrePZLE75MhxqrsA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpFindFirstFileA");
	Dl_415953_ = (tyProc_pXd9cx04FDRRnxBxs9aoG2KA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpFindFirstFileW");
	Dl_415960_ = (tyProc_51E0cFSg9bDNqNXb61cndfQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpGetFileA");
	Dl_415969_ = (tyProc_cAC5ip3WKhbUcKGbKG9aKWA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpGetFileW");
	Dl_415978_ = (tyProc_kLND6E9bR7RhKtfVfD5OAxQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpPutFileA");
	Dl_415985_ = (tyProc_qjBREOMCyD2CvslzTsUgjg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpPutFileW");
	Dl_415992_ = (tyProc_pYFEA6qdfZT1dGNrN639bCg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpGetFileEx");
	Dl_416001_ = (tyProc_c1IA1lj3yLt29c5iA4kDGeQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpPutFileEx");
	Dl_416008_ = (tyProc_IBq5TENC0hs6XbsecLkH2g) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpDeleteFileA");
	Dl_416012_ = (tyProc_zpIbd6qEt9a2fDaFRY6iS4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpDeleteFileW");
	Dl_416016_ = (tyProc_4vvMuwAGLRwXgAi0Oe9cSZw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpRenameFileA");
	Dl_416021_ = (tyProc_8kIgXqTQk0UfvD54m0PVUQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpRenameFileW");
	Dl_416026_ = (tyProc_43y7vyIDoqTJOPjL9aMMGXw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpOpenFileA");
	Dl_416033_ = (tyProc_OMHy9aHn1HP29cDAD8ta0f2g) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpOpenFileW");
	Dl_416040_ = (tyProc_IBq5TENC0hs6XbsecLkH2g) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpCreateDirectoryA");
	Dl_416044_ = (tyProc_zpIbd6qEt9a2fDaFRY6iS4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpCreateDirectoryW");
	Dl_416048_ = (tyProc_IBq5TENC0hs6XbsecLkH2g) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpRemoveDirectoryA");
	Dl_416052_ = (tyProc_zpIbd6qEt9a2fDaFRY6iS4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpRemoveDirectoryW");
	Dl_416056_ = (tyProc_IBq5TENC0hs6XbsecLkH2g) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpSetCurrentDirectoryA");
	Dl_416060_ = (tyProc_zpIbd6qEt9a2fDaFRY6iS4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpSetCurrentDirectoryW");
	Dl_416064_ = (tyProc_1X1qFDGqVZtr0FNdqKPPyQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpGetCurrentDirectoryA");
	Dl_416069_ = (tyProc_xjWfD6JL61TePeffRuJvNw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpGetCurrentDirectoryW");
	Dl_416074_ = (tyProc_eex9c6ByuGqswZB801XCW6Q) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpCommandA");
	Dl_416083_ = (tyProc_qhfr9b7vEKBVn9c2TQ1MDiWw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpCommandW");
	Dl_416092_ = (tyProc_hmzku9acjH9bP9a9cEj2lReMig) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpGetFileSize");
	Dl_416096_ = (tyProc_Qi9aHNdTw0bNfAccvLdvMzQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherCreateLocatorA");
	Dl_416105_ = (tyProc_bA9bcKawSwUkcYVGbYDAukQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherCreateLocatorW");
	Dl_416114_ = (tyProc_8e3Pc9bDmk0y4L2XN8nKBfQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherGetLocatorTypeA");
	Dl_416118_ = (tyProc_gxkCuWdOe6iDXo10iWshaA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherGetLocatorTypeW");
	Dl_416122_ = (tyProc_UDiFTVUA9bAB9a9aGX9cGZW6eQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherFindFirstFileA");
	Dl_416130_ = (tyProc_9c19a9bNwSc8b5r3ShY5BDukg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherFindFirstFileW");
	Dl_416138_ = (tyProc_519bNrk9bPAHJy9bD0U81xSjA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherOpenFileA");
	Dl_416145_ = (tyProc_IotBtDeviRFtvznQvFtb9aQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherOpenFileW");
	Dl_416152_ = (tyProc_v2Qau7p9clikFEJPznyWp9aQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherGetAttributeA");
	Dl_416162_ = (tyProc_yocxcokGSKFQxaqqVdalgg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherGetAttributeW");
	Dl_416172_ = (tyProc_39bvRsZ2NWyNmTxldSroDpg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpOpenRequestA");
	Dl_416183_ = (tyProc_jYD3iltB9cC1EDm3YFqpWQw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpOpenRequestW");
	Dl_416194_ = (tyProc_n7uqtUBZA9cah5cMlbu9aYvw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpAddRequestHeadersA");
	Dl_416200_ = (tyProc_GDtgFkYwnC8EJx7gppgoYg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpAddRequestHeadersW");
	Dl_416206_ = (tyProc_g7sgbb4KeafvPq9cLmwRcpw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpSendRequestA");
	Dl_416213_ = (tyProc_WUiVDobayRMfSL5cBE4TnQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpSendRequestW");
	Dl_416220_ = (tyProc_vSwYi5jbo0kfRe9ciLWbVuA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpSendRequestExA");
	Dl_416227_ = (tyProc_DK4rtfuwEr1Jwgpf9aFxYng) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpSendRequestExW");
	Dl_416234_ = (tyProc_9aWznLiR5YCCrF53nsjUfGg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpEndRequestA");
	Dl_416240_ = (tyProc_DHwEOkGuBcGhrfKi2seYRQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpEndRequestW");
	Dl_416246_ = (tyProc_QE3D0vERbcDUZ3vh8kM53w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpQueryInfoA");
	Dl_416253_ = (tyProc_QE3D0vERbcDUZ3vh8kM53w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpQueryInfoW");
	Dl_416260_ = (tyProc_uHbNDtUHhLpn9ayW9alFCA1g) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetCookieA");
	Dl_416265_ = (tyProc_TZyzM64ehR6MYFFuadIvRw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetCookieW");
	Dl_416270_ = (tyProc_llTOQ9bz6AdtOIqBq7OtlYA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetCookieA");
	Dl_416276_ = (tyProc_VoxY9bI1PG6msz4ykdSNJZA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetCookieW");
	Dl_416282_ = (tyProc_m5kaRwJiiF9bAxwGY3ksKDw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetCookieExA");
	Dl_416289_ = (tyProc_T9cy1IWeW7pZ7m2cZdvkX1A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetCookieExW");
	Dl_416296_ = (tyProc_rOfJfVVcWJ4OiS8z0Dct3w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetCookieExA");
	Dl_416304_ = (tyProc_NZ1LgKIViXnB9byV3PmBXSw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetCookieExW");
	Dl_416312_ = (tyProc_78ER49aUeWMW9b9c9aDqn5uqBg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetAttemptConnect");
	Dl_416315_ = (tyProc_npwuIjepzLxnErJxDI15Bw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCheckConnectionA");
	Dl_416320_ = (tyProc_C2HPPnPs38qWChg6HAUbKQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCheckConnectionW");
	Dl_416325_ = (tyProc_IJ8vvlYbVRxpIZFy4xyteg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "ResumeSuspendedDownload");
	Dl_416329_ = (tyProc_V5ObZeuO9a1Jj3umz39cGLJA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetErrorDlg");
	Dl_416337_ = (tyProc_cAT3HCJ3BlnK47CHaJExzg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetConfirmZoneCrossingA");
	Dl_416343_ = (tyProc_CWEdM7t4AIIGMHwMzG2F4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetConfirmZoneCrossingW");
	Dl_416349_ = (tyProc_Rgp6n1s0KykPQupsOwW01A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "CreateUrlCacheEntryA");
	Dl_416356_ = (tyProc_wj9aPLjX9cs71aKYqXtbq9b9cg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "CreateUrlCacheEntryW");
	Dl_416363_ = (tyProc_sroQuCsif34Jckj50zHinQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "CommitUrlCacheEntryA");
	Dl_416374_ = (tyProc_QTEfuhI4ZvHYcE5ptxgJJQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "CommitUrlCacheEntryW");
	Dl_416385_ = (tyProc_V1DwSfF9cF1FJkID9bg8xajw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "RetrieveUrlCacheEntryFileA");
	Dl_416391_ = (tyProc_1BV4zcCrUPN9amuao4lDaUA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "RetrieveUrlCacheEntryFileW");
	Dl_416397_ = (tyProc_80L3Z6UegUoaV03fstCgIA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "UnlockUrlCacheEntryFileA");
	Dl_416401_ = (tyProc_YMWms6jt9axreas9bJGMtTMA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "UnlockUrlCacheEntryFileW");
	Dl_416405_ = (tyProc_xjQPX6Ok4btsdPJAz1LtZA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "RetrieveUrlCacheEntryStreamA");
	Dl_416412_ = (tyProc_XlKzC6ac7y6uN9b3dZ0laEg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "RetrieveUrlCacheEntryStreamW");
	Dl_416419_ = (tyProc_EmyS3bz8dwyBVVC5PvwCDA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "ReadUrlCacheEntryStream");
	Dl_416426_ = (tyProc_FprzxJFfqQdWyyGxiUsmeQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "UnlockUrlCacheEntryStream");
	Dl_416430_ = (tyProc_Bx8co4J5c39a74b3mGUlFzg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheEntryInfoA");
	Dl_416435_ = (tyProc_lQNu1EXmL3nhDsEpkJPe9cA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheEntryInfoW");
	Dl_416440_ = (tyProc_gbtYhwh5ObtDGJPrINBU4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindFirstUrlCacheGroup");
	Dl_416449_ = (tyProc_o89cqX00gc5sX4oMqC2WegA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindNextUrlCacheGroup");
	Dl_416455_ = (tyProc_9b0Xc3PcaOW9cvn9bmwCs9bv6w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheGroupAttributeA");
	Dl_416463_ = (tyProc_LHbwrYhcZAmmJxgsHSzCYw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheGroupAttributeW");
	Dl_416471_ = (tyProc_LuANEz54Su9ccSmaGzXAOng) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheGroupAttributeA");
	Dl_416478_ = (tyProc_LuY1thm5hcscDVU4hhpPIg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheGroupAttributeW");
	Dl_416485_ = (tyProc_HIgFc5j5zgC05A9cNOLmg1w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "CreateUrlCacheGroup");
	Dl_416489_ = (tyProc_XR9a4iQtkL6QDQ19cu9a4jjFw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "DeleteUrlCacheGroup");
	Dl_416494_ = (tyProc_ygQs32zsiSaVDY9ayRdUYAQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheEntryInfoExA");
	Dl_416503_ = (tyProc_toL9bm9c5Ne65smhfALHcgvQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheEntryInfoExW");
	Dl_416512_ = (tyProc_yZNtE6xy5rcp3DDq71kwfA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheEntryInfoA");
	Dl_416517_ = (tyProc_9cmnBYbNnkS9cL9czR6krANEw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheEntryInfoW");
	Dl_416522_ = (tyProc_ow4WOYsmQgsldqeza9a88FQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheEntryGroupA");
	Dl_416530_ = (tyProc_LZ8LGGS31Ukf6ie2ByFP5A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheEntryGroupW");
	Dl_416538_ = (tyProc_dyrC4pmz4aGBO9cVfBWs78A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindFirstUrlCacheEntryExA");
	Dl_416549_ = (tyProc_AY6Qc5d734LzFhiAgm9axVw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindFirstUrlCacheEntryExW");
	Dl_416560_ = (tyProc_dHTNA0REpG3mOWtsGFcK8w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindNextUrlCacheEntryExA");
	Dl_416568_ = (tyProc_qsTAIqdcfIGlFGdYgXooNA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindNextUrlCacheEntryExW");
	Dl_416576_ = (tyProc_yR2gT9bBADC9agQOWOq1p37w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindFirstUrlCacheEntryA");
	Dl_416581_ = (tyProc_Zsw3dpID8Cjlt9bKyI9a54ow) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindFirstUrlCacheEntryW");
	Dl_416586_ = (tyProc_WhceJN4pt1xcC2McMkmcPA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindNextUrlCacheEntryA");
	Dl_416591_ = (tyProc_77LKcxVxiaK4AiK9cXtLTJg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindNextUrlCacheEntryW");
	Dl_416596_ = (tyProc_P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindCloseUrlCache");
	Dl_416599_ = (tyProc_yDWFOVVnqizp6M8D0kw9aVg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "DeleteUrlCacheEntryA");
	Dl_416602_ = (tyProc_uaa3EeY5nSKYBlex9baos2Q) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "DeleteUrlCacheEntryW");
	Dl_416605_ = (tyProc_KT0ShBylKYFzgT40PxF9cMA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetDialA");
	Dl_416613_ = (tyProc_wETW8F3oXFBPxGEMIUi3Ng) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetDialW");
	Dl_416621_ = (tyProc_8Dmqcbk03OzAn3kfUB9bxMQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetHangUp");
	Dl_416625_ = (tyProc_9bBHkTLQdF9bS6fgH9aW9bGHzA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGoOnlineA");
	Dl_416630_ = (tyProc_e0CAZd8piR1d8Mhnmhxx4w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGoOnlineW");
	Dl_416635_ = (tyProc_EIsGESqSaU8RXWpB8OLznw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetAutodial");
	Dl_416639_ = (tyProc_78ER49aUeWMW9b9c9aDqn5uqBg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetAutodialHangup");
	Dl_416642_ = (tyProc_ZMYPd7BOgovcnmXIh85rUQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetConnectedState");
	Dl_416646_ = (tyProc_KWKTc68BOA9bxliOrmvtkBA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetConnectedStateExA");
	Dl_416652_ = (tyProc_qLN066ctYabzFgMmWhVe9aw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetConnectedStateExW");
	Dl_416658_ = (tyProc_78ER49aUeWMW9b9c9aDqn5uqBg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetInitializeAutoProxyDll");
	Dl_416661_ = (tyProc_npwuIjepzLxnErJxDI15Bw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "DetectAutoProxyUrl");
	Dl_416666_ = (tyProc_8zxj8hHidNnmY39a2Qmks1A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "CreateMD5SSOHash");
	Dl_416672_ = (tyProc_npwuIjepzLxnErJxDI15Bw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetDialStateA");
	Dl_416677_ = (tyProc_C2HPPnPs38qWChg6HAUbKQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetDialStateW");
	Dl_416682_ = (tyProc_80L3Z6UegUoaV03fstCgIA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetPerSiteCookieDecisionA");
	Dl_416686_ = (tyProc_YMWms6jt9axreas9bJGMtTMA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetPerSiteCookieDecisionW");
	Dl_416690_ = (tyProc_8e3Pc9bDmk0y4L2XN8nKBfQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetPerSiteCookieDecisionA");
	Dl_416695_ = (tyProc_gxkCuWdOe6iDXo10iWshaA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetPerSiteCookieDecisionW");
	Dl_416700_ = (tyProc_9bXer9a4ps9aSGctILcxWReVw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetClearAllPerSiteCookieDecisions");
	Dl_416702_ = (tyProc_WobKuZ6sZlpLjWq0eOmh1g) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetEnumPerSiteCookieDecisionA");
	Dl_416710_ = (tyProc_dR7tySHCzyuUHadQKu9abuw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetEnumPerSiteCookieDecisionW");
	Dl_416718_ = (tyProc_nwLuJEx85btRONfl5MaiPg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "PrivacySetZonePreferenceW");
	Dl_416724_ = (tyProc_BsIhBpJUmxj9cbJv0LXh3eA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "PrivacyGetZonePreferenceW");
	Dl_416831_ = (tyProc_K4OzLFhLp6H1MEU0m007mA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCrackUrlW");
	Dl_416837_ = (tyProc_g39bQdN20SIZOPT0oqNoTPQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCreateUrlW");
	Dl_416843_ = (tyProc_NDE1Wz6MLFk5KS7JJEJ18w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCanonicalizeUrlW");
	Dl_416849_ = (tyProc_WE0t5XxU0pEHgtwUGwCYug) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCombineUrlW");
	Dl_416856_ = (tyProc_81VIzYkqwzDl7rl3af0pZg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetOpenW");
	Dl_416863_ = (tyProc_P2lHXOiBZr7SMt9b1gl6ptA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetConnectW");
	Dl_416873_ = (tyProc_k7gzG6e9b9bnzbZvYShWFTLg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetOpenUrlW");
	Dl_416881_ = (tyProc_DHwEOkGuBcGhrfKi2seYRQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetReadFileExW");
	Dl_416887_ = (tyProc_wS8JrJMcfFBzgzuqJGOAAg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetFindNextFileW");
	Dl_416891_ = (tyProc_p9acI9c9chaDF2CTXkYiH9bPlw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetQueryOptionW");
	Dl_416897_ = (tyProc_OygtxCk9aDjhab6i7UhdJdQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetOptionW");
	Dl_416903_ = (tyProc_TxuhRZrGfx2HNJbRLGdbvA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetOptionExW");
	Dl_416910_ = (tyProc_ghb0s1syaKEjHpgg9bpy5lA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetLastResponseInfoW");
	Dl_416915_ = (tyProc_pXd9cx04FDRRnxBxs9aoG2KA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpFindFirstFileW");
	Dl_416922_ = (tyProc_cAC5ip3WKhbUcKGbKG9aKWA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpGetFileW");
	Dl_416931_ = (tyProc_qjBREOMCyD2CvslzTsUgjg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpPutFileW");
	Dl_416938_ = (tyProc_zpIbd6qEt9a2fDaFRY6iS4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpDeleteFileW");
	Dl_416942_ = (tyProc_8kIgXqTQk0UfvD54m0PVUQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpRenameFileW");
	Dl_416947_ = (tyProc_OMHy9aHn1HP29cDAD8ta0f2g) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpOpenFileW");
	Dl_416954_ = (tyProc_zpIbd6qEt9a2fDaFRY6iS4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpCreateDirectoryW");
	Dl_416958_ = (tyProc_zpIbd6qEt9a2fDaFRY6iS4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpRemoveDirectoryW");
	Dl_416962_ = (tyProc_zpIbd6qEt9a2fDaFRY6iS4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpSetCurrentDirectoryW");
	Dl_416966_ = (tyProc_xjWfD6JL61TePeffRuJvNw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpGetCurrentDirectoryW");
	Dl_416971_ = (tyProc_qhfr9b7vEKBVn9c2TQ1MDiWw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FtpCommandW");
	Dl_416980_ = (tyProc_bA9bcKawSwUkcYVGbYDAukQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherCreateLocatorW");
	Dl_416989_ = (tyProc_gxkCuWdOe6iDXo10iWshaA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherGetLocatorTypeW");
	Dl_416993_ = (tyProc_9c19a9bNwSc8b5r3ShY5BDukg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherFindFirstFileW");
	Dl_417001_ = (tyProc_IotBtDeviRFtvznQvFtb9aQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherOpenFileW");
	Dl_417008_ = (tyProc_yocxcokGSKFQxaqqVdalgg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GopherGetAttributeW");
	Dl_417018_ = (tyProc_jYD3iltB9cC1EDm3YFqpWQw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpOpenRequestW");
	Dl_417029_ = (tyProc_GDtgFkYwnC8EJx7gppgoYg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpAddRequestHeadersW");
	Dl_417035_ = (tyProc_WUiVDobayRMfSL5cBE4TnQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpSendRequestW");
	Dl_417042_ = (tyProc_DK4rtfuwEr1Jwgpf9aFxYng) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpSendRequestExW");
	Dl_417049_ = (tyProc_DHwEOkGuBcGhrfKi2seYRQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpEndRequestW");
	Dl_417055_ = (tyProc_QE3D0vERbcDUZ3vh8kM53w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "HttpQueryInfoW");
	Dl_417062_ = (tyProc_TZyzM64ehR6MYFFuadIvRw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetCookieW");
	Dl_417067_ = (tyProc_VoxY9bI1PG6msz4ykdSNJZA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetCookieW");
	Dl_417073_ = (tyProc_T9cy1IWeW7pZ7m2cZdvkX1A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetCookieExW");
	Dl_417080_ = (tyProc_NZ1LgKIViXnB9byV3PmBXSw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetCookieExW");
	Dl_417088_ = (tyProc_C2HPPnPs38qWChg6HAUbKQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetCheckConnectionW");
	Dl_417093_ = (tyProc_wj9aPLjX9cs71aKYqXtbq9b9cg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "CreateUrlCacheEntryW");
	Dl_417100_ = (tyProc_QTEfuhI4ZvHYcE5ptxgJJQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "CommitUrlCacheEntryW");
	Dl_417111_ = (tyProc_1BV4zcCrUPN9amuao4lDaUA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "RetrieveUrlCacheEntryFileW");
	Dl_417117_ = (tyProc_YMWms6jt9axreas9bJGMtTMA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "UnlockUrlCacheEntryFileW");
	Dl_417121_ = (tyProc_XlKzC6ac7y6uN9b3dZ0laEg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "RetrieveUrlCacheEntryStreamW");
	Dl_417128_ = (tyProc_lQNu1EXmL3nhDsEpkJPe9cA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheEntryInfoW");
	Dl_417133_ = (tyProc_LHbwrYhcZAmmJxgsHSzCYw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheGroupAttributeW");
	Dl_417141_ = (tyProc_LuY1thm5hcscDVU4hhpPIg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheGroupAttributeW");
	Dl_417148_ = (tyProc_toL9bm9c5Ne65smhfALHcgvQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "GetUrlCacheEntryInfoExW");
	Dl_417157_ = (tyProc_9cmnBYbNnkS9cL9czR6krANEw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheEntryInfoW");
	Dl_417162_ = (tyProc_AY6Qc5d734LzFhiAgm9axVw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindFirstUrlCacheEntryExW");
	Dl_417173_ = (tyProc_qsTAIqdcfIGlFGdYgXooNA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindNextUrlCacheEntryExW");
	Dl_417181_ = (tyProc_Zsw3dpID8Cjlt9bKyI9a54ow) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindFirstUrlCacheEntryW");
	Dl_417186_ = (tyProc_77LKcxVxiaK4AiK9cXtLTJg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "FindNextUrlCacheEntryW");
	Dl_417191_ = (tyProc_YMWms6jt9axreas9bJGMtTMA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetPerSiteCookieDecisionW");
	Dl_417195_ = (tyProc_gxkCuWdOe6iDXo10iWshaA) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetPerSiteCookieDecisionW");
	Dl_417200_ = (tyProc_dR7tySHCzyuUHadQKu9abuw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetEnumPerSiteCookieDecisionW");
	Dl_417208_ = (tyProc_35C5Jy9bv719cLBXZdEji9aCg) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetTimeFromSystemTimeW");
	Dl_417215_ = (tyProc_v6FU7HBc3TqIDHV4Fx5IOQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetTimeToSystemTimeW");
	Dl_417221_ = (tyProc_Dmq9b2yaUhM9bVc5PPuvIAPw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetStatusCallbackW");
	Dl_417225_ = (tyProc_CWEdM7t4AIIGMHwMzG2F4A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetConfirmZoneCrossingW");
	Dl_417231_ = (tyProc_wETW8F3oXFBPxGEMIUi3Ng) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetDialW");
	Dl_417239_ = (tyProc_e0CAZd8piR1d8Mhnmhxx4w) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGoOnlineW");
	Dl_417244_ = (tyProc_uaa3EeY5nSKYBlex9baos2Q) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "DeleteUrlCacheEntryW");
	Dl_417247_ = (tyProc_LZ8LGGS31Ukf6ie2ByFP5A) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "SetUrlCacheEntryGroupW");
	Dl_417255_ = (tyProc_C2HPPnPs38qWChg6HAUbKQ) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetSetDialStateW");
	Dl_417260_ = (tyProc_qLN066ctYabzFgMmWhVe9aw) nimGetProcAddr(TM_yWPAFHUOrlH9cmyrd88npxA_2, "InternetGetConnectedStateExW");
}

