/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   F:\nim\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IF:\nim\lib -o O:\nim\wnim\release\examples\nimcache\winim_winnetwk.o O:\nim\wnim\release\examples\nimcache\winim_winnetwk.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg;
typedef struct tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ;
typedef struct tyObject_CONNECTDLGSTRUCTA_xLHruk42Rb6US8Hvkzk06A tyObject_CONNECTDLGSTRUCTA_xLHruk42Rb6US8Hvkzk06A;
typedef struct tyObject_CONNECTDLGSTRUCTW_GnpDubUQYNAljMMT5b9a9aHw tyObject_CONNECTDLGSTRUCTW_GnpDubUQYNAljMMT5b9a9aHw;
typedef struct tyObject_DISCDLGSTRUCTA_b78o69bMqmk1pjbm4RVTibg tyObject_DISCDLGSTRUCTA_b78o69bMqmk1pjbm4RVTibg;
typedef struct tyObject_DISCDLGSTRUCTW_3KIgGDzVVlmHrGEe2cNv4A tyObject_DISCDLGSTRUCTW_3KIgGDzVVlmHrGEe2cNv4A;
typedef struct tyObject_NETINFOSTRUCT_vj3MolriyCBMVYyBNrJJbA tyObject_NETINFOSTRUCT_vj3MolriyCBMVYyBNrJJbA;
typedef struct tyObject_NETCONNECTINFOSTRUCT_fUa2h4F0CmgYhM3Ma0PskA tyObject_NETCONNECTINFOSTRUCT_fUa2h4F0CmgYhM3Ma0PskA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, tyProc_uHbNDtUHhLpn9ayW9alFCA1g) (NCSTRING lpRemoteName, NCSTRING lpPassword, NCSTRING lpLocalName);
typedef N_STDCALL_PTR(NI32, tyProc_TZyzM64ehR6MYFFuadIvRw) (NU16* lpRemoteName, NU16* lpPassword, NU16* lpLocalName);
typedef N_STDCALL_PTR(NI32, tyProc_79cAIRr4BSk6Psvdq7jvu3Q) (tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg* lpNetResource, NCSTRING lpPassword, NCSTRING lpUserName, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_vDWKx330V8S0H4iULxD41A) (tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ* lpNetResource, NU16* lpPassword, NU16* lpUserName, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_HKVsoCgnzesVqmnQeHUQbA) (NI hwndOwner, tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg* lpNetResource, NCSTRING lpPassword, NCSTRING lpUserName, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_e9cY9c49cUsS8ZzUoIP0GOXQg) (NI hwndOwner, tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ* lpNetResource, NU16* lpPassword, NU16* lpUserName, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_80L3Z6UegUoaV03fstCgIA) (NCSTRING lpName, NI32 fForce);
typedef N_STDCALL_PTR(NI32, tyProc_YMWms6jt9axreas9bJGMtTMA) (NU16* lpName, NI32 fForce);
typedef N_STDCALL_PTR(NI32, tyProc_npwuIjepzLxnErJxDI15Bw) (NCSTRING lpName, NI32 dwFlags, NI32 fForce);
typedef N_STDCALL_PTR(NI32, tyProc_C2HPPnPs38qWChg6HAUbKQ) (NU16* lpName, NI32 dwFlags, NI32 fForce);
typedef N_STDCALL_PTR(NI32, tyProc_PRm2NuoDw9cpC2vh11FewNg) (NCSTRING lpLocalName, NCSTRING lpRemoteName, NI32* lpnLength);
typedef N_STDCALL_PTR(NI32, tyProc_obbe09bmtKIYoKQYc8TBiTg) (NU16* lpLocalName, NU16* lpRemoteName, NI32* lpnLength);
typedef N_STDCALL_PTR(NI32, tyProc_elH9b6mOxnGGnYIDwpf7KSA) (NI hwndOwner, tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg* lpNetResource, NCSTRING lpPassword, NCSTRING lpUserID, NI32 dwFlags, NCSTRING lpAccessName, NI32* lpBufferSize, NI32* lpResult);
typedef N_STDCALL_PTR(NI32, tyProc_GsYKnZjRvAgSDxEk71fj9aQ) (NI hwndOwner, tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ* lpNetResource, NU16* lpPassword, NU16* lpUserID, NI32 dwFlags, NU16* lpAccessName, NI32* lpBufferSize, NI32* lpResult);
typedef N_STDCALL_PTR(NI32, tyProc_FprzxJFfqQdWyyGxiUsmeQ) (NI hwnd, NI32 dwType);
typedef N_STDCALL_PTR(NI32, tyProc_zs1G9aN0hsG4qr4I6t6Agtg) (NI hwndParent, NU16* lpDevice, NI32 fUseUI);
typedef N_STDCALL_PTR(NI32, tyProc_6nWvK0WeYiwIsryXXf3Kbg) (tyObject_CONNECTDLGSTRUCTA_xLHruk42Rb6US8Hvkzk06A* lpConnDlgStruct);
typedef N_STDCALL_PTR(NI32, tyProc_5V6lrjbAmxQOe28sadqLgg) (tyObject_CONNECTDLGSTRUCTW_GnpDubUQYNAljMMT5b9a9aHw* lpConnDlgStruct);
typedef N_STDCALL_PTR(NI32, tyProc_6UERPxlGV7ynX1yo9a8PC1g) (tyObject_DISCDLGSTRUCTA_b78o69bMqmk1pjbm4RVTibg* lpConnDlgStruct);
typedef N_STDCALL_PTR(NI32, tyProc_6tCrgd4MJ2J2qvsjOZgcpA) (tyObject_DISCDLGSTRUCTW_3KIgGDzVVlmHrGEe2cNv4A* lpConnDlgStruct);
typedef N_STDCALL_PTR(NI32, tyProc_TPhchzbjjAR5Wx5w9cq4e6A) (NI32 dwScope, NI32 dwType, NI32 dwUsage, tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg* lpNetResource, NI* lphEnum);
typedef N_STDCALL_PTR(NI32, tyProc_gY4L0liQeaM7TIU9b9a8sr7w) (NI32 dwScope, NI32 dwType, NI32 dwUsage, tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ* lpNetResource, NI* lphEnum);
typedef N_STDCALL_PTR(NI32, tyProc_ibTCPGAURr9bw9cm6f8DXQgg) (NI hEnum, NI32* lpcCount, void* lpBuffer, NI32* lpBufferSize);
typedef N_STDCALL_PTR(NI32, tyProc_P13srMBg9b3d3yEV9aW4NCoA) (NI hEnum);
typedef N_STDCALL_PTR(NI32, tyProc_zCK2PFKHEZcLod49c5XGe1g) (tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg* lpNetResource, void* lpBuffer, NI32* lpcbBuffer);
typedef N_STDCALL_PTR(NI32, tyProc_X267ca6x0D18t1YK8epgIQ) (tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ* lpNetResource, void* lpBuffer, NI32* lpcbBuffer);
typedef N_STDCALL_PTR(NI32, tyProc_ux79aKJ0QTu6a9c7FQHhSLVA) (tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg* lpNetResource, void* lpBuffer, NI32* lpcbBuffer, NCSTRING* lplpSystem);
typedef N_STDCALL_PTR(NI32, tyProc_W2MY3ySOS4qb0Ogt9cE9bJmw) (tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ* lpNetResource, void* lpBuffer, NI32* lpcbBuffer, NU16** lplpSystem);
typedef N_STDCALL_PTR(NI32, tyProc_9apLr9cImbQub9ccTYvAL6L9aA) (NCSTRING lpLocalPath, NI32 dwInfoLevel, void* lpBuffer, NI32* lpBufferSize);
typedef N_STDCALL_PTR(NI32, tyProc_Nh1EvAYLnEaXcXTacT9bHJA) (NU16* lpLocalPath, NI32 dwInfoLevel, void* lpBuffer, NI32* lpBufferSize);
typedef N_STDCALL_PTR(NI32, tyProc_o9aU4DmdRj4drWJRtCxP89ag) (NI32 dwNetType, NCSTRING lpProviderName, NI32* lpBufferSize);
typedef N_STDCALL_PTR(NI32, tyProc_Y9cp8MFnlAtx9aaSpBQogtFA) (NI32 dwNetType, NU16* lpProviderName, NI32* lpBufferSize);
typedef N_STDCALL_PTR(NI32, tyProc_ZGCQNxRGGTRoDudgkWf9bmg) (NCSTRING lpProvider, tyObject_NETINFOSTRUCT_vj3MolriyCBMVYyBNrJJbA* lpNetInfoStruct);
typedef N_STDCALL_PTR(NI32, tyProc_9cmeQO7ANswQHcUFS2tBhxw) (NU16* lpProvider, tyObject_NETINFOSTRUCT_vj3MolriyCBMVYyBNrJJbA* lpNetInfoStruct);
typedef N_STDCALL_PTR(NI32, tyProc_4OrEi66Rz8Kw9c9a88fpKZxA) (NI32* lpError, NCSTRING lpErrorBuf, NI32 nErrorBufSize, NCSTRING lpNameBuf, NI32 nNameBufSize);
typedef N_STDCALL_PTR(NI32, tyProc_rN6tUin54arz4cXONOd9ckw) (NI32* lpError, NU16* lpErrorBuf, NI32 nErrorBufSize, NU16* lpNameBuf, NI32 nNameBufSize);
typedef N_STDCALL_PTR(NI32, tyProc_Fyxp2Ff3zY162yzwa2ddqQ) (tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg* lpNetResource, tyObject_NETCONNECTINFOSTRUCT_fUa2h4F0CmgYhM3Ma0PskA* lpNetConnectInfoStruct);
typedef N_STDCALL_PTR(NI32, tyProc_xZfJuuTu0Cy8Ce9cM4R5LOw) (tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ* lpNetResource, tyObject_NETCONNECTINFOSTRUCT_fUa2h4F0CmgYhM3Ma0PskA* lpNetConnectInfoStruct);
struct tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg {
NI32 dwScope;
NI32 dwType;
NI32 dwDisplayType;
NI32 dwUsage;
NCSTRING lpLocalName;
NCSTRING lpRemoteName;
NCSTRING lpComment;
NCSTRING lpProvider;
};
struct tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ {
NI32 dwScope;
NI32 dwType;
NI32 dwDisplayType;
NI32 dwUsage;
NU16* lpLocalName;
NU16* lpRemoteName;
NU16* lpComment;
NU16* lpProvider;
};
struct tyObject_CONNECTDLGSTRUCTA_xLHruk42Rb6US8Hvkzk06A {
NI32 cbStructure;
NI hwndOwner;
tyObject_NETRESOURCEA_aramGacVenjlx77zMlRAsg* lpConnRes;
NI32 dwFlags;
NI32 dwDevNum;
};
struct tyObject_CONNECTDLGSTRUCTW_GnpDubUQYNAljMMT5b9a9aHw {
NI32 cbStructure;
NI hwndOwner;
tyObject_NETRESOURCEW_i4Mkz2YdWxSjEqOeKGZgAQ* lpConnRes;
NI32 dwFlags;
NI32 dwDevNum;
};
struct tyObject_DISCDLGSTRUCTA_b78o69bMqmk1pjbm4RVTibg {
NI32 cbStructure;
NI hwndOwner;
NCSTRING lpLocalName;
NCSTRING lpRemoteName;
NI32 dwFlags;
};
struct tyObject_DISCDLGSTRUCTW_3KIgGDzVVlmHrGEe2cNv4A {
NI32 cbStructure;
NI hwndOwner;
NU16* lpLocalName;
NU16* lpRemoteName;
NI32 dwFlags;
};
struct tyObject_NETINFOSTRUCT_vj3MolriyCBMVYyBNrJJbA {
NI32 cbStructure;
NI32 dwProviderVersion;
NI32 dwStatus;
NI32 dwCharacteristics;
NU64 dwHandle;
NU16 wNetType;
NI32 dwPrinters;
NI32 dwDrives;
};
struct tyObject_NETCONNECTINFOSTRUCT_fUa2h4F0CmgYhM3Ma0PskA {
NI32 cbStructure;
NI32 dwFlags;
NI32 dwSpeed;
NI32 dwDelay;
NI32 dwOptDataSize;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_6XCKo7Az9aliEbSvh03S9bdQ_2;
tyProc_uHbNDtUHhLpn9ayW9alFCA1g Dl_299447_;
tyProc_TZyzM64ehR6MYFFuadIvRw Dl_299452_;
tyProc_79cAIRr4BSk6Psvdq7jvu3Q Dl_299457_;
tyProc_vDWKx330V8S0H4iULxD41A Dl_299463_;
tyProc_HKVsoCgnzesVqmnQeHUQbA Dl_299469_;
tyProc_e9cY9c49cUsS8ZzUoIP0GOXQg Dl_299476_;
tyProc_80L3Z6UegUoaV03fstCgIA Dl_299483_;
tyProc_YMWms6jt9axreas9bJGMtTMA Dl_299487_;
tyProc_npwuIjepzLxnErJxDI15Bw Dl_299491_;
tyProc_C2HPPnPs38qWChg6HAUbKQ Dl_299496_;
tyProc_PRm2NuoDw9cpC2vh11FewNg Dl_299501_;
tyProc_obbe09bmtKIYoKQYc8TBiTg Dl_299506_;
tyProc_elH9b6mOxnGGnYIDwpf7KSA Dl_299511_;
tyProc_GsYKnZjRvAgSDxEk71fj9aQ Dl_299521_;
tyProc_FprzxJFfqQdWyyGxiUsmeQ Dl_299531_;
tyProc_FprzxJFfqQdWyyGxiUsmeQ Dl_299535_;
tyProc_zs1G9aN0hsG4qr4I6t6Agtg Dl_299539_;
tyProc_6nWvK0WeYiwIsryXXf3Kbg Dl_299544_;
tyProc_5V6lrjbAmxQOe28sadqLgg Dl_299547_;
tyProc_6UERPxlGV7ynX1yo9a8PC1g Dl_299550_;
tyProc_6tCrgd4MJ2J2qvsjOZgcpA Dl_299553_;
tyProc_TPhchzbjjAR5Wx5w9cq4e6A Dl_299556_;
tyProc_gY4L0liQeaM7TIU9b9a8sr7w Dl_299563_;
tyProc_ibTCPGAURr9bw9cm6f8DXQgg Dl_299570_;
tyProc_ibTCPGAURr9bw9cm6f8DXQgg Dl_299576_;
tyProc_P13srMBg9b3d3yEV9aW4NCoA Dl_299582_;
tyProc_zCK2PFKHEZcLod49c5XGe1g Dl_299585_;
tyProc_X267ca6x0D18t1YK8epgIQ Dl_299590_;
tyProc_ux79aKJ0QTu6a9c7FQHhSLVA Dl_299595_;
tyProc_W2MY3ySOS4qb0Ogt9cE9bJmw Dl_299602_;
tyProc_9apLr9cImbQub9ccTYvAL6L9aA Dl_299609_;
tyProc_Nh1EvAYLnEaXcXTacT9bHJA Dl_299615_;
tyProc_PRm2NuoDw9cpC2vh11FewNg Dl_299621_;
tyProc_obbe09bmtKIYoKQYc8TBiTg Dl_299626_;
tyProc_o9aU4DmdRj4drWJRtCxP89ag Dl_299631_;
tyProc_Y9cp8MFnlAtx9aaSpBQogtFA Dl_299636_;
tyProc_ZGCQNxRGGTRoDudgkWf9bmg Dl_299641_;
tyProc_9cmeQO7ANswQHcUFS2tBhxw Dl_299645_;
tyProc_4OrEi66Rz8Kw9c9a88fpKZxA Dl_299649_;
tyProc_rN6tUin54arz4cXONOd9ckw Dl_299656_;
tyProc_Fyxp2Ff3zY162yzwa2ddqQ Dl_299663_;
tyProc_xZfJuuTu0Cy8Ce9cM4R5LOw Dl_299667_;
tyProc_TZyzM64ehR6MYFFuadIvRw Dl_299702_;
tyProc_vDWKx330V8S0H4iULxD41A Dl_299707_;
tyProc_e9cY9c49cUsS8ZzUoIP0GOXQg Dl_299713_;
tyProc_YMWms6jt9axreas9bJGMtTMA Dl_299720_;
tyProc_C2HPPnPs38qWChg6HAUbKQ Dl_299724_;
tyProc_obbe09bmtKIYoKQYc8TBiTg Dl_299729_;
tyProc_GsYKnZjRvAgSDxEk71fj9aQ Dl_299734_;
tyProc_5V6lrjbAmxQOe28sadqLgg Dl_299744_;
tyProc_6tCrgd4MJ2J2qvsjOZgcpA Dl_299747_;
tyProc_gY4L0liQeaM7TIU9b9a8sr7w Dl_299750_;
tyProc_ibTCPGAURr9bw9cm6f8DXQgg Dl_299757_;
tyProc_X267ca6x0D18t1YK8epgIQ Dl_299763_;
tyProc_W2MY3ySOS4qb0Ogt9cE9bJmw Dl_299768_;
tyProc_Nh1EvAYLnEaXcXTacT9bHJA Dl_299775_;
tyProc_obbe09bmtKIYoKQYc8TBiTg Dl_299781_;
tyProc_Y9cp8MFnlAtx9aaSpBQogtFA Dl_299786_;
tyProc_9cmeQO7ANswQHcUFS2tBhxw Dl_299791_;
tyProc_rN6tUin54arz4cXONOd9ckw Dl_299795_;
tyProc_xZfJuuTu0Cy8Ce9cM4R5LOw Dl_299802_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_6XCKo7Az9aliEbSvh03S9bdQ_4, "mpr", 3);
STRING_LITERAL(TM_6XCKo7Az9aliEbSvh03S9bdQ_5, "mpr", 3);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, winim_winnetwkInit000)(void) {
	nimfr_("winnetwk", "winnetwk.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, winim_winnetwkDatInit000)(void) {
if (!((TM_6XCKo7Az9aliEbSvh03S9bdQ_2 = nimLoadLibrary((NimStringDesc*) &TM_6XCKo7Az9aliEbSvh03S9bdQ_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_6XCKo7Az9aliEbSvh03S9bdQ_5);
	Dl_299447_ = (tyProc_uHbNDtUHhLpn9ayW9alFCA1g) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnectionA");
	Dl_299452_ = (tyProc_TZyzM64ehR6MYFFuadIvRw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnectionW");
	Dl_299457_ = (tyProc_79cAIRr4BSk6Psvdq7jvu3Q) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnection2A");
	Dl_299463_ = (tyProc_vDWKx330V8S0H4iULxD41A) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnection2W");
	Dl_299469_ = (tyProc_HKVsoCgnzesVqmnQeHUQbA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnection3A");
	Dl_299476_ = (tyProc_e9cY9c49cUsS8ZzUoIP0GOXQg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnection3W");
	Dl_299483_ = (tyProc_80L3Z6UegUoaV03fstCgIA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetCancelConnectionA");
	Dl_299487_ = (tyProc_YMWms6jt9axreas9bJGMtTMA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetCancelConnectionW");
	Dl_299491_ = (tyProc_npwuIjepzLxnErJxDI15Bw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetCancelConnection2A");
	Dl_299496_ = (tyProc_C2HPPnPs38qWChg6HAUbKQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetCancelConnection2W");
	Dl_299501_ = (tyProc_PRm2NuoDw9cpC2vh11FewNg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetConnectionA");
	Dl_299506_ = (tyProc_obbe09bmtKIYoKQYc8TBiTg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetConnectionW");
	Dl_299511_ = (tyProc_elH9b6mOxnGGnYIDwpf7KSA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetUseConnectionA");
	Dl_299521_ = (tyProc_GsYKnZjRvAgSDxEk71fj9aQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetUseConnectionW");
	Dl_299531_ = (tyProc_FprzxJFfqQdWyyGxiUsmeQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetConnectionDialog");
	Dl_299535_ = (tyProc_FprzxJFfqQdWyyGxiUsmeQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetDisconnectDialog");
	Dl_299539_ = (tyProc_zs1G9aN0hsG4qr4I6t6Agtg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetRestoreSingleConnectionW");
	Dl_299544_ = (tyProc_6nWvK0WeYiwIsryXXf3Kbg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetConnectionDialog1A");
	Dl_299547_ = (tyProc_5V6lrjbAmxQOe28sadqLgg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetConnectionDialog1W");
	Dl_299550_ = (tyProc_6UERPxlGV7ynX1yo9a8PC1g) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetDisconnectDialog1A");
	Dl_299553_ = (tyProc_6tCrgd4MJ2J2qvsjOZgcpA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetDisconnectDialog1W");
	Dl_299556_ = (tyProc_TPhchzbjjAR5Wx5w9cq4e6A) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetOpenEnumA");
	Dl_299563_ = (tyProc_gY4L0liQeaM7TIU9b9a8sr7w) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetOpenEnumW");
	Dl_299570_ = (tyProc_ibTCPGAURr9bw9cm6f8DXQgg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetEnumResourceA");
	Dl_299576_ = (tyProc_ibTCPGAURr9bw9cm6f8DXQgg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetEnumResourceW");
	Dl_299582_ = (tyProc_P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetCloseEnum");
	Dl_299585_ = (tyProc_zCK2PFKHEZcLod49c5XGe1g) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetResourceParentA");
	Dl_299590_ = (tyProc_X267ca6x0D18t1YK8epgIQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetResourceParentW");
	Dl_299595_ = (tyProc_ux79aKJ0QTu6a9c7FQHhSLVA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetResourceInformationA");
	Dl_299602_ = (tyProc_W2MY3ySOS4qb0Ogt9cE9bJmw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetResourceInformationW");
	Dl_299609_ = (tyProc_9apLr9cImbQub9ccTYvAL6L9aA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetUniversalNameA");
	Dl_299615_ = (tyProc_Nh1EvAYLnEaXcXTacT9bHJA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetUniversalNameW");
	Dl_299621_ = (tyProc_PRm2NuoDw9cpC2vh11FewNg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetUserA");
	Dl_299626_ = (tyProc_obbe09bmtKIYoKQYc8TBiTg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetUserW");
	Dl_299631_ = (tyProc_o9aU4DmdRj4drWJRtCxP89ag) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetProviderNameA");
	Dl_299636_ = (tyProc_Y9cp8MFnlAtx9aaSpBQogtFA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetProviderNameW");
	Dl_299641_ = (tyProc_ZGCQNxRGGTRoDudgkWf9bmg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetNetworkInformationA");
	Dl_299645_ = (tyProc_9cmeQO7ANswQHcUFS2tBhxw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetNetworkInformationW");
	Dl_299649_ = (tyProc_4OrEi66Rz8Kw9c9a88fpKZxA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetLastErrorA");
	Dl_299656_ = (tyProc_rN6tUin54arz4cXONOd9ckw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetLastErrorW");
	Dl_299663_ = (tyProc_Fyxp2Ff3zY162yzwa2ddqQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "MultinetGetConnectionPerformanceA");
	Dl_299667_ = (tyProc_xZfJuuTu0Cy8Ce9cM4R5LOw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "MultinetGetConnectionPerformanceW");
	Dl_299702_ = (tyProc_TZyzM64ehR6MYFFuadIvRw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnectionW");
	Dl_299707_ = (tyProc_vDWKx330V8S0H4iULxD41A) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnection2W");
	Dl_299713_ = (tyProc_e9cY9c49cUsS8ZzUoIP0GOXQg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetAddConnection3W");
	Dl_299720_ = (tyProc_YMWms6jt9axreas9bJGMtTMA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetCancelConnectionW");
	Dl_299724_ = (tyProc_C2HPPnPs38qWChg6HAUbKQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetCancelConnection2W");
	Dl_299729_ = (tyProc_obbe09bmtKIYoKQYc8TBiTg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetConnectionW");
	Dl_299734_ = (tyProc_GsYKnZjRvAgSDxEk71fj9aQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetUseConnectionW");
	Dl_299744_ = (tyProc_5V6lrjbAmxQOe28sadqLgg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetConnectionDialog1W");
	Dl_299747_ = (tyProc_6tCrgd4MJ2J2qvsjOZgcpA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetDisconnectDialog1W");
	Dl_299750_ = (tyProc_gY4L0liQeaM7TIU9b9a8sr7w) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetOpenEnumW");
	Dl_299757_ = (tyProc_ibTCPGAURr9bw9cm6f8DXQgg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetEnumResourceW");
	Dl_299763_ = (tyProc_X267ca6x0D18t1YK8epgIQ) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetResourceParentW");
	Dl_299768_ = (tyProc_W2MY3ySOS4qb0Ogt9cE9bJmw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetResourceInformationW");
	Dl_299775_ = (tyProc_Nh1EvAYLnEaXcXTacT9bHJA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetUniversalNameW");
	Dl_299781_ = (tyProc_obbe09bmtKIYoKQYc8TBiTg) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetUserW");
	Dl_299786_ = (tyProc_Y9cp8MFnlAtx9aaSpBQogtFA) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetProviderNameW");
	Dl_299791_ = (tyProc_9cmeQO7ANswQHcUFS2tBhxw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetNetworkInformationW");
	Dl_299795_ = (tyProc_rN6tUin54arz4cXONOd9ckw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "WNetGetLastErrorW");
	Dl_299802_ = (tyProc_xZfJuuTu0Cy8Ce9cM4R5LOw) nimGetProcAddr(TM_6XCKo7Az9aliEbSvh03S9bdQ_2, "MultinetGetConnectionPerformanceW");
}

