#====================================================================
#
#               wNim - Nim's Windows GUI Framework
#                 (c) Copyright 2017-2021 Ward
#
#====================================================================

## These events are generated by wWindow when the user pressed the keyboard.
#
## :Superclass:
##   `wEvent <wEvent.html>`_
#
## :Seealso:
##   `wWindow <wWindow.html>`_
#
## :Events:
##   ==============================  =============================================================
##   wKeyEvent                       Description
##   ==============================  =============================================================
##   wEvent_Char                     A focused Window receives a char.
##   wEvent_KeyDown                  A key was pressed.
##   wEvent_KeyUp                    A key was released.
##   wEvent_SysKeyDown               Presses the F10 key or holds down the ALT key and then presses another key.
##   wEvent_SysKeyUp                 Releases a key that was pressed while the ALT key was held down.
##   ==============================  =============================================================

include ../pragma
import ../wBase

wEventRegister(wKeyEvent):
  wEvent_Char = WM_CHAR
  wEvent_KeyDown = WM_KEYDOWN
  wEvent_KeyUp = WM_KEYUP
  wEvent_SysKeyDown = WM_SYSKEYDOWN
  wEvent_SysKeyUp = WM_SYSKEYUP
  wEvent_KeyFirst = WM_KEYFIRST
  wEvent_KeyLast = WM_KEYLAST

method getKeyCode*(self: wKeyEvent): int {.property, inline.} =
  ## Returns the key code of the key that generated this event.
  result = int self.mWparam
