#====================================================================
#
#               wNim - Nim's Windows GUI Framework
#                 (c) Copyright 2017-2021 Ward
#
#====================================================================

## These events are generated by wListCtrl.
#
## :Superclass:
##   `wCommandEvent <wCommandEvent.html>`_
#
## :Seealso:
##   `wListCtrl <wListCtrl.html>`_
#
## :Events:
##   ==============================  =============================================================
##   wListEvent                      Description
##   ==============================  =============================================================
##   wEvent_ListBeginDrag            Begin dragging with the left mouse button.
##   wEvent_ListBeginRightDrag       Begin dragging with the right mouse button.
##   wEvent_ListBeginLabelEdit       Begin editing a label. This event can be vetoed.
##   wEvent_ListEndLabelEdit         Finish editing a label. This event can be vetoed.
##   wEvent_ListDeleteItem           An item was deleted.
##   wEvent_ListDeleteAllItems       All items were deleted.
##   wEvent_ListItemFocused          The currently focused item has changed.
##   wEvent_ListItemSelected         The item has been selected.
##   wEvent_ListItemDeselected       The item has been deselected.
##   wEvent_ListItemActivated        The item has been activated (ENTER or double click).
##   wEvent_ListItemRightClick       The right mouse button has been clicked on an item.
##   wEvent_ListInsertItem           An item has been inserted.
##   wEvent_ListColClick             A column has been left-clicked.
##   wEvent_ListColRightClick        A column has been right-clicked.
##   wEvent_ListColBeginDrag         The user started resizing a column. This event can be vetoed.
##   wEvent_ListColDragging          The divider between columns is being dragged.
##   wEvent_ListColEndDrag           A column has been resized by the user.
##   wEvent_ListColBeginMove         The user started moving a column.
##   wEvent_ListColEndMove           A column has been moved by the user.
##   wEvent_ListitemChecked          The item has been checked.
##   wEvent_ListitemUnchecked        The item has been unchecked.
##   ==============================  =============================================================

include ../pragma
import ../wBase

wEventRegister(wListEvent):
  wEvent_ListFirst
  wEvent_ListBeginDrag
  wEvent_ListBeginRightDrag
  wEvent_ListBeginLabelEdit
  wEvent_ListEndLabelEdit
  wEvent_ListDeleteItem
  wEvent_ListDeleteAllItems
  wEvent_ListItemFocused
  wEvent_ListItemSelected
  wEvent_ListItemDeselected
  wEvent_ListItemActivated
  wEvent_ListItemRightClick
  wEvent_ListItemChecked
  wEvent_ListItemUnchecked
  wEvent_ListInsertItem
  wEvent_ListColClick
  wEvent_ListColRightClick
  wEvent_ListColBeginDrag
  wEvent_ListColDragging
  wEvent_ListColEndDrag
  wEvent_ListColBeginMove
  wEvent_ListColEndMove
  wEvent_ListLast

method getIndex*(self: wListEvent): int {.property, inline.} =
  ## The item index.
  result = self.mIndex

method getColumn*(self: wListEvent): int {.property, inline.} =
  ## The column position.
  result = self.mCol

method getText*(self: wListEvent): string {.property, inline.} =
  ## The (new) item label for wEvent_ListEndLabelEdit event.
  result = self.mText
