#====================================================================
#
#               wNim - Nim's Windows GUI Framework
#                 (c) Copyright 2017-2019 Ward
#
#====================================================================

## This event is generated by wControl when it need to know a navigation key
## is used by the control or not. This is used by wNim internally.
#
## :Superclass:
##   `wEvent <wEvent.html>`_
#
## :Events:
##   ==============================  =============================================================
##   wNavigationEvent                Description
##   ==============================  =============================================================
##   wEvent_Navigation               A navigation key was pressed.
##   ==============================  =============================================================

const
  wEvent_Navigation* = WM_APP + 2

proc isNavigationEvent(msg: UINT): bool {.inline.} =
  msg == wEvent_Navigation

method shouldPropagate*(event: wNavigationEvent): bool =
  ## A navigation event should be never propagated.
  result = false

method getKeyCode*(self: wNavigationEvent): int {.property, inline.} =
  ## Returns the key code of the key that generated this event.
  result = int self.mWparam
