#====================================================================
#
#               wNim - Nim's Windows GUI Framework
#                 (c) Copyright 2017-2020 Ward
#
#====================================================================

## These events are generated by wWindow when the window size is changed or
## about to change.
#
## :Superclass:
##   `wEvent <wEvent.html>`_
#
## :Seealso:
##   `wWindow <wWindow.html>`_
#
## :Events:
##   ==============================  =============================================================
##   wSizeEvent                      Description
##   ==============================  =============================================================
##   wEvent_Size                     Window size has changed.
##   wEvent_Iconize                  Window is iconized, mostly generated from a frame.
##   wEvent_Minimize                 Window is iconized, the same as wEvent_Iconize.
##   wEvent_Maximize                 Window is maximized, mostly generated from a frame.
##   wEvent_Sizing                   Window is sizing.
##   ==============================  =============================================================

{.experimental, deadCodeElim: on.}

import ../wBase

DefineEvent:
  wEvent_Size
  wEvent_Minimize
  wEvent_Maximize
  wEvent_Sizing

const
  wEvent_Iconize* = wEvent_Minimize

proc isSizeEvent(msg: UINT): bool {.inline, shield.} =
  msg in wEvent_Size..wEvent_Sizing

method getSize*(self: wSizeEvent): wSize {.property.} =
  ## Returns the entire size of the window generating the size change event.
  result.width = GET_X_LPARAM(self.mLparam)
  result.height = GET_Y_LPARAM(self.mLparam)
