#====================================================================
#
#               wNim - Nim's Windows GUI Framework
#                 (c) Copyright 2017-2019 Ward
#
#====================================================================

## These events are generated by wWindow when the window size is changed or
## about to change.
#
## :Superclass:
##   `wEvent <wEvent.html>`_
#
## :Events:
##   ==============================  =============================================================
##   wSizeEvent                      Description
##   ==============================  =============================================================
##   wEvent_Size                     Window size has changed.
##   wEvent_Iconize                  Window is iconized, mostly generated from a frame.
##   wEvent_Minimize                 Window is iconized, the same as wEvent_Iconize.
##   wEvent_Maximize                 Window is maximized, mostly generated from a frame.
##   wEvent_Sizing                   Window is sizing.
##   ==============================  =============================================================


const
  wEvent_Size* = WM_APP + 52
  wEvent_Iconize* = WM_APP + 53
  wEvent_Minimize* = WM_APP + 53
  wEvent_Maximize* = WM_APP + 54
  wEvent_Sizing* = WM_APP + 55

proc isSizeEvent(msg: UINT): bool {.inline.} =
  msg in wEvent_Size..wEvent_Sizing

method getSize*(self: wSizeEvent): wSize {.property.} =
  ## Returns the entire size of the window generating the size change event.
  result.width = GET_X_LPARAM(self.mLparam)
  result.height = GET_Y_LPARAM(self.mLparam)
