#====================================================================
#
#               wNim - Nim's Windows GUI Framework
#                 (c) Copyright 2017-2019 Ward
#
#====================================================================

## These events are generated by wStatusBar.
#
## :Superclass:
##   `wCommandEvent <wCommandEvent.html>`_
#
## :Events:
##   ================================  =============================================================
##   wStatusBarEvent                   Description
##   ================================  =============================================================
##   wEvent_StatusBarLeftClick         Clicked the left mouse button within the control.
##   wEvent_StatusBarLeftDoubleClick   Double-clicked the left mouse button within the control.
##   wEvent_StatusBarRightClick        Clicked the right mouse button within the control.
##   wEvent_StatusBarRightDoubleClick  Double-clicked the right mouse button within the control.
##   ================================  =============================================================

DefineIncrement(wEvent_StatusBarFirst):
  wEvent_StatusBarLeftClick
  wEvent_StatusBarLeftDoubleClick
  wEvent_StatusBarRightClick
  wEvent_StatusBarRightDoubleClick
  wEvent_StatusBarLast

proc isStatusBarEvent(msg: UINT): bool {.inline.} =
  msg in wEvent_StatusBarFirst..wEvent_StatusBarLast

method getIndex*(self: wStatusBarEvent): int {.property.} =
  ## Return the index of the field that was clicked.
  let lpnm  = cast[LPNMMOUSE](self.mLparam)
  result = int lpnm.dwItemSpec
