#====================================================================
#
#               wNim - Nim's Windows GUI Framework
#                 (c) Copyright 2017-2021 Ward
#
#====================================================================

## These events are generated by wTxtCtrl when mouse events occur over
## link or url.
#
## :Superclass:
##   `wCommandEvent <wCommandEvent.html>`_
#
## :Seealso:
##   `wTextCtrl <wTextCtrl.html>`_
#
## :Events:
##   ==============================  =============================================================
##   wTextLinkEvent                  Description
##   ==============================  =============================================================
##   wEvent_TextLink                 When mouse events occur over link or url.
##   ==============================  =============================================================

include ../pragma
import ../wBase

wEventRegister(wTextLinkEvent):
  wEvent_TextLink

method getStart*(self: wTextLinkEvent): int {.property, inline.} =
  ## Returns the start of the link.
  result = self.mStart

method getEnd*(self: wTextLinkEvent): int {.property, inline.} =
  ## Returns the end of the link.
  result = self.mEnd

method getMouseEvent*(self: wTextLinkEvent): UINT {.property, inline.} =
  ## Returns the mouse event.
  result = self.mMouseEvent
