#====================================================================
#
#               wNim - Nim's Windows GUI Framework
#                 (c) Copyright 2017-2021 Ward
#
#====================================================================

import ../winimx

## The key-code used in wNim functions. These constants are in fact
## Windows' virtual-key codes.

const
  wKey_None* = 0
  wKey_LButton* = VK_LBUTTON
  wKey_RButton* = VK_RBUTTON
  wKey_Cancel* = VK_CANCEL
  wKey_MButton* = VK_MBUTTON
  wKey_XButton1* = VK_XBUTTON1
  wKey_XButton2* = VK_XBUTTON2
  wKey_Back* = VK_BACK
  wKey_Tab* = VK_TAB
  wKey_Clear* = VK_CLEAR
  wKey_Return* = VK_RETURN
  wKey_Enter* = VK_RETURN
  wKey_Shift* = VK_SHIFT
  wKey_Control* = VK_CONTROL
  wKey_Ctrl* = VK_CONTROL
  wKey_Menu* = VK_MENU
  wKey_Alt* = VK_MENU
  wKey_Pause* = VK_PAUSE
  wKey_Capital* = VK_CAPITAL
  wKey_Kana* = VK_KANA
  wKey_Hangeul* = VK_HANGEUL
  wKey_Hangul* = VK_HANGUL
  wKey_Junja* = VK_JUNJA
  wKey_Final* = VK_FINAL
  wKey_Hanja* = VK_HANJA
  wKey_Kanji* = VK_KANJI
  wKey_Escape* = VK_ESCAPE
  wKey_Esc* = VK_ESCAPE
  wKey_Convert* = VK_CONVERT
  wKey_NonConvert* = VK_NONCONVERT
  wKey_Accept* = VK_ACCEPT
  wKey_ModeChange* = VK_MODECHANGE
  wKey_Space* = VK_SPACE
  wKey_Prior* = VK_PRIOR
  wKey_PgUp* = VK_PRIOR
  wKey_Next* = VK_NEXT
  wKey_PgDn* = VK_NEXT
  wKey_End* = VK_END
  wKey_Home* = VK_HOME
  wKey_Left* = VK_LEFT
  wKey_Up* = VK_UP
  wKey_Right* = VK_RIGHT
  wKey_Down* = VK_DOWN
  wKey_Select* = VK_SELECT
  wKey_Print* = VK_PRINT
  wKey_Execute* = VK_EXECUTE
  wKey_Snapshot* = VK_SNAPSHOT
  wKey_Insert* = VK_INSERT
  wKey_Delete* = VK_DELETE
  wKey_Help* = VK_HELP
  wKey_LWin* = VK_LWIN
  wKey_RWin* = VK_RWIN
  wKey_Apps* = VK_APPS
  wKey_Sleep* = VK_SLEEP
  wKey_Numpad0* = VK_NUMPAD0
  wKey_Numpad1* = VK_NUMPAD1
  wKey_Numpad2* = VK_NUMPAD2
  wKey_Numpad3* = VK_NUMPAD3
  wKey_Numpad4* = VK_NUMPAD4
  wKey_Numpad5* = VK_NUMPAD5
  wKey_Numpad6* = VK_NUMPAD6
  wKey_Numpad7* = VK_NUMPAD7
  wKey_Numpad8* = VK_NUMPAD8
  wKey_Numpad9* = VK_NUMPAD9
  wKey_Multiply* = VK_MULTIPLY
  wKey_Add* = VK_ADD
  wKey_Separator* = VK_SEPARATOR
  wKey_Subtract* = VK_SUBTRACT
  wKey_Decimal* = VK_DECIMAL
  wKey_Divide* = VK_DIVIDE
  wKey_F1* = VK_F1
  wKey_F2* = VK_F2
  wKey_F3* = VK_F3
  wKey_F4* = VK_F4
  wKey_F5* = VK_F5
  wKey_F6* = VK_F6
  wKey_F7* = VK_F7
  wKey_F8* = VK_F8
  wKey_F9* = VK_F9
  wKey_F10* = VK_F10
  wKey_F11* = VK_F11
  wKey_F12* = VK_F12
  wKey_F13* = VK_F13
  wKey_F14* = VK_F14
  wKey_F15* = VK_F15
  wKey_F16* = VK_F16
  wKey_F17* = VK_F17
  wKey_F18* = VK_F18
  wKey_F19* = VK_F19
  wKey_F20* = VK_F20
  wKey_F21* = VK_F21
  wKey_F22* = VK_F22
  wKey_F23* = VK_F23
  wKey_F24* = VK_F24
  wKey_Numlock* = VK_NUMLOCK
  wKey_Scroll* = VK_SCROLL
  wKey_OemNecEqual* = VK_OEM_NEC_EQUAL
  wKey_OemFjJisho* = VK_OEM_FJ_JISHO
  wKey_OemFjMasshou* = VK_OEM_FJ_MASSHOU
  wKey_OemFjTouroku* = VK_OEM_FJ_TOUROKU
  wKey_OemFjLoya* = VK_OEM_FJ_LOYA
  wKey_OemFjRoya* = VK_OEM_FJ_ROYA
  wKey_LShift* = VK_LSHIFT
  wKey_RShift* = VK_RSHIFT
  wKey_LControl* = VK_LCONTROL
  wKey_RControl* = VK_RCONTROL
  wKey_LMenu* = VK_LMENU
  wKey_RMenu* = VK_RMENU
  wKey_LCtrl* = VK_LCONTROL
  wKey_RCtrl* = VK_RCONTROL
  wKey_LAlt* = VK_LMENU
  wKey_RAlt* = VK_RMENU
  wKey_BrowserBack* = VK_BROWSER_BACK
  wKey_BrowserForward* = VK_BROWSER_FORWARD
  wKey_BrowserRefresh* = VK_BROWSER_REFRESH
  wKey_BrowserStop* = VK_BROWSER_STOP
  wKey_BrowserSearch* = VK_BROWSER_SEARCH
  wKey_BrowserFavorites* = VK_BROWSER_FAVORITES
  wKey_BrowserHome* = VK_BROWSER_HOME
  wKey_VolumeMute* = VK_VOLUME_MUTE
  wKey_VolumeDown* = VK_VOLUME_DOWN
  wKey_VolumeUp* = VK_VOLUME_UP
  wKey_MediaNextTrack* = VK_MEDIA_NEXT_TRACK
  wKey_MediaPrevTrack* = VK_MEDIA_PREV_TRACK
  wKey_MediaStop* = VK_MEDIA_STOP
  wKey_MediaPlayPause* = VK_MEDIA_PLAY_PAUSE
  wKey_LaunchMail* = VK_LAUNCH_MAIL
  wKey_LaunchMediaSelect* = VK_LAUNCH_MEDIA_SELECT
  wKey_LaunchApp1* = VK_LAUNCH_APP1
  wKey_LaunchApp2* = VK_LAUNCH_APP2
  wKey_Oem1* = VK_OEM_1
  wKey_OemPlus* = VK_OEM_PLUS
  wKey_OemComma* = VK_OEM_COMMA
  wKey_OemMinus* = VK_OEM_MINUS
  wKey_OemPeriod* = VK_OEM_PERIOD
  wKey_Oem2* = VK_OEM_2
  wKey_Oem3* = VK_OEM_3
  wKey_Oem4* = VK_OEM_4
  wKey_Oem5* = VK_OEM_5
  wKey_Oem6* = VK_OEM_6
  wKey_Oem7* = VK_OEM_7
  wKey_Oem8* = VK_OEM_8
  wKey_OemAx* = VK_OEM_AX
  wKey_Oem102* = VK_OEM_102
  wKey_IcoHelp* = VK_ICO_HELP
  wKey_Ico00* = VK_ICO_00
  wKey_ProcessKey* = VK_PROCESSKEY
  wKey_IcoClear* = VK_ICO_CLEAR
  wKey_Packet* = VK_PACKET
  wKey_OemReset* = VK_OEM_RESET
  wKey_OemJump* = VK_OEM_JUMP
  wKey_OemPa1* = VK_OEM_PA1
  wKey_OemPa2* = VK_OEM_PA2
  wKey_OemPa3* = VK_OEM_PA3
  wKey_OemWsctrl* = VK_OEM_WSCTRL
  wKey_OemCusel* = VK_OEM_CUSEL
  wKey_OemAttn* = VK_OEM_ATTN
  wKey_OemFinish* = VK_OEM_FINISH
  wKey_OemCopy* = VK_OEM_COPY
  wKey_OemAuto* = VK_OEM_AUTO
  wKey_OemEnlw* = VK_OEM_ENLW
  wKey_OemBacktab* = VK_OEM_BACKTAB
  wKey_Attn* = VK_ATTN
  wKey_Crsel* = VK_CRSEL
  wKey_Exsel* = VK_EXSEL
  wKey_Ereof* = VK_EREOF
  wKey_Play* = VK_PLAY
  wKey_Zoom* = VK_ZOOM
  wKey_Noname* = VK_NONAME
  wKey_Pa1* = VK_PA1
  wKey_OemClear* = VK_OEM_CLEAR
  wKey_A* = ord 'A'
  wKey_B* = ord 'B'
  wKey_C* = ord 'C'
  wKey_D* = ord 'D'
  wKey_E* = ord 'E'
  wKey_F* = ord 'F'
  wKey_G* = ord 'G'
  wKey_H* = ord 'H'
  wKey_I* = ord 'I'
  wKey_J* = ord 'J'
  wKey_K* = ord 'K'
  wKey_L* = ord 'L'
  wKey_M* = ord 'M'
  wKey_N* = ord 'N'
  wKey_O* = ord 'O'
  wKey_P* = ord 'P'
  wKey_Q* = ord 'Q'
  wKey_R* = ord 'R'
  wKey_S* = ord 'S'
  wKey_T* = ord 'T'
  wKey_U* = ord 'U'
  wKey_V* = ord 'V'
  wKey_W* = ord 'W'
  wKey_X* = ord 'X'
  wKey_Y* = ord 'Y'
  wKey_Z* = ord 'Z'
  wKey_0* = ord '0'
  wKey_1* = ord '1'
  wKey_2* = ord '2'
  wKey_3* = ord '3'
  wKey_4* = ord '4'
  wKey_5* = ord '5'
  wKey_6* = ord '6'
  wKey_7* = ord '7'
  wKey_8* = ord '8'
  wKey_9* = ord '9'
